### ISSUE TITLE
Grabbed object lags behind controller

### ISSUE THREAD

**Issue by MrJimbones** [thestonefox/SteamVR_Unity_Toolkit#108]
Hi,
First of all I really want to say thank you for making this available. It's obviously required a lot of hard work and passion making these assets so much more user friendly.
The issue I'm having may have been addressed before (I think I read a couple of posts regarding it) but I still cant seem to wrap my head around it. Sorry, I'm really new at all this..
My problem is that I am trying to use this asset: 

https://www.assetstore.unity3d.com/en/#!/content/61830

With your toolkit but anything I'm holding in my hand while using the thrusters just lags so far behind the controller. I'm sure I could figure it out eventually, but I guess I'm mostly curious as to whether I am fighting a losing battle here.
The idea is to be able to fly around using the thrusters while picking up guns/items around the map and shoot at stuff. Is this even possible with this kind of physics? I would very much love to know whether or not my trials are futile so I can start thinking of other ways to do it if so be the case.

Again, my apologies if you have already covered this and I'm just being dense. Thank you!

**Comment by thestonefox** [comment]
What sort of grab type are you using? joint or track object?

Also, it all depends on how that other asset is moving you around the world

**Comment by MrJimbones** [comment]
I thought that might have something to do with it. (The other asset's methods) 
I did try both joint and track. One seemed to be less of a "problem" but ultimately had the same thing happen. I guess I'll just have to look into another means of "jetpacking" around and see if that solves it..lol

**Comment by thestonefox** [comment]
I'll try download that asset and take a look over the weekend

**Comment by MrJimbones** [comment]
That would be most gracious of you. Of course take your time and absolutely no obligation. In the unlikely event that I figure anything out regarding this I'll post. ;D

**Comment by TangoTwoNine** [comment]
I had the same issue with UI attached to the controller while "jetpacking". Try to set the object as a child of the controller and see if it works better for you.

**Comment by MrJimbones** [comment]
Very cool. I thought I had tried that already, but honestly ive tried so many different things now that I could be totally wrong (and dreamed it maybe? Haha..).
 I'll give it a go here in a few. Thanks for the idea! :)

**Comment by thestonefox** [comment]
A new grab type is coming soon, called child to controller, which does this parent thing for you. It's in the archery branch if you want to check it out

**Comment by MrJimbones** [comment]
This works beautifully! Thank you so much!! :D

**Comment by thestonefox** [comment]
new Child To Controller grab type is in after commit 08a2cc0c24c830f00c5150f170c34492ad12ce4f

so this can be resolved using that grab type now.
