### ISSUE TITLE
Option to enable isTrigger on Collider when grabbed.

### ISSUE THREAD

**Issue by mmealman** [thestonefox/SteamVR_Unity_Toolkit#110]
For "grab a sword, have it replace your controller" actions you sort of don't want it to collide with real world objects and bend around in your hand. A pretty simple tweak for this is in InteractableObjects adding:

    public bool enableIsTrigger = false;

to grab interactions and changing grabbed and ungrabbed:

    public virtual void Grabbed(GameObject currentGrabbingObject)
    {
        ForceReleaseGrab();
        RemoveTrackPoint();
        grabbingObject = currentGrabbingObject;
        SetTrackPoint(grabbingObject);
		if (enableIsTrigger) {
			this.GetComponent<Collider> ().isTrigger = true;
		}
    }

    public virtual void Ungrabbed(GameObject previousGrabbingObject)
    {
        RemoveTrackPoint();
        grabbingObject = null;
		if (enableIsTrigger) {
			this.GetComponent<Collider> ().isTrigger = false;
		}
    }

This changes the object into something you can swing around and pass through objects, but you should still be able to detect trigger actions on the thing you're holding and have it apply sounds, damage, etc based on the normal Collider that enters/exits it.

I'm not sure if this is the best way to handle this though.

**Comment by thestonefox** [comment]
The easiest way to do this is to set the grab attach type to "child to controller". Then it won't clip with anything, the example scene (haptic rumble) has already been updated to demo this

**Comment by mmealman** [comment]
That works great. Thanks.
