### ISSUE TITLE
Texture size and necessity

### ISSUE THREAD

**Issue by TobiasPott** [thestonefox/SteamVR_Unity_Toolkit#113]
Hi, 

this is actually not a direct technical or functional issue with your toolkit as it works like charm making things easy as pie for us at work.
Unfortunately some textures are very big and blow up the size of the download of the github repository.
It would be helpful if some of the included textures would be downsized to a more appropiate size as all examples use a strong stylized look without textures and very high details arn't necessary.
You may look into the "Resources\Free_Rocks\_textures" folder for the "rocks..." textures (which are saved with 4k resolution).
I'm not sure whether this opened issue will suffice or if I should create a fork and pull request just for changed texture resolutions).

Best Regards and thank you for this package =)
Tobias

**Comment by thestonefox** [comment]
sure no worries. Those free rock ones are from the unity asset store ( i needed to have a mesh collider example).

But yeah there's really no need for large textures to be included as examples.

**Comment by thestonefox** [comment]
Fixed in cf5874a8c58c12487ac1eb9ceee84e778e6cecf5

**Comment by TobiasPott** [comment]
Awesome. Nice to see this quicker reaction :-)
