### ISSUE TITLE
Disable bezier/simple teleporter on controller collision with "excludeteleport" tagged object.

### ISSUE THREAD

**Issue by x-mugen-x** [thestonefox/SteamVR_Unity_Toolkit#118]
To stop players physically reaching through walls tagged with "excludeteleport" (in the height adjust teleport script) and getting into areas they shouldn't :) Even double walling doesn't seem effective in stopping them doing this. Disabling tele on collision then re-enabling after they release the grip should suffice.

**Comment by thestonefox** [comment]
Thos should be achievable, the headset collision fade script when attached to the headset emits an on headset collision event. 

The teleporter could listen to this and prevent teleport if it's been clipped.

I'll look to introduce this feature soon.

**Comment by x-mugen-x** [comment]
Sounds great. Cheers!

**Comment by thestonefox** [comment]
Completed in 6a624bf4de765a2821b83b37e12e40093fe9c64c
