### ISSUE TITLE
[bug] The legacy Animation Clip "BowPullAnimation" cannot be used in the State "BowPullAnimation". Legacy AnimationClips are not allowed in Animator Controllers.

### ISSUE THREAD

**Issue by thedonquixotic** [thestonefox/SteamVR_Unity_Toolkit#119]
Just loaded up one of the example scenes in Unity 5.3. I've already built my own scene using the SteamVR toolkit int he asset store so I know I have my settings right. I got this legacy bow pull animation alert. I've only been doing Unity for a little while so I have trouble knowing how this issue is changed, but I'm guessing it's something to do with differences in versions and older syntax being phased out of Unity releases?

**Comment by thestonefox** [comment]
Not sure what you're doing.

Could you explain step by step how you're creating this issue.

Where is your animator controller?
