### ISSUE TITLE
[Structure] Separate out destination event from world pointer

### ISSUE THREAD

**Issue by thestonefox** [thestonefox/SteamVR_Unity_Toolkit#120]
The world pointer is responsible for setting the teleport destination, but sometimes you may want to use the destination set code in another mechanic

I'm suggesting a new abstract class that the world pointer then extends.

**Comment by GavinRace** [comment]
I was the one talking to you on YouTube about this. Thanks for trying to add this enhancement! Looking forward to try it out and cleaning up my hacked attempts at making it work.

**Comment by thestonefox** [comment]
Trello Card https://trello.com/c/I44onSyq

**Comment by thestonefox** [comment]
Completed with f94d7899ed97e9263b204b7f12c60f6de3362e2b
