### ISSUE TITLE
[Controller] Ability to disable teleport or touchpad walking for specific controller

### ISSUE THREAD

**Issue by thestonefox** [thestonefox/SteamVR_Unity_Toolkit#123]
The teleport and touchpad walking scripts both listen out for controller events (via the controller manager).

If the teleport and touchpad walking script had an option to toggle the listening off/on for the controller then it wouldn't be affected by that controller.

Useful if you only want touchpad walking to work on one controller.

**Comment by drifio** [comment]
Not sure if this is any good, but I was messing with this in my own project:

14c5a0090816ad47d2e57b4dad453c845d8bb4ce

Only issue is that without a custom Editor, when you change a property (exposed via [SerializeField]) in the Unity editor, the setter isn't run so it won't toggle the listeners. Other than that, it seems to work ok. Not sure if the approach is correct or one you'd like to take, but it might be worth a look.

**Comment by thestonefox** [comment]
@drifio neat idea.

I was considering just returning out of the callback if the controller wasn't set

here: https://github.com/thestonefox/SteamVR_Unity_Toolkit/blob/master/Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_TouchpadWalking.cs#L34-L37

So have a couple of bool params for each controller, and then use the controller manager to know the index, the payload (e) contains the controller index and if the index is ignored then just don't update the axis variables.

So the listener would always be attached.

Easier to implement, but means listeners are attached that never work (unless you toggle the bool during runtime then it's already set)

In your version, does it matter if the listeners don't toggle in the editor? Do they still work at runtime?

**Comment by drifio** [comment]
At runtime if you set the bools to true or false, the listeners are attached/detatched accordingly. I implemented it like this so you could change hand in an options screen in-game for example. It's possible to make it work in the editor too, just need a small editor script.

**Comment by thestonefox** [comment]
Trello Card https://trello.com/c/q24itIXB

**Comment by drifio** [comment]
Made a PR with my touchpad walking toggle, don't feel like there's a need to add a toggle to the teleport script however, as there is currently a requirement for a pointer for those to work, and the pointer has a teleport on/off toggle.

**Comment by thestonefox** [comment]
Yeah the destination set event allows for the enableTeleport bool, so you could just disable it at that point rather than adding more things to toggle the listeners.

**Comment by thestonefox** [comment]
Completed with 52578c3c67161e010320b8b357628fc27e07b25f

thanks @drifio :heart: :green_heart: :blue_heart: :yellow_heart:
