### ISSUE TITLE
Improvement(Use Unity 5.4 Beta): SteamVR Plugin not working with 5.3.5

### ISSUE THREAD

**Issue by appdevtk** [thestonefox/SteamVR_Unity_Toolkit#124]
I have tried to install Unity 5.3 with the newest SteamVR Plugin to debug my feature for this project, but all I get are compile errors from the plugin. Lightprobes not found etc.

I suggest to move the support to Unity 5.4 because it dramatically increased the rendering performance for VR [(Blogpost)](http://blogs.unity3d.com/2016/03/15/enhanced-visuals-better-performance-and-more-the-unity-5-4-public-beta-is-ready/) and Valve released the [Lab Renderer](https://www.assetstore.unity3d.com/en/#!/content/63141) (Adaptive Quality with MSAA) for Unity 5.4.

Are there any concerns? Is there a real reason to support 5.3?

**Comment by thestonefox** [comment]
5.4 is still in beta. It's not wise to support only a product that is in beta. Many people still use 5.3 because it is the stable release.

**Comment by appdevtk** [comment]
Thats true. I thought the time to market for VR games is great enough to start using 5.4 [Release Target June 2016](https://unity3d.com/unity/roadmap). But I could turn my features on and off depending on the Unity version.
