### ISSUE TITLE
Highlight on Trigger Hold

### ISSUE THREAD

**Issue by graydetroit** [thestonefox/SteamVR_Unity_Toolkit#125]
When using a tracked controller to Touch and Use an Interactable Object that is Usable with Highlight on Touch checked, pressing and holding the Trigger button to Use the Interactable Object removes the Highlighted color. I'd like to be able to keep the Object highlighted while Holding the Trigger to Use it.

**Comment by thestonefox** [comment]
The touch highlight colour is (should) be turned off whenever a grab/use interaction happens.

If you take a look at the code here:

https://github.com/thestonefox/SteamVR_Unity_Toolkit/blob/master/Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_InteractGrab.cs#L277

and here:

https://github.com/thestonefox/SteamVR_Unity_Toolkit/blob/master/Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_InteractUse.cs#L111

You can see the grab and the use intentionally turn the highlight colour off.

I can add an option on the grab/use script that prevents this from being toggled off if you want?

I won't be able to do it till early next week though :/

**Comment by graydetroit** [comment]
Oh ok thanks! No problem, I can probably just do this myself and submit a PR.
