### ISSUE TITLE
Color IndexOutOfRangeException: Array index is out of range.

### ISSUE THREAD

**Issue by B33T** [thestonefox/SteamVR_Unity_Toolkit#126]
I have a tank that spawns bullets in my game and you can pick up the tank, it highlights on pickup the bullets then die/destroy.
I think whats happening is the object is being destroyed as the color is changed so it doesn't exist any more. 
So in gameplay you pick up the tank during combat(await a bullet to die), the tank then goes "black" which i think is the global color(even though a color is set on the gameobject. then as soon as you highlight it again it goes "white" and crashes out with the below error.

The following throws up the error

`   private void ChangeColor(Color[] colors)
    {
        Renderer[] rendererArray = GetRendererArray();
        int i = 0;
        foreach (Renderer renderer in rendererArray)
        {
            if (renderer.material.HasProperty("_Color"))
            {
                renderer.material.color = colors[i];
            }
            i++;
        }
    }`

IndexOutOfRangeException: Array index is out of range.
VRTK_InteractableObject.ChangeColor (UnityEngine.Color[] colors) (at Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_InteractableObject.cs:345)
VRTK_InteractableObject.ToggleHighlight (Boolean toggle, Color globalHighlightColor) (at Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_InteractableObject.cs:205)
VRTK_InteractableObject.ToggleHighlight (Boolean toggle) (at Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_InteractableObject.cs:182)
VRTK_InteractTouch.OnTriggerExit (UnityEngine.Collider collider) (at Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_InteractTouch.cs:130)

**Comment by thestonefox** [comment]
Any chance you can make a branch that shows the issue then it will be easier to fix 😃

**Comment by thestonefox** [comment]
Found the issue, have a solution to not use an array to store the colours but to use a dictionary to store the colours against the name of each object to prevent the list from getting out of sync.

Fix coming soon!

**Comment by thestonefox** [comment]
Fixed with 5c54691c6fd1aea7e52b4ae43ea418de9b892d55
