### ISSUE TITLE
Snap to a Handle

### ISSUE THREAD

**Issue by IARI** [thestonefox/SteamVR_Unity_Toolkit#127]
I don't find the snap mechanics very comfortable, in case there are many objects that have a handle i want to snap to.

I would prefer if there could be a Handle child Gameobject.
The snap mechanics should use the handles position and Orientation, instead of the public field currently used.

The handle could be optional, or whatever. but i don't want to manually have to set angles and positions. And well if so, then at least i would like to have some gizmos drawn.

**Comment by drifio** [comment]
I implemented this already in my local version, if nobody else proposes a solution, I'll make a pull request when I get home tonight.

**Comment by thestonefox** [comment]
If you do implement this then make it an optional extra. Don't replace the public rotation and position fields in case people are using them.

I'm not around till Tuesday to review any pull requests, but feel free to make one :)

**Comment by drifio** [comment]
My current implementation does not change the way it currently works if not utilised, so it shouldn't cause any conflicts with the existing system. I'll run over it and double check everything tonight though, ta.

**Comment by thestonefox** [comment]
Do you have a parameter on the script that you drag the empty game object in to? I'm guessing it only supports child on controller too?

**Comment by drifio** [comment]
Yeah, you drop a transform in, and when you grab the object the attachment point + rotation of the object you have grabbed is that of the transform. Afaik I also implemented an additional VRTK_InteractableObject.GrabSnapType to avoid this functionality interacting with other GrabSnapTypes, but it was quick solution so it probably needs a bit of extra thought & tidying.

**Comment by drifio** [comment]
Just submitted a pull request with my changes. It's not a huge update, and it's pretty straightforward. Seems to work just fine with both Child of controller and Fixed joint. The way it works is you add a gameobject as a child to the VRTK_InteractableObject, and then drag that into the Snap Handle slot. When you grab the object, the grab point will then be that transform's position. Any rotation applied to this transform will cause the object to rotate around it.

**Comment by thestonefox** [comment]
Completed with commit d5a5585397073968347a68f9e64fd78b4987e808

Thanks to @drifio :heart: :green_heart: :yellow_heart: :blue_heart:

**Comment by IARI** [comment]
yay, thanks a lot :)

**Comment by RoccoGD** [comment]
Yes thank you, would love to see a little example for it.

**Comment by thestonefox** [comment]
Ok no worries, I'll update one of the existing scenes to demo it.

**Comment by RoccoGD** [comment]
Thank you very much, you are doing an amazing job!
I also would love to have a place (forum?) to talk with you more freely about the Toolkit and maybe with other developers to share ideas, suggest new features and help each other.

**Comment by thestonefox** [comment]
@RoccoGD There was talk of a slack channel. I'm happy to set one up if people are interested?

**Comment by thestonefox** [comment]
Ok quick slack channel for those who are interested:

https://steamvr-unity-toolkit.slack.com

I'll update the readme to publicise it too.

**Comment by thestonefox** [comment]
This commit updates an example scene:
c1023618ac1d7f88759638b8352179717f68c53e

**Comment by spaggi** [comment]
Hey mate,

Sorry for the potential stupid question but I'd love to join the slack community however it seems that you need to invite people in order for them to join.

Would you invite me?

Thank you so much for your effort

Von meinem iPhone gesendet

**Comment by thestonefox** [comment]
I wonder if slack isn't the best thing if I have to keep inviting people. Maybe an IRC channel would be better?

**Comment by teatime** [comment]
You can change it so that people signup via email, then you just need to
publish the group details on something like http://www.slacklist.info/

*Allowing email signup*
If email signup is enabled for your team, new members will be able to
create an account on their own. Team Owners can manage this option under *Team
Sign Up Mode* on the Team Settings <https://my.slack.com/admin/settings>
page.

**Comment by thestonefox** [comment]
@teatime I'm only getting two options on Team Options:

* Invite Only
* Any email addresses from these domains

Meaning I have to provide a list of domains that accepted emails come from.

I wonder if email sign up is a paid for thing?

**Comment by thestonefox** [comment]
I'll take a look at https://github.com/rauchg/slackin in the morning.

**Comment by Locxion** [comment]
Umm ... i dont know if this is up to date but ... how about using gitter?
https://gitter.im/

**Comment by drifio** [comment]
We're set up and using slack pretty regularly now. Click the slack button on the README to sign up :)
