### ISSUE TITLE
[Controller] Provide haptic feedback on interactions

### ISSUE THREAD

**Issue by thestonefox** [thestonefox/SteamVR_Unity_Toolkit#13]
Make the controller rumble when a user touches, grabs or uses something.

Perhaps you could have a global rumble amount that is overriden by the touching object?

**Comment by thestonefox** [comment]
I think the controller events could have a public method to call the rumble code. Then you can call it yourself whenever you want.

And the interactable object can have a rumble amount for touch, grab, use. Perhaps have a global rumble amount on interact classes too

**Comment by thestonefox** [comment]
I'm not sure why the SteamVR_Controller TriggerHapticPulse method only works when it's continuously called. It seems the `ushort duration` parameter is actually the strength of the vibration and has nothing to do with the amount of time the vibration lasts for.

This is why when it's called within a button press code nothing appears to happen because the vibration happens for a split second.

This commit: 2dbcff7bf3d833379c63ed59d86de6a681c59f5e

Adds a working version of the haptic feedback on the controllers and includes a `duration` and `strength` parameter.

**Comment by rmoussawi** [comment]
Copying my request from my youtube conversation with you :)

Can you please include the following to your upcoming video?

"Do an example scene where a collision whilst holding an object causes the rumble"

Thanks a lot!

**Comment by thestonefox** [comment]
Completed with e8e3bfe66a0d4b5b9ae2d4db8e37f7cf476fecd4
