### ISSUE TITLE
New Interactions

### ISSUE THREAD

**Issue by 10FingerArmy** [thestonefox/SteamVR_Unity_Toolkit#130]
While the initial functionality is awesome already it would be really great to go more into the interaction direction now. It would be great to gradually build up a library of interaction possibilities. Job Simulator is a great example here of what could be done.

- Push-Button
- Toggle-Switch (e.g. light switch)
- Slider (continuous or stepwise)
- Lever
- Box-Lid being fully detachable
- Copy-Machine-like Lid attached on one side rotating only in set boundaries
- Wheel (e.g. safe)
- ...

Especially the button introduces a new concept to VRTK I think as here the controller would act as the force without pushing any controller buttons. Gradually moving the controller down the button should also gradually push the button down until that one reaches a certain push limit and triggers the action. The computer keys in job simulator are perfect examples.

Also it would be great to showcase some sample interactions like pulling out a drawer (with limits).

**Comment by thestonefox** [comment]
If you look at the grabbing objects with joints example. It covers a number of these suggestions.

Things like buttons and switches I would assume would be just rigid bodies with animations for the mechanism. Levers and wheels could just use joints. If any one wants to update the examples, that would be helpful

**Comment by 10FingerArmy** [comment]
I will split this issue into multiple ones for discussing the best approaches.

**Comment by thestonefox** [comment]
Let's close this but reference the first issue that's been created in relation to it:

https://github.com/thestonefox/SteamVR_Unity_Toolkit/issues/146
