### ISSUE TITLE
VRTK_SimplePointer works in Unity editor but not in build

### ISSUE THREAD

**Issue by sommerper** [thestonefox/SteamVR_Unity_Toolkit#132]
As the title says VRTK_SimplePointer works perfectly fine when testing in the editor. As soon as I build and run the .exe pressing any of the grip buttons does not activate the laser pointer.

I do get a lot of NullReferenceException errors as shown in the screenshot.

![vrtk_simplepointererror](https://cloud.githubusercontent.com/assets/1512048/15808628/87a3b1c0-2b7c-11e6-9aba-761b3cf00c19.png)

**Comment by thestonefox** [comment]
This FAQ is your friend:)

https://youtu.be/IsmYoLTmX4c

**Comment by sommerper** [comment]
Auch. Wrist slaps for not RTFM.

**Comment by ssshake** [comment]
This also breaks the bow, arrow and arrow spawner in the example level. I was relying on this for my game and a recent change broke all of this. Looks like adding the unlit shader to your graphics project settings is a big one to miss. I know 2.2.1 is dated but I made some bad coding decisions and I'm heavily coupled to it. I need to carve out so time for a migration.
