### ISSUE TITLE
Boolean option for non-detachable objects

### ISSUE THREAD

**Issue by Roland09** [thestonefox/SteamVR_Unity_Toolkit#138]
There should be a boolean option which defines whether an object is detachable or not.

I created a sword example and sometimes the sword was taken out of my hands for some reason. I found out that there is some detach parameter which seems to be physics based and depending on at which force another object collides with the object the player is holding.

In my case the player should never lost his sword, no matter how big the force is that collides with the sword.

**Comment by drifio** [comment]
Try using the "Child of controller" grab attach mechanic, afaik that's exactly what it's for.

**Comment by Roland09** [comment]
Yes, that worked. Thanks!

**Comment by thestonefox** [comment]
There is also another thing that you can't currently do.

The ability to never drop an object even if you press the grab button (which goes well with your auto grab on start issue).

I need to make some changes to allow for this, but I think it's worthwhile that you start a game with an object and you never can let it go.

**Comment by Roland09** [comment]
Brookhaven Experiment has that. You start with a flashlight and a gun which you can never drop.

**Comment by thestonefox** [comment]
I may take a look at this today along with the auto spawn an item into your hand (as they go together)
