### ISSUE TITLE
Initially put object into the player's hands

### ISSUE THREAD

**Issue by Roland09** [thestonefox/SteamVR_Unity_Toolkit#139]
There should be a method which allows you to place an object into the player's hands when the game starts, i. e. without the player having to grab something first.

**Comment by thestonefox** [comment]
I have just written a script that does exactly this :)

You can achieve it by using the ForceTouch and AttemptGrab methods. But I'll provide an example scene with a test script that shows how it's done

**Comment by Roland09** [comment]
That's great! Looking forward to trying it.

**Comment by thestonefox** [comment]
Trello Card https://trello.com/c/tjhO04ZQ

**Comment by thestonefox** [comment]
Completed with: 3731f999b232d63d3c57394b1638d78ba2f9ef8f
