### ISSUE TITLE
Errors in "SteamVR_ControllerInteract"

### ISSUE THREAD

**Issue by thesbros** [thestonefox/SteamVR_Unity_Toolkit#14]
I get the following errors when I try to use the `003_Controller_SimplePointer` example:
```csharp
Assets/SteamVR_Unity_Toolkit/Scripts/SteamVR_ControllerInteract.cs(118,50): error CS1061: Type `SteamVR_ControllerEvents' does not contain a definition for `AliasInteractOn' and no extension method `AliasInteractOn' of type `SteamVR_ControllerEvents' could be found (are you missing a using directive or an assembly reference?)
Assets/SteamVR_Unity_Toolkit/Scripts/SteamVR_ControllerInteract.cs(119,50): error CS1061: Type `SteamVR_ControllerEvents' does not contain a definition for `AliasInteractOff' and no extension method `AliasInteractOff' of type `SteamVR_ControllerEvents' could be found (are you missing a using directive or an assembly reference?)
```

**Comment by thestonefox** [comment]
Are you using an old version of the repository?

The SteamVR_ControllerInteract script no longer exists and has now been replaced with:

SteamVR_InteractTouch, SteamVR_InteractGrab, SteamVR_InteractUse

You may need to get the latest version of the repository (and remove all existing files from the old repo you pulled down)

**Comment by thesbros** [comment]
I updated just today but I guess it merged instead of replacing. I was using ControllerInteract, is there anything I need to change to use InteractTouch or just simply replace it?

**Comment by thestonefox** [comment]
Yeah, the project is changing so much at the moment it's pretty much breaking changes when a new version comes out. This should calm down when I figure out how things will be structured, so it just means a little manual housekeeping whilst I sort it :)

ControllerInteract doesn't exist now, so where as before you'd put that script on a controller you now have to:

  * Put the SteamVR_InteractTouch on the controller (this gives the touch ability)
  * If you want grabbing ability you put SteamVR_InteractGrab on the controller as well
  * If you want using ability you put SteamVR_InteractUse on the controller as well

If you look at 004_CameraRig_BasicTeleport and look at the controllers you'll see the new scripts required to get the same functionality.

**Comment by thesbros** [comment]
Alright, thanks. I will close this because it seemed to be my error.
