### ISSUE TITLE
Donation

### ISSUE THREAD

**Issue by Roland09** [thestonefox/SteamVR_Unity_Toolkit#140]
Since you commented on youtube that there is no forum and I should use the "issues" section here: Is there a way for donations (paypal) to you? I'd like to show support, but in my opinion a donation should at least give you a pizza, but buying Holodaze isn't even a burger ;-)

**Comment by kjm16** [comment]
Honestly he should just setup his own website and sell Holodaze as a "Pay what you want" download/key.

**Comment by thestonefox** [comment]
I did have Holodaze on itch.io but when I implemented all the Steam specific stuff, it was becoming a chore to maintain a steam version and a everywhere else version.

I'm happy for people to just buy and play Holodaze (I hope people enjoy it!)

I'm making some changes this week where there are leaderboards per difficulty level as the current single high score table is getting to the point of being unbeatable! Even I can't get number 1 now :p 

If you'd like to support more, then just make a post on Reddit promoting holodaze, or do a video on youtube playing it, that promotion just leads to more sales (usually) which just means you've helped contribute more to me :)

**Comment by Roland09** [comment]
Ok, as you wish. Just bought Holodaze. References to Holodaze will follow.

Btw: Thanks for your awesome framework!

If I may ask and if it isn't a secret: How many copies does one sell with a VR game like Holodaze these days? I'm not planning into going into business, I'm just curious because some guy obviously bought a 30$ bowling game asset, attached steamvr to it and sold it on Steam for 20$. I guess he made a few thousand dollars.

Is this issue supposed to be closed now? Otherwise it'll show up as open issue.

**Comment by thestonefox** [comment]
@Roland09 Thanks for the purchase! Glad you're liking the framework too :)

Holodaze hasn't sold all that many copies, I have more stars on this repository than copies sold :P 

It seems only a few games sell really well, things like Holopoint, Audioshield, Holoball, Cyberpong have all sold very well, and Lightblade VR sold a bucket load.

I guess it's just a matter of what people are interested in, I've not broken even with the cost of publishing Holodaze, let alone make any money out of it.

Making and selling games can be an odd affair. As you say, someone buys a cheap asset and sells thousands, whereas someone else can have an original idea and no one cares.

I had lots of negative feedback in the greenlight process, people saying the graphics were rubbish therefore the game was rubbish. A lot of, it lacks polish, which translates into people not wanting to buy something unless it has great graphics, which is a shame.

I'm happy to keep this issue open as a discussion point for others :)

**Comment by drifio** [comment]
On the graphics issue, I'm definitely feeling the weight of that. Take something like Vanishing Realms which uses asset store stuff and looks like it's done pretty well. Makes me consider buying assets for my project, but at the same time it takes so much charm away from it.

**Comment by thestonefox** [comment]
Vanishing realms does look really nice. But also it helps having someone with creative flair working on the project too.

I'm not the most graphically gifted person and when you're working on something on your own, even if you have asset store assets then you can end up still looking rough.

Shame though, because some games do really well with lower quality graphics and has no impact on their game play (binding of issac, nidhogg, minecraft, etc)

**Comment by paulc755** [comment]
Bought, bit of a bargain for all the work you are putting into this toolkit, thank you.

**Comment by thestonefox** [comment]
@paulc755 
Is it downloading ok for you? I've just pushed an update to steam and now it's not downloading at all for me! Stupid steamworks :/

**Comment by paulc755** [comment]
It is downloading sort of, being very slow though,  35 MB download on a 100 mbps line 5 minutes! perhaps there is an issue with steam, still hasn't finished. Ah "an error has occurred" Seems stuck with 1 second to go. So I'd have to say it is not downloading.

**Comment by thestonefox** [comment]
@paulc755 
I've just rolled it back to version 1.4.0.0 to see if I can figure out what's wrong. Give it 10 minutes and try again (you may need to uninstall it)

**Comment by paulc755** [comment]
Eventually comes up with "connection Time out"

**Comment by paulc755** [comment]
will do

**Comment by paulc755** [comment]
@thestonefox 
Ok The roll back downloaded and installed without issues.

**Comment by thestonefox** [comment]
Ok I've just pushed the update and it seems to be working again now.

You should now have difficulty mode high scores as well as overall high scores (I've just dominated the easy mode and overall high score table!)

**Comment by paulc755** [comment]
Wouldn't want to suffer with vertigo! I always find it amazing that my brain is telling me I am standing on a ledge and not the carpet. Very entertaining, now I just need to work how not to get shot in the first 5 seconds.

**Comment by thestonefox** [comment]
Dodge and move is the best advice I can give. Listen out for the shots and just teleport like crazy.

Also, stay on the green sides of the cubes to be in a normal standing position, if you're on the side or underneath of a cube it makes throwing harder!

**Comment by bcoyle** [comment]
Love this post. I'm going to make sure to pick up Holodaze today! I think you could also put up a place to charge for the Unity VR Toolkit. Maybe giving the donors extra preference to their suggestions to the direction/features the kit goes in. I'm more a fan of tools for VR than games for VR. At the moment at least.

**Comment by Roland09** [comment]
@thestonefox: I read today that the lightsaber game sold 5000 copies within 5 days. 

Regarding games altogtether: I figured that I usually buy games when there is a demo and the demo is good. You don't get demos these days anymore. Steam has the refund policy, but that seems like abusing a system.

Regarding Holodaze: My opinion: the gfx looks out of date, but that wasn't my concern. I didn't want to buy it and rather give a donation because the sound in the trailer on Steam is just awful for my likings.

**Comment by thestonefox** [comment]
@Roland09 just buy it and never install it then :p 
You can also turn off the music and announcer sounds if you want to play but not listen to the music :)

**Comment by Roland09** [comment]
@thestonefox: that's what I did, I bought and didn't install - so far :D  But I have to take a look when I find the time. The problem with the vive games is that they look cheap, but once you are in VR they are awesome. Take e. g the Brookhaven Experiment. Or Space Pirate Trainer. It looks rather boring in the Steam videos, but it's one of the best games I've played in VR.

Regarding music: That's not what I meant. It's the trailer's music that didn't make me want to buy the game. But maybe that's just me. I learned from other developers that impressions are important. So I just wanted to let you know.

**Comment by thestonefox** [comment]
The trailer music is the same in game music :) so being able to turn that off will be a godsend for you! :p 

But yeah, I know what you mean about first impressions. I was the same about minecraft for ages, thought it looked rubbish, till I actually played it.

**Comment by thestonefox** [comment]
Any objections to closing this thread and moving it to the sub reddit?

**Comment by Roland09** [comment]
No, please close it. Thank you for your contributions.

**Comment by thestonefox** [comment]
Continue the discussion over here:

https://www.reddit.com/r/SteamVRUnityToolkit/comments/4n3q8h/donations_a_continuation_of_the_github_issue/
