### ISSUE TITLE
Add touchpad angle as the .z component in touchpadAxis

### ISSUE THREAD

**Issue by Tenebrous** [thestonefox/SteamVR_Unity_Toolkit#141]
In some cases I've found it really useful to have the angle the users finger is around the centre of the touchpad available in all the touchpad events.

E.g. if you divide the pad up into sections, each of which does a different thing.

0 degrees would be up and 90 would be right.

**Comment by thestonefox** [comment]
I like the idea. Is this something you could do a PR on?

**Comment by Tenebrous** [comment]
Yep absolutely, will do that later

**Comment by Tenebrous** [comment]
Done - however I've added it as an extra field rather than the .z of
.touchpadAxis.  I think the ability to get the magnitude of .touchpadAxis
is useful and would be broken by adding the angle to .z.

**Comment by thestonefox** [comment]
Completed with 0e5ccab5da13478990055ceec7e4750278435c4f

Thanks @Tenebrous :heart: :green_heart: :blue_heart: :yellow_heart:
