### ISSUE TITLE
Trigger stuck

### ISSUE THREAD

**Issue by Hexagon-Vienna** [thestonefox/SteamVR_Unity_Toolkit#142]
Has anyone the same issue?

When I press the trigger... is stays triggered.
At least when I am using the Steam VR_ControllerEvents from your Toolkit.

Kind of a problem, cause sometimes things get triggered just pointing at them without even touching the trigger. I recognized it by implementing my Menu. Sometimes when touching and realising the trigger before pointing at the object and then just sweep over the object it gets activated... Is that normal? Shouldn't be I guess :(

**Comment by thestonefox** [comment]
What version of the toolkit are you using?

There was an issue with the triggerPressed bool not unchecking after releasing the trigger. but this has been fixed since the bow and arrow mechanics were introduced.

**Comment by Hexagon-Vienna** [comment]
ahhhh k. That's my problem then... what else... updates :)
Actually I was collecting all the stuff I added and changed to the scripts
to be prepared for a new version of Toolkit and Steam VR. So I will update
the version later on. Mine is at least 2 weeks old.

I am having issues with the ApplicationButton
as well. But will update first and come back if nothing changed!

Thank you!

**Comment by thestonefox** [comment]
This is the commit with the fix:
08a2cc0c24c830f00c5150f170c34492ad12ce4f

Look at the controller_events changes, you may be able to just lift them into your own script to save the hassle of merging updates :)

**Comment by Hexagon-Vienna** [comment]
JUP... that helped!
Fixed it. Thx.

But my simulation is a bloody mess anyhow, have to clean it sooner or later. My scripts are... well chaotic... I am a messy coder and a bad too :) But for now the minor changes helped, so I can finally have some lunch without a feeling of failure ;)

**Comment by thestonefox** [comment]
Glad it worked :)
