### ISSUE TITLE
Use better colliders for controllers

### ISSUE THREAD

**Issue by 10FingerArmy** [thestonefox/SteamVR_Unity_Toolkit#143]
While the sphere controller is convenient initially it is very inaccurate when it comes to interactions with controls like buttons, sliders etc. Also moving objects around has weird side effects since the sphere shape causes unexpected physics.

We should really use a collider fitting to the controller which reacts then much more natural to the environment. NewtonVR shows that very nicely.

**Comment by thestonefox** [comment]
Do they use a mesh collider?

**Comment by 10FingerArmy** [comment]
It very much feels like it but these are several box colliders generated at
startup approximating it quite nicely. I have the feeling job simulator
actually uses the mesh as it is really precise.

**Comment by thestonefox** [comment]
Could do the same and create a collection of boxes. Wouldn't be too much of a big deal.

**Comment by 10FingerArmy** [comment]
Would be great, the bounding sphere is way too big especially right under the tip. My work-in-progress-button currently is pressed very magically ;-)

**Comment by thestonefox** [comment]
Completed in 2da56bd91c0b54a4122169867988128816c758f3

The rigidbody colliders are now a collection of boxes that are closer to the shape of the controller.

I've also moved the code responsible for creating the ridigbody (and toggling it on or off) to the Interact Touch script.

Meaning, the grab buttons aren't necessary now to toggle the rigidbody state (they still can toggle it though).

This means you'd be able to have a trigger collider on an object that could intercept the controller touching the trigger and have the public method to toggle the rigidbody called on the Interact Touch script.
