### ISSUE TITLE
Renaming struct and events

### ISSUE THREAD

**Issue by Tenebrous** [thestonefox/SteamVR_Unity_Toolkit#145]
Suggest the struct & events are renamed to be clearer and match the usage better.

For example, "Clicked" usually refers to the combined actions of pressing down and releasing, but here we're using it to mean down only.

Examples:
ControllerClickedEventArgs -> ControllerEventArgs
TriggerClicked -> TriggerDown
TriggerUnclicked -> TriggerUp
TouchpadClicked -> TouchpadDown
TouchpadUnclicked -> TouchpadUp
TouchpadTouched -> TouchpadTouchBegin
TouchpadUntouched -> TouchpadTouchEnd

The touchpad 'touch' events could tie in with Unity's existing Touch Phases: https://docs.unity3d.com/ScriptReference/TouchPhase.html

**Comment by thestonefox** [comment]
Yeah makes sense :+1:

**Comment by thestonefox** [comment]
I think ControllerEventArgs is already used by the SteamVR Unity plugin

**Comment by Tenebrous** [comment]
Possibly, although I think we can agree that having 'Clicked' in the name
is wrong :)

**Comment by thestonefox** [comment]
Yeah I agree Clicked is wrong. Just need something that doesn't clash :)

**Comment by Tenebrous** [comment]
I suggest a VRTK prefix, then I think we're clear.

**Comment by thestonefox** [comment]
it's probably worth prefixing all the toolkit events with VRTK for consistency as well

**Comment by 10FingerArmy** [comment]
in a more general sense, isn't this also what namespaces provide?

**Comment by Tenebrous** [comment]
Yes, good point, I keep forgetting about those :)

**Comment by thestonefox** [comment]
It's probably worth adding namespaces to all of the Toolkit classes, it's too similar to the global nature of SteamVR at the moment.

**Comment by Tenebrous** [comment]
Agreed, and then the naming within the namespace doesn't matter at all.

**Comment by thestonefox** [comment]
I think it's worth holding off on this kind of refactor until all relevant pull requests are merged, otherwise people are going to have a conflict battle on their hands :p

**Comment by thestonefox** [comment]
Trello card https://trello.com/c/pcNWc10m

**Comment by thestonefox** [comment]
I'm going for "<button-name>Pressed" and "<button-name>Released" (instead of clicked/unclicked)

Up/Down felt a bit confusing when talking about touchpad because is TouchpadDown a press or a touch?

So I've gone with TouchpadPressed/ TouchpadReleased for clicking and TouchpadTouchStart/ TouchpadTouchEnd for touching

**Comment by Tenebrous** [comment]
Pressed/Released work perfectly I think, good choice!

**Comment by thestonefox** [comment]
PR up with these changes in, feel free to review:
https://github.com/thestonefox/SteamVR_Unity_Toolkit/pull/157

**Comment by thestonefox** [comment]
Completed with d718ef24db6575c08ae36a5076fdfab56acfaf32
