### ISSUE TITLE
Provide a push button interaction

### ISSUE THREAD

**Issue by 10FingerArmy** [thestonefox/SteamVR_Unity_Toolkit#146]
**Control description**
A gameobject that can be touched physically correct with the controller, moving it gradually down until a certain distance is reached, setting it to a pushed state. When moving the controller away it springs back into it's original position removing the pushed state.

**Approach**
I am a bit torn here. I think the way to go is:

- create a two part button: frame and button, since there must be free space under the button in order to let it move, all the rest could potentially be setup by a script
- add a rigidbody with no gravity to the gameobject
- constrain it to only one axis, e.g. y
- expose a variable for push distance to reach until triggered (somehow optional, we could also say it reaches the bottom of the free space, but that might be difficult to get right)
- the controller (with activated rigidbody) is now able to move the button down

So far so good. Several things to think about:

How does the button come back up again? 

- Option 1: we add a spring joint mimicing actual keyboard buttons, my experiments have quite some unreliable behaviour using a spring joint but that might be initial trouble only
- Option 2: add a constant force from the bottom pushing up the button that stops once it reaches the original state. I think this actually the easier way.

How do we get the controller to interact?

- Option 1: push the grab key to enable the rigid body, works but feels very unnatural since it somehow implies "you have to activate your hand"
- Option 2: establish an interaction paradigm with the rigidbody controller always on, that is actually my favorite, see Job Simulator, but it has some side effects when grabbing.
- Option 3: we activate the rigidbody controller when close to a button only
- Option 4: we deactivate the rigidbody controller when close to a grabbable object, that might be the best of both worlds (and I think that is what job simulator actually does as levers or donuts can be freely grabbed for example without collision)

Please provide feedback and ideas :-)

**Comment by thestonefox** [comment]
I think the concept that items would "activate" the controller rigidbody when it passes through a collider trigger would work.

In Job Simulator, not all items are collidable with the controller, so they must be doing something similar to this I would guess.

**Comment by 10FingerArmy** [comment]
I have a first version. Just wanted to share how it currently feels. As long as we use a sphere collider the distance is quite a bit off. We will have to sort that out in a separate change. Will cleanup the script now and make a first PR to get feedback.

http://imgur.com/M0kcoGo

**Comment by thestonefox** [comment]
Looks really nice.

I'll see if I can get some time later to sort out the colliders. I wanted to work on some issues today but I've been wasting my day trying to figure out why Steamworks won't take my latest game build...Turns out the steam servers are down in places and no one at Valve bothers to let anyone know it may affect their game publishing! grr

**Comment by 10FingerArmy** [comment]
Here we go: https://github.com/thestonefox/SteamVR_Unity_Toolkit/pull/151

**Comment by thestonefox** [comment]
Other opinions and views welcome and required on this thread:
https://github.com/thestonefox/SteamVR_Unity_Toolkit/pull/151

**Comment by thestonefox** [comment]
Completed with https://github.com/thestonefox/SteamVR_Unity_Toolkit/pull/151
