### ISSUE TITLE
Best Practice: Create a GameObject at Controller position

### ISSUE THREAD

**Issue by IARI** [thestonefox/SteamVR_Unity_Toolkit#147]
My Goal is simple: When the trigger is pulled, a GameObject should be instanciated at the position of the rsp. controller.

My approach is to connect to the TriggerClicked event, but from there I only get the ClickedEventArgs.
How do I get the Controller positions (i.e. SteamVR_TrackedObjects) that belong to the event?

I could find SteamVR_TrackedObjects on Start, then GetComponent<VRTK_ControllerEvents> to hook up to the events and then memorize a mapping from controllerindex to SteamVR_TrackedObject - but that seems super wrong.

Being completely new to Unity, probably I'm being stupid here - can someone help me out?

**Comment by thestonefox** [comment]
Take a look at the Archery scripts, the arrow spawner does something similar to what you're requesting

**Comment by thestonefox** [comment]
This is really solved by this:

https://github.com/thestonefox/SteamVR_Unity_Toolkit/issues/139
