### ISSUE TITLE
Gaze functionality

### ISSUE THREAD

**Issue by RoccoGD** [thestonefox/SteamVR_Unity_Toolkit#152]
Would be nice to have the base scripts for Gaze triggered actions included in the Toolkit.

To use Gazepointer for triggering UI Events is obvious, but also for direct Gameplayactions, to trigger events as you can see in the Lab - Secret Room Demo, when you look on certain entities.

**Comment by thestonefox** [comment]
I wonder if it's worth recreating their gaze pointer so it's more compatible with the events that are used by other things in the toolkit.

The gaze is just a raycast from the headset, so it's not that dissimilar to the simple pointer. It could maybe even extend the destination events (when I separate them out of the world pointer)

**Comment by RoccoGD** [comment]
Yes, maybe an extention to the simple pointer would be fine. 
(I don't know but some experiences have this functionality and work for all headsets, so maybe someone could develop experiences with the gaze functionality very easy for multiple devices.)

**Comment by bcoyle** [comment]
I like this idea. Sometimes I'll have a friend in a demo and need to help them with movement. If I hold the controller I can just ask them to look at something and then pull the trigger for them.

**Comment by thestonefox** [comment]
I'm just about to do a PR that basically lets you stick a Pointer script onto the Camera (head) which would give you gaze functionality along with all of the abilities of the pointer

**Comment by thestonefox** [comment]
PR for gaze functionality:
https://github.com/thestonefox/SteamVR_Unity_Toolkit/pull/219

I'll add an example scene too
