### ISSUE TITLE
Haptic feedback duration in frames of feedback

### ISSUE THREAD

**Issue by drifio** [thestonefox/SteamVR_Unity_Toolkit#159]
**https://github.com/thestonefox/SteamVR_Unity_Toolkit/blob/1bade6d169634ae4a1074d1ad660083735c4fc34/Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_ControllerActions.cs#L58**

Whilst I appreciate that VR should run at 90fps constantly, framerates can and do fluctuate. Would it not make more sense to have the 'duration' of a haptic feedback event be in a fixed timescale rather than number of frames?

**Comment by thestonefox** [comment]
Lol N00b coding

Should be using Time.deltaTime :)

**Comment by drifio** [comment]
Looking into it a bit deeper, hapticPulseStrength is the duration in microseconds that the controller will vibrate for within the SteamVR toolkit, in which case the time between calls to that method will have a measurable effect on the 'strength' of the pulse. Ideally we need to call it at as specific a time interval as possible from what I can tell. Maybe a coroutine is the best way to go?

**Comment by thestonefox** [comment]
Don't read the docs, try it out in SteamVR

it doesn't actually seem to be duration, it seems to be strength.

The larger the number in SteamVr the more intensity to the vibration (over a single tick)

The docs seem wrong (to me)

**Comment by drifio** [comment]
Ah, ok then. I'll mess about with it this evening and see if I can find a solution that feels consistent across multiple framerates.

**Comment by thestonefox** [comment]
i think Time.deltaTime should be the approach.

But I'd love to get to the bottom of how SteamVR Haptic Feedback is supposed to work

**Comment by thestonefox** [comment]
Completed with https://github.com/thestonefox/SteamVR_Unity_Toolkit/pull/193
