### ISSUE TITLE
[Teleporter] - Allow teleporting over terrains and mesh colliders

### ISSUE THREAD

**Issue by thestonefox** [thestonefox/SteamVR_Unity_Toolkit#16]
At the moment a terrain or mesh collider won't work wth the Height Adjust teleporter. Need these to be supported too.

**Comment by thestonefox** [comment]
Terrain colliders are now supported in eed0829ad47ffbb3a2ca4619c116911ba36b6cb2

Mesh colliders have not been looked at yet. They will probably be looked at later down the line.

**Comment by thestonefox** [comment]
I've had reports that mesh colliders also work :)

I will investigate myself before closing this ticket

**Comment by thestonefox** [comment]
It seems mesh colliders still don't work. I'll investigate more in the future

**Comment by thestonefox** [comment]
Completed with ad0f27450efa6bfb1f591f2628fe8f31920f4f72

**Comment by RoccoGD** [comment]
Wohoo, Thank you very much!

**Comment by thestonefox** [comment]
Hopefully it works as you require :)

**Comment by RoccoGD** [comment]
A bit late but no time last days, today i tested it and its working absolutely perfect with the elevation, t have tested a complicated mesh -> <a href="http://www.fotos-hochladen.net/view/unity2016051sju942xdh1.jpg" target="_blank"><img src="http://www.fotos-hochladen.net/thumbnail/unity2016051sju942xdh1_thumb.jpg" border="0"></a>

Thank you very much!!

**Comment by thestonefox** [comment]
Awesome, glad it's working!
