### ISSUE TITLE
Laser Pointer as a Marker_help wanted

### ISSUE THREAD

**Issue by Jihosong** [thestonefox/SteamVR_Unity_Toolkit#160]
Hi, Fox and generous developers here. I am an architecture student at GSD, Harvard, trying to learn Unity for architecture in VR as a design tool. I am using your toolkit. It is just incredibly helpful. I really appreciate it. 

I got your laser pointer and it works perfect. What I want to do for the next step is to make the pointer as a marker so that my professors can see a building I designed and give me a feedback by checking architectural elements in my building.

This thing is big here among students, but professors tend to look at VR as a mere architectural visualization tool or even a gimmick. If there is any genius here who can help me realize some features like this, we can expand the boundary beyond a game.  

Breif: 
Making a tip where the pointer collides with an object draws something on the object. 

Is this possible?? Please let me know. Thanks!

**Comment by thestonefox** [comment]
Hey,

Check out this video (and example)

https://www.youtube.com/watch?v=NhmGAbj5Hvo&list=PLRM1b2lKjTbdFJtYv_SNAb3NvYp-Gl7nZ&index=20

It probably does what you're after :)

**Comment by Jihosong** [comment]
Thanks! I will check out the video and probably ask some questions to you... Thank you so much, Fox!

**Comment by Jihosong** [comment]
Hey,  I checked all the other videos and decided to try a grab feature first so that I can move some columns around in my building. I started with a simple cube. I used the scripts exactly the way you used in the video for both the controller and an object. The problem I have is that a cube is not moving even though it's highlighted when touched... Do you have any idea?

**Comment by thestonefox** [comment]
Are you using the CameraRig prefab from the SteamVR Unity Plugin?

If so then that is the problem. You need to use the CameraRig from the Toolkit Prefabs folder instead.
