### ISSUE TITLE
Errors on Basic Teleport Script

### ISSUE THREAD

**Issue by Locxion** [thestonefox/SteamVR_Unity_Toolkit#161]
Hey Guys o/
I found StoneFox's Youtube Videos some Hours Ago and want to try the Toolkit out.
But if i want to Test the Teleport Scene Visual Studio gives me 2 Errors in the VRTL_BasicTeleport.cs

`'float' does not contain a definition for 'Start' and no extension method 'Start' accepting a first argument of type 'float' could be found (are you missing a using directive or an assembly reference?)	at 67 and 123`

and

`The name 'Valve' does not exist in the current context	at 304
`
The "Valve" Error appears in the VRTK_ControllerEvents.cs too at 304?

so What the hell did i wrong?
I Use the Stable Unity 5.3.5 and i imported the SteamVr from the Asset Store?
Help?
greez
Locxion

**Comment by thestonefox** [comment]
Hey,

I would recommend re downloading, the toolkit and opening in a fresh Unity project, then re-importing the SteamVR Unity plugin again from the Asset store, the error you're getting is to do with the SteamVR Unity Asset store plugin not being found.

**Comment by Locxion** [comment]
Hell yes ... i did what you mentioned 3 times ... and now i did it again ... it works ... DAMMIT!
So another Question ... What is the difference between the Rig from the SteamVR Asset and Yours?
In another post there was a problem that the SteamVr Rig doesnt work verry well with the Toolbox?

**Comment by thestonefox** [comment]
The SteamVR CameraRig Prefab is missing a number of children items within the model within the editor. It generates them at runtime.

However, in the SteamVR test throw scene they have a different CameraRig which has these child elements on the model within the editor, which is required to specific the rigidbody grab point.

The prefab included in this toolkit is the CameraRig from the test throw scene. I'd recommend using the one from within this toolkit.
