### ISSUE TITLE
Custom Controller

### ISSUE THREAD

**Issue by juanbarambones** [thestonefox/SteamVR_Unity_Toolkit#164]
Hi Fox and other developers here. Sure there are many junior developers like me, trying to change in the examples Steam Controller for one custom (hand for example). Some instruction here could be helpful. Thanks for the toolkit, It is incredibly helpful !!

**Comment by thestonefox** [comment]
Related to https://github.com/thestonefox/SteamVR_Unity_Toolkit/issues/4

I can look to add an example scene it it helps.

**Comment by juanbarambones** [comment]
That would be great. Thanks.

**Comment by thestonefox** [comment]
early PR to show adding custom controller models:

https://github.com/thestonefox/SteamVR_Unity_Toolkit/pull/226

**Comment by thestonefox** [comment]
Completed with https://github.com/thestonefox/SteamVR_Unity_Toolkit/commit/29e088034bd8e59a0d669a4bc924e7442af9382d
