### ISSUE TITLE
SteamVR_InteractGrab fails to get the tip of the controller on Start

### ISSUE THREAD

**Issue by BenWoodford** [thestonefox/SteamVR_Unity_Toolkit#17]
I assume it's running too early and the models haven't been built yet, but SteamVR_InteractGrab's Start() method tries to get the "tip" GameObject before it exists, which in turn prevents the grabbing events from binding to AliasGrabOn/Off.

EDIT: Just realised it's because I'm not using the bundled prefab. Oops. Might be worth having it add the RigidBody on the fly as not every controller will use this structure.

**Comment by thestonefox** [comment]
The bundled prefab has the additional children on the Controller that are required (like the tip, etc).

The prefab that comes in the SteamVR plugin seems to be missing all these children (except for the version of the prefab in the Test Throw scene...no idea why!).

Basically, the prefab in my project is just the one from the SteamVR Test Throw scene.

If you use the default prefab then it has no child objects on it to even add a rigidbody to. (I think they are generated at runtime, but it's too late by then)
