### ISSUE TITLE
SnapToPosition and SnapToRotation

### ISSUE THREAD

**Issue by jakk2809** [thestonefox/SteamVR_Unity_Toolkit#171]
I'm not sure if this is a bug or not, but I noticed something weird with snapToPosition and snapToRotation. In VRTK_InteractGrab, line 134 is using global position, but I thought snapToPosition was local to the controller. When I grab the object with an offset, it keeps changing relative to the controller. A possible fix could be:

`obj.transform.position = controllerAttachPoint.transform.position + controllerAttachPoint.transform.TransformVector(obj.GetComponent<VRTK_InteractableObject>().snapToPosition);`

Also, for rotation snap, I noticed that on some large objects it seems to "glitch" to a flat position and then snap to the controller. Perhaps something like this could fix it:

`obj.transform.rotation = controllerAttachPoint.transform.rotation * Quaternion.Euler (obj.GetComponent<VRTK_InteractableObject> ().snapToRotation);`

One last small thing. In VRTK_InteractableObject, may I suggest that the snapToPosition be placed before snapToRotation. Usually in Unity position comes before rotation in the transform and being backwards trips me up sometimes.

Let me know what you think. Thanks.

**Comment by thestonefox** [comment]
I wonder if snapToPostion and snapToRotation should be deprecated and eventually removed, the handleSnap concept works well, where you put in a child transform to your object with the rotation and position you want it to snap to.

**Comment by jakk2809** [comment]
The handle would work but it would be up to the user to setup the handle transform externally. I usually make an empty object as a child of the controller if I want a different attach point other than the tip or default controller transform.

**Comment by thestonefox** [comment]
This has been changed in a PR https://github.com/thestonefox/SteamVR_Unity_Toolkit/pull/202
