### ISSUE TITLE
Custom Edge of Chaperone Events

### ISSUE THREAD

**Issue by xEvoGx** [thestonefox/SteamVR_Unity_Toolkit#173]
This might be up there with _already available_ or _easy to implement yourself_, but then again maybe not?

I was looking for an easy way to detect when either the HMD or a controller is near the boundaries of the Chaperone, and up on that call an event (outside of the Chaperone grid simply appearing). 

I was going through the **Steam VR** code but couldn't find anything that pertains to this, so now I'm wondering if I'm blind or maybe the Chaperone stuff is black-boxed? (I don't see why that would be the case, so I'm going with blind if nothing else) lol.

Cheers

-Steven

**Comment by sdouglas** [comment]
Hi Steven - I'd be interested to know what application you have in mind because I was working on something similar this morning.

One simple thing you can do is use the locations of the camera and playarea to get a rough idea of where the player is standing. For example, I used this information to modify `VRTK_WorldPointer.SetPlayAreaCursorTransform` to center the pointer on where the player is standing and offset the room bounds so you have a better idea where they will end up.

```
playArea = GameObject.FindObjectOfType<SteamVR_PlayArea>();
hmdCamera = GameObject.FindObjectOfType<SteamVR_Camera>();
Vector3 roomPos = new Vector3(playArea.transform.position.x, 0, playArea.transform.position.z);
Vector3 hmdPos = new Vector3(hmdCamera.transform.position.x, 0, cam.transform.position.z);
Vector3 offset = roomPos - hmdPos;

playAreaCursor.transform.position = destination + offset;
```

I think this is similar to the hinting provided in The Lab's teleport function, but they also include a circle to make it even more obvious where the player is standing:

![teleport](https://cloud.githubusercontent.com/assets/45583/16059229/f8c389f0-3236-11e6-9d79-ebe33876ca8d.jpg)

**Comment by xEvoGx** [comment]
Ah Shawn I was thinking the exact same thing, though with Teleport, as Stone added that bit to restrict a teleport by play area collision! 

Your solution is elegant and exactly what I was looking for...

...as for _use_, I'm not entirely certain yet. It dawned on me that I may want to know when the HMD or controllers were near the Chaperone edge, and do something with that information. Something perhaps as subtle as vibrating the controller so having a blue boundary floating around you isn't necessary (I still think it is). Obviously we're speaking about the edges of safe play, so there may not be a ton that can be done, unless you have ideas?

I really appreciate the response Shawn thank you!

-Steven

**Comment by xEvoGx** [comment]
Okay! Works as it should, and it's neat to hold the pointer (with play area visible) and walk around and see the pointer update _your_ position relative to the play area...

...but I realize that while the offset is a neat idea, it doesn't know I'm near the _boundary_, so I still need that info, hmmm.

**Comment by sdouglas** [comment]
When I first installed everything I tried to make the play area as big as possible, and that did make it easy to occasionally whack stuff in the room with the controllers. One option is to rerun SteamVR room setup and specify a smaller play area to keep everything further out of reach. 

I do like the idea of a secondary warning. With some minor changes you can calculate whether a point is within some distance of one of the four boundaries. I suggest looking at `InitPlayAreaCursor` to get an idea of how the boundaries are drawn based on `playArea.transform.localScale`. You can probably define your own 'safe zone' min and max values for x and z (essentially another box centered inside the play area), and then trigger an event whenever the controller position exceeds those values. You could check the y as well if you have low ceilings. :)

**Comment by thestonefox** [comment]
@sdouglas That's a good addition, would you raise a pull request with your addition?

**Comment by sdouglas** [comment]
Yes will do!

**Comment by xEvoGx** [comment]
Hopefully you don't forget about the initial intent of this issue! :)

**Comment by sdouglas** [comment]
@xEvoGx did you have any luck with manually calculating proximity to boundaries based on the playArea transform?

**Comment by xEvoGx** [comment]
Not yet, though as you may be feeling too, there's so much to learn and play with in VR, getting sidetracked is effortless! :smiley: 

I guess all I'd have to do is get the boundary for X and Y separately, divide that in half and simply check for the controller/HMD vs both X and Y. Sounds right?

**Comment by thestonefox** [comment]
ok if i close this? seems stale. happy to reopen if required
