### ISSUE TITLE
Commenting Scripts from Git Description

### ISSUE THREAD

**Issue by xEvoGx** [thestonefox/SteamVR_Unity_Toolkit#176]
This is minor, but I'm a huge proponent of commenting in code, so it may be convenient to just have the description for each script that's already here on Git, commented in the respective script. :)

Thanks Stone

**Comment by thestonefox** [comment]
I did start doing that, but then it's just a ballache to keep the documentation up in 2 places (3 places included the [out of date] wiki)

**Comment by xEvoGx** [comment]
Lol _ballache_...

...and also 

**// 
{Cut and Paste} 
//** 

Ctrl + S? 

Cheers Stone!

-Steven

**Comment by thestonefox** [comment]
Feel free to make a pr ;) :p

**Comment by xEvoGx** [comment]
HA! I knew that was coming...

...I suppose I could **learn2git** but we'd ALL be risking a lot potentially.

O.o

Guess it can't hurt but no promises!
