### ISSUE TITLE
What is Play Space Falling?  It causes jumpiness when head moves up and down

### ISSUE THREAD

**Issue by sgehrman** [thestonefox/SteamVR_Unity_Toolkit#178]
I was wondering why my scene was shifting up and down and noticed it was from Update inside the Height Adjust Teleport.  Default to false or figure out how to fix it.  In your demo, teleport on a cube and move head down near the floor to see it jump around.

**Comment by thestonefox** [comment]
Not sure what problem you're explaining.

I also don't have my headset at the moment as it's being repaired so I can't look into this at present

**Comment by drifio** [comment]
Play space falling is an optional feature that allows you to "fall" off of objects if your hmd transform moves over an edge. If you don't want to use it, toggle it off.

**Comment by thestonefox** [comment]
@drifio is @sgehrman reporting a bug with it though? I'm not entirely sure if he's just describing the expected behaviour or has found a glitch

**Comment by drifio** [comment]
Hm, the description sounds to me like it's operating as intended. I'll fudge about with it when I get home and see if I can reproduce any issues. Care to be more specific @sgehrman ?

**Comment by sgehrman** [comment]
It's not operating as intended.  If I move my head around in my scene, the whole scene seems to jump around randomly up and down, it's a serious bug.  I just disabled that feature.

**Comment by thestonefox** [comment]
If it's broken then lets leave the ticket open until someone can look into it

**Comment by thestonefox** [comment]
I've tested this and it seems to be working as intended.
