### ISSUE TITLE
Wondering why you rename game objects

### ISSUE THREAD

**Issue by sgehrman** [thestonefox/SteamVR_Unity_Toolkit#179]
I see things getting renamed with PlayerObject_ or whatever.  just wondering why. It's kind of confusing.

**Comment by thestonefox** [comment]
The items are renamed so other scripts can identify player related game objects. Tagging objects is too limiting as only 1 tag is allowed per object.

**Comment by sgehrman** [comment]
I would have probably built a singleton that keeps track of objects.  As objects are created they register themselves? I'm not a c# expert, I just don't like the concept of renaming and relying on names.
