### ISSUE TITLE
Physically ignore targets with teleporter

### ISSUE THREAD

**Issue by exemef** [thestonefox/SteamVR_Unity_Toolkit#180]
I have Sphere colliders set as triggers to activate events and would like to be able to ignore them but be able to teleport through them and the ground beneath. Using the HeightAdjustTeleport script will put me on top of the collider and if I use the basic teleport script the pointer still reacts to the collider as I pass over it which makes it hard to teleport to the center area of the collider. I imagine modifying the ignore targets function to pointer to allow teleportation but ignore height instead and adding the same ignore target function to the pointer script but allow teleportation.

**Comment by thestonefox** [comment]
Try putting your sphere colliders on the ignore ray cast layer. Then the pointers shouldn't interact with it

**Comment by exemef** [comment]
Wow, this works, thank you so much for the scripts, examples, videos and fast response! I hope you get you Vive in working order again soon!
