### ISSUE TITLE
HeightAdjustTeleport occasionally drops player below [terrain] mesh collider.

### ISSUE THREAD

**Issue by Arfenhaus** [thestonefox/SteamVR_Unity_Toolkit#183]
First off, thanks for the fantastic toolkit! I wouldn't be close to where I am without it. 

So I've built a fairly complex terrain using the Unity Terrain creator, lots of valleys and peaks. 95% of the time, the height adjust teleport works beautifully and I can get across the map with ease. However, 5% of the time, the player teleports completely through the terrain and ends up falling into the Unity abyss. I can catch a teleport back up quickly enough without having to exit out completely, but for novices and those prone to motion sickness, it's not ideal and not presentable. I can't playtest for my roommate because he nopes out the instant he teleports under and starts falling.

Have you run into this issue elsewhere, and if so, have you been able to find a solution? I have not edited the HeightAdjust script, and it is the latest version.

**Comment by thestonefox** [comment]
Do you have the Player_Presence script added as well?

The teleporters won't ever make you actually freefall, they just send down a raycast from the headset to the nearest floor (this is the player falling parameter). If the raycast doesn't hit a valid collider then it just wouldn't teleport you.

So the only way I can think you're falling into the abyss is the Player_Presence script adds a rigid body to the player and if you move onto a piece of your terrain where the terrain collider is too thin or non-existent would mean your CameraRig would then freefall.

Test the areas of your terrain where you're falling by dropping other objects at that point and see if they fall through.

I don't have my headset at the moment because it's off for repairs, but when I get it back I can take a further look

**Comment by Arfenhaus** [comment]
I do have the Player_Presence script added, and it does create the rigidbody at runtime correctly. 

The biggest culprits in the terrain are places where there is a steep degree (and I imagine the deformation has stretched the terrain thin), and places where meshes collide (like where I have rocks sunken into the ground). What's the most strange though is that it's not even a reliable measure. Sometimes I'll teleport on flat or barely curved terrain with no other game objects and it still will occasionally drop me through unannounced. As if the terrain can't keep up with the teleport, or the SimplePointer is clipping through the ground (even though the raycast should compensate).

Unity noob, so forgive my supposition, but would it be possible to add a statement that says if the player is freefalling with no collider under them (or the raycast returns something something null), it shoots a raycast straight up to find the nearest collider and teleports on top of it? I might jump in and try and hack that together myself to see if it works but I imagine you would know for certain if it's a viable solution.

**Comment by Arfenhaus** [comment]
From reading around it also seems that moving too fast can also cause issues with larger colliders sometimes failing to actually collide. What about an option to slow down the teleport speed or ease into the end position more slowly? If it's an instant translation I don't see how it would have speed in the first place, otherwise this might be a factor.

**Comment by thestonefox** [comment]
The player presence adds a rigid body that will pull the camera rig down with gravity. It's nothing to do with teleporting.

The issue you're referring to is called collision tunneling and you can reduce it by turning on continuous collision detection on your rigid bodies.

**Comment by Arfenhaus** [comment]
Of course, but in the teleport script would it be prudent to add something like that in this case?

I've tried adjusting the collision detection, both by adding a separate rigidbody and enabling continuous detection, and by adjusting the rigidbody created by the Player_Presence script to have that collision mode. Neither seems to solve or mitigate the issue at hand.

**Comment by thestonefox** [comment]
It's got no relevance to the teleporter if a rigid body is not colliding. The teleporter just updates your y position it doesn't do it with physics.

Try removing the player presence script and see if that solves the free fall issue.

**Comment by Arfenhaus** [comment]
Well I was referring to the raycast up script, not the slow teleport option, sorry about that.

I removed the script, it fixes the freefalling, though I am still able to sometimes teleport beneath the terrain and now I am also able to teleport into the air in a fixed position without falling (obviously because the player now has no physics).

**Comment by thestonefox** [comment]
See if you can log out the destination position before you teleport, sounds like the pointer is cutting through the terrain I wonder if the terrain collider is offset or something

**Comment by Arfenhaus** [comment]
Updated in Simple_Pointer:

            if (hasRayHit)
            {
                pointerContactDistance = collidedWith.distance;
                pointerContactTarget = collidedWith.transform;
                destinationPosition = pointerTip.transform.position;
                UpdatePointerMaterial(pointerHitColor);

                base.PointerIn();
                Debug.Log(destinationPosition.y);
            }


And HeightAdjustTeleport:

        private float GetTeleportY(Transform target, Vector3 tipPosition)
        {
            float newY = this.transform.position.y;
            //Check to see if the tip is on top of an object
            if (target && (tipPosition.y + 0.5f) > (target.position.y + (target.localScale.y / 2)))
            {
                newY = tipPosition.y;
                Debug.Log(newY);
            } 


What I end up seeing is zero discrepancy between both values when the player is teleporting in relatively flat or evenly bumpy terrain. Only occasional discrepancy when going up a high incline. Where it does become an issue when clipping into certain border terrain assets that I fall through regularly. I can easily recreate the dropping through issue by using them, however it still occurs randomly in regular flat terrain, but again with zero discrepancy in the values logged between the pointer end position Y and the final player position Y.

**Comment by Arfenhaus** [comment]
More clues...It seems I can successfully recreate this by clipping through any geometry that itself is clipped through the terrain (i.e. a rock that is placed IN the geometry to simulate a natural setup). It seems once the player object clips through, it ignores all colliders and falls straight down. All objects in my scene have colliders, whether mesh or otherwise, and setting them as convex does nothing to prevent this from occurring.

**Comment by Arfenhaus** [comment]
Also seems that terrain surfaces that are almost vertical also recreate the issue regularly.

**Comment by thestonefox** [comment]
Ok when I get my headset working again I'll take a look at recreating the issue

**Comment by Arfenhaus** [comment]
I'm finding the most success in recreating the issue where there are hard breaks in the terrain. For instance, at the crest of a hill or anywhere quads are at extreme angles. If I aim the teleport pointer right above the break, especially from the bottom of the hill, it happens every time. Debugging doesn't point to any Y weirdness. Just fyi, for when you get your headset back. Thanks again!

**Comment by thestonefox** [comment]
Be great to have an example project showing the issue.

Maybe someone else could take a look then while i'm waiting for my headset to be back to it's full glory.

**Comment by thestonefox** [comment]
I've attempted to replicate this, but I cannot seem to recreate the issue.

If you could provide an example scene or a video demonstrating the issue then I can look into it further.

**Comment by Arfenhaus** [comment]
The issue ended up being the terrain thickness, increasing the thickness beyond a level that the Simple Pointer could penetrate solved the issue for me.

On a separate note, Bezier Pointer shows but no longer teleports.

**Comment by thestonefox** [comment]
So would you say that the solution then is regarded to terrain thickness?

May be worth raising another issue about the bezier pointer so to not clutter this issue up.

**Comment by Arfenhaus** [comment]
That's my best guess, since I changed that I've had zero issues with HeightAdjustTeleport.

**Comment by Nova66** [comment]
I continue to have the same problem with the HeightAdjustTeleport script. Whenever I try to teleport up a ramp and the landing point is higher than my head, I end up teleporting to the new X,Z position but at the old Y level which means that I end up underground. This only happens in the uphill direction, never downhill or on the flat.

Arfenhaus made the point that he found a fix by increasing the terrain thickness. Where is this setting? My collision mesh is imported geometry from my CAD software and is a simplified version of the ground and surrounding buildings. I'm pretty sure that it's a clean mesh with no holes or anomalies.

This has been a long standing problem for me and I'd love to find a solution.

Thanks.

**Comment by thestonefox** [comment]
If someone could provide me with a clean example scene showing how to recreate the issue then I can take a look into it further.

**Comment by Nova66** [comment]
It's evening here now but I'll create a simple project and send you a download link tomorrow.

Thanks.

**Comment by Arfenhaus** [comment]
Hey Nova, if you click on your Terrain, look in the Inspector, click the Settings gear icon, Thickness should be the last option under "Base Terrain". I have that set at 20 and have had zero teleporting problems since.

**Comment by Nova66** [comment]
Thanks for the instructions Arfenhaus but I see now that your workflow refers to the "Terrain" object type within Unity. My collision mesh is a simple mesh that I've imported from my CAD software, it doesn't have any of those settings that you talk about.

I've managed to create a simple project for thestonefox to look at that shows the problem with the teleporter. Just teleport as far up the hill that you can and you'll find yourself underground.

The download link is: [https://drive.google.com/file/d/0B2THCAxN5jlrM3FmZ0tuZ0tSLTA/view?usp=sharing](url)

Thanks.

**Comment by thestonefox** [comment]
@Nova66 I can replicate the issue in your demo scene, I'll take a look into a fix for it

**Comment by thestonefox** [comment]
@Nova66 check out this PR and see if it fixes your problem:

https://github.com/thestonefox/SteamVR_Unity_Toolkit/pull/257

If it does then I'll merge it into master as long as it passes other teleport tests.

**Comment by Nova66** [comment]
Hi @thestonefox

> check out this PR and see if it fixes your problem

I'm a noob when it comes to GitHub but I think your intent was for me to insert your code changes into my version of those two script files. I did that and no luck. I'm still seeing the same problem with that sample project I sent you a few days ago.

Do these changes work for you on that sample project? If so, then I've done something wrong at my end.

Sorry I can't be more helpful.

**Comment by thestonefox** [comment]
@Nova66 How have you built your mesh?

From what I can tell it seems that it's 0 y position is the top of the mesh object and it then goes into negatives.

The Mesh Teleporting example has an example rock mesh that has the mesh 0 y position at the bottom and then goes up.

So it would seem that if your mesh 0 y position is the bottom then it works, but putting it in a negative way means your pointer is always below your mesh in the world space.

**Comment by thestonefox** [comment]
@Nova66 I've had another attempt at rewriting the way the height adjust teleport works.

I think this new way makes more sense, it now uses a raycast from the pointer position to determine your destination Y location for teleporting to.

You can either download the PR code from the branch (https://github.com/thestonefox/SteamVR_Unity_Toolkit/archive/fix/mesh-teleporting.zip)

Or you can just take the code changes from the PR (like you did before)

https://github.com/thestonefox/SteamVR_Unity_Toolkit/pull/257/commits/a180e6a3310501395af482ec37d17b95ca40dd31


Let me know if this new method works for you.

**Comment by Nova66** [comment]
> Let me know if this new method works for you

Oh yes, this new method works perfectly :-)
It's amazing how good it feels not having to be careful of steep hills.

Thanks so much for taking care of this edge case for me.

**Comment by thestonefox** [comment]
Cool, I'll merge that change into master then :)

**Comment by thestonefox** [comment]
fixed with https://github.com/thestonefox/SteamVR_Unity_Toolkit/pull/257
