### ISSUE TITLE
Pre-defined teleport points?

### ISSUE THREAD

**Issue by paulcanning** [thestonefox/SteamVR_Unity_Toolkit#185]
Apologies if this isn't the bets place to ask questions.

I'm currently using the bezier pointer control to teleport players around my environment, which works fine, but I'd like to add a secondary mode of transport.

I'd like to set up a handful of pre-defined teleport points (like those in the mountain experience in the Steam Labs) so the player can (on the second controller) pull the trigger (doesn't have to necessarily aim at the point) and be teleported to point 1, then pull the trigger again to go to point 2 and so on.

Can anyone point me in the right direction? Perhaps with an example scene?

Thank you!

**Comment by thestonefox** [comment]
Take a look at the model village teleport. It can probably point you in the right direction

**Comment by paulcanning** [comment]
Hmm, is there any easy way to just attach the teleporting to the press of a trigger?

I'm really new to Unity, and I cannot wrap my head around this toolkit :/

I can see that the example is using collision(?) detection to initiate the teleport? What I'd like is to use the trigger on the left controller.

I made a script, and copied the trigger press method from the controller event example script.

But then I need to add in the destination teleport stuff. I cannot figure this out.

Also, I need the destinations to be in an array (I know I need a public array of transforms on my script for this, but beyond that, I'm lost).

Just wish I could understand how the different scripts talk to each other, and knew more about Unity scripting in general ha

**Comment by thestonefox** [comment]
You should join the slack channel (link in readme) quite a few helpful people that can help talk you through things :)

**Comment by paulcanning** [comment]
I can't find the link in the readme

**Comment by thestonefox** [comment]
https://vrtk-slack-invite.herokuapp.com

**Comment by thestonefox** [comment]
I think we fixed this in slack? :)
