### ISSUE TITLE
Pointer Issues after Building my scenes

### ISSUE THREAD

**Issue by Hexagon-Vienna** [thestonefox/SteamVR_Unity_Toolkit#186]
Hey there,

I've looked through the threads, couldn't find a similar problem:

I have 3 scenes, they all work fine. Starting Menu, Main Scene and End Menu.
When I test them in unity in Game mode I can go from one scene to the next one.
All settings are good nothing changed to the SceneMode.

As soon as I build the game and start the .exe, there are some things missing:

- the VRTK_SimplePointer script is NOT activated, or at least there is no more beam
- the steam play Area is NOT shown on the ground

I can't interact with the menu, therefore cannot start the simulation.
I build games before, with the exact same Menu and same settings and they woked fine!

My question: Is there such a major change between the former version of the Toolkit (the one without VRTK) and the actual one (the one with VRTK) that there are occuring building issues?
Did not find any specific ones so far.

I have steam VR plugin 1.1.0, the latest version from SteamVR_Unity_Toolkit (17.6.2016) and tried it with Unity 5.3.4 and Unity 5.3.5

I checked the Steam VR Plugin versions and the Unity Versions with my former build (the working one). That build also works with the newest versions of Unity (5.3.5) and Steam Vr Plugin (1.1.0)

So I think there must be an issue with the new scripts of the VRTK?
Anyone having similar problems? Ideas?

I keep on trying and maybe rebuild it with the older scripts and prefabs...

**Comment by thestonefox** [comment]
Have you tried following the instructions in the FAQ section as outlined in this video?

https://www.youtube.com/watch?v=IsmYoLTmX4c

**Comment by Hexagon-Vienna** [comment]
Ah shader... should have checked on that!

Yes that worked for the Pointer. Thank you.

Why did it work for your older version of the toolkit without going to
graphic settings? The play Area still causing problems in the newer build.
Will compare them more accurate and see if I find a solution.

Thanks again!

**Comment by thestonefox** [comment]
I'm guessing the old version didn't use the transparent shader.

The play area is displayed by the steam vr camera rig prefab. If you look at the parameters there's a check box to turn off displaying the boundaries

**Comment by Hexagon-Vienna** [comment]
yeah i know about the check box ...
it is not changing a thing, at least not for the
first and third scene.
Must be sth. on my side I am pretty sure ;)
Not necessary for the menu anyway. If it is sth.
in connection with versions or the toolkit I let u know!

**Comment by Hexagon-Vienna** [comment]
A Restart helped in the end for the Play Area.
Is it using the same shader as for the pointer?

Thanks for your help. Simulation is running smoothly!
