### ISSUE TITLE
"use" button stops working when grabbed object is hit

### ISSUE THREAD

**Issue by Roland09** [thestonefox/SteamVR_Unity_Toolkit#188]
I use the autograb feature. I have a sword with a hilt and a blade, the hilt is attached to the controller via autograb. You have to deflect incoming objects with the sword. It all works as long as the blade is hit. But once the hilt is hit by the incoming objects the "use" functionality doesn't work anymore.

**Comment by thestonefox** [comment]
what do you have as the use functionality? and do you mean the use button no longer functions?

Do you also get the same issue if you were to attach the autograb to the example scene with the light saber?

**Comment by Roland09** [comment]
The "use" functionality is the grip button. 

My script extends from VRTK_InteractableObject. I added debug loggings. It appears that the grip button is still detected when pressed, but the StartUsing and StopUsing methods of my super class aren't invoked anymore. 

I'll try with your light saber code.

**Comment by thestonefox** [comment]
I'll try taking a look at the code, but being without my headset makes testing the problem impossible :(

**Comment by Roland09** [comment]
I can reproduce it now: I took your example (014_Controller_SnappingObjectsOnGrab), removed the collider from Lightsaber and added a collider to Blade. Base doesn't have a collider. Do you have any pointers for me how to fix it? Also, it works when you disable / remove VRTK_Interact Touch from Controller.

**Comment by thestonefox** [comment]
If you remove the collider from the same object that the Interactable Object script is on then the script won't be able to detect any collisions with the controllers (so the touch won't work, which in turn will prevent grab/use from working).

If you add a collider to your object, does it work then?

**Comment by Roland09** [comment]
Yes, it works then. I suggest to perform a consistency check and show an error message.

**Comment by thestonefox** [comment]
I did look at adding a warning in the start method on the interactable object to see if the game object had a collider.

Whilst it worked, I don't think it's the right solution as someone could be adding the collider at runtime in a method that is called after start, which means the message would never get called.

The only other way to ensure it's called is to keep checking in an update routine, which is probably unnecessary. I think for now we'll monitor it and see if it can't be resolved with education as it is really a unity issue where unity needs the collider to be on the same object as the script.
