### ISSUE TITLE
Enhancement(RoomExtender #158): Requests for additions to the RoomExtender Scripts

### ISSUE THREAD

**Issue by appdevtk** [thestonefox/SteamVR_Unity_Toolkit#189]
There are some requests for additions to the RoomExtender #158 scripts and I'll try to add them.

- [x] One thing that I think would really improve things would be perhaps if you press a button on a controller it prevents the movement tracking, so when you walk to the edge of your physical play area (and cannot extend anymore_ then pressing a button stops moving the play area when you walk, then you can walk back to the center of your room and release the button to walk some more.

- [x] along with what Stone suggests (completely agree with this btw), if possible it would be nice to show the extended playspace along with the Chaperone. This way we of course see our play area, and then exactly just how far it's extended, so you can build content to this new volume.
I wonder if it's as simple a n*Chaperone Size? (where n is the extend multiplier)

I'll take a look.

**Comment by xEvoGx** [comment]
Just a further suggestion regarding using a button...

...but perhaps you'd press the button to _engage_ the room extender, as if you were pressing the *Sprint* button in a given game. Walk normally, press/hold button to 'run'.

At the very least make it a toggle: **Press to Extend/No Press to Extend**

**Comment by appdevtk** [comment]
@xEvoGx Do you think this would be enough to show the extended area? 

![roomextender](https://cloud.githubusercontent.com/assets/7008526/16275194/4ec0f63a-38a9-11e6-9b87-cb12317bb998.png)

**Comment by xEvoGx** [comment]
Oh that's perfect! Heck you probably could even get away with a red "Extended Chaperone" that mirrors the play-space chaperone. 

But yea that's awesome! :smile:

**Comment by appdevtk** [comment]
I tried do create the chaperone, but keeping the normal chaperone was not easy. This renders a gizmo.

**Comment by xEvoGx** [comment]
Yea no that's great...really just being able to build to any visual of the extended space is awesome.

Great work man!

**Comment by xEvoGx** [comment]
Not sure if it's worth reopening in case it's something I'm doing/not doing, but simply loading the scene **028 ...RoomExtender**, I do not see the Room Extension Gizmo, **SelectedOnly** on nor off. 

Again nothing special, just loading the scene, so one would expect to see it no?

Thanks!

-Steven
