### ISSUE TITLE
Using Precise grab mode in conjunction with a hinge joint produces strange effects

### ISSUE THREAD

**Issue by clydeshaffer** [thestonefox/SteamVR_Unity_Toolkit#191]
In trying to construct a lever to interact with, I'm finding that the connection point between the lever and the controller is at a point extended far from the controller.

A similar effect occurs for the door in the Grabbing With Joints example, if the door's grab mode is set to precise. The door will open and close as normal, but rotating the controller will produce a large displacement.

**Comment by clydeshaffer** [comment]
It looks like the connection point is at the object's center. The door in the example is not centered on the hinge, so the behavior is less extreme. The lever in my scene is centered on its hinge, so large forces are applied against the constraint of the hinge, causing the lever to flail around.

**Comment by thestonefox** [comment]
Does this PR fix this issue?
https://github.com/thestonefox/SteamVR_Unity_Toolkit/pull/192
