### ISSUE TITLE
Make ForceReleaseGrab a public method in VRTK_InteractableObject

### ISSUE THREAD

**Issue by kurzemnieks** [thestonefox/SteamVR_Unity_Toolkit#195]
Allow forcing releasing grabbed object from script. I don't know if that's a correct way - i found only ForceReleaseGrab method, but it is private. It would be nice to have a public one so I can for example release grab when object is placed in a slot and snap object in place.

**Comment by thestonefox** [comment]
It is already a public method.

You call it on the controller

https://github.com/thestonefox/SteamVR_Unity_Toolkit/blob/master/Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_InteractGrab.cs#L54
