### ISSUE TITLE
Can't increase in-game draw distance with CameraRig and Camera (head)?

### ISSUE THREAD

**Issue by bknie1** [thestonefox/SteamVR_Unity_Toolkit#211]
I see the draw distance box (the big one facing forward) in Unity but can't seem to figure out where you change the variables associated with it. Changing far clipping seems to change something much closer to the camera and doesn't affect draw distance. Just in case, I messed with the different variables in CameraRig and Main Camera, too (just in case, for whatever reason).

![capture](https://cloud.githubusercontent.com/assets/16689276/16435070/79e3ec3e-3d61-11e6-94a2-0a338a1d027b.PNG)

![capture2](https://cloud.githubusercontent.com/assets/16689276/16435125/c0d7483e-3d61-11e6-857f-49c66203a649.PNG)

Am I missing something? Has anyone figured out how to increase in-game draw distance?

Thanks.

**Comment by paulc755** [comment]
Think you are looking for Camera Eyes, child of camera Head.

**Comment by bknie1** [comment]
I'll try again tomorrow. I somehow messed up the FOV doing that. Thanks for the suggestion; will report back.

**Comment by bknie1** [comment]
Yes, thanks Paul. It was the far clip setting in camera (eye).
