### ISSUE TITLE
Need ability to toggle laser pointer on/off by pressing grip

### ISSUE THREAD

**Issue by ribawaja** [thestonefox/SteamVR_Unity_Toolkit#213]
Hi,

I'm working with the SimplePointer.

Currently the options for the laser beam are:
- Beam is always on
- Beam is on when the grip is held, off when the grip is released

For my application, I'd like for the user to be able to turn on or off the beam by pressing the grip, i.e. press and release the grip once to turn on the beam, and later press and release the grip again to turn off the beam.

I hacked together something (below) that works by subclassing SimplePointer and overriding the base's controller events to toggle the beam during AliasPointerOn, and do nothing on AliasPointerOff. 
But I feel a better place for this functionality is within the framework, possibly WorldPointer.
Is it something you would consider?  

Thank you.

--------------------------------
    public class VRTK_SimpleTogglingPointer : VRTK_SimplePointer
    {

        // Use this for initialization
        protected override void Start()
        {
            base.Start();

            //The base class will turn the beam on when the grip button is held, and
            // turn the beam off when the grip button is released.
            //We want the grip to turn on when the grip is pressed and released, and
            // turn off again when the grip button is pressed and released.
            //Undo the base class's beam on/off callbacks.

            GetComponent<VRTK_ControllerEvents>().AliasPointerOn -= base.EnablePointerBeam;
            GetComponent<VRTK_ControllerEvents>().AliasPointerOff -= base.DisablePointerBeam;

            //Now register our own callback
            GetComponent<VRTK_ControllerEvents>().AliasPointerOn += TogglePointerBeam;
        }

        protected virtual void TogglePointerBeam( object sender, ControllerInteractionEventArgs e )
        {
            if ( IsActive() )
                DisablePointerBeam( sender, e );
            else
                EnablePointerBeam( sender, e );
        }
        
    }
}

**Comment by thestonefox** [comment]
i wonder if this is better to do as a setting on the beams or extend them the way you have?

Doing the toggle would be easy enough on the script as a parameter. I'll take a look a bit later

**Comment by ribawaja** [comment]
Yes, I think the issue of whether this belongs in the Toolkit as a beam property or as a extension that should be left up to individual users of the Toolkit to implement themselves comes down to whether this behavior is something that would be broadly useful or whether it's some oddball case. I don't have any perspective on this as I'm completely new to Unity and VR. 
As far as my particular use case, I'm not using the beam as a teleporter, but as a laser pointer that is used to select objects. I want to be able to grab a nearby object by reaching out and pressing the trigger, and also be able to "grab" a distant object by aiming the laser pointer at it and pressing the trigger. But I don't want this 2nd "grab distant" mode to be on all the time, nor do I want to require holding the grip down continuously for this mode to be active, because it's awkward to hold the grip button down for any length of time while at the same time manipulating the touchpad, trigger etc. 
Anyway, use your judgment and feel free to close this issue. 
And thanks for releasing your toolkit to the community!

**Comment by thestonefox** [comment]
PR to resolve this https://github.com/thestonefox/SteamVR_Unity_Toolkit/pull/362
