### ISSUE TITLE
Two pointers on one controller

### ISSUE THREAD

**Issue by couba** [thestonefox/SteamVR_Unity_Toolkit#220]
I'm trying to put Simple Pointer and Bezier Pointer on one controller and depending on situation use one of them for teleportation. In my case, I have an architectural model, which I view in different scales. In human scale I'd like to teleport with Bezier and in 1:100 scale I want to use the simple pointer to teleport back to 1:1 scale. 

It works when I use one of the pointers but when I put both, teleportation works only with the script, which is higher in hierarchy. 

Another issue is that during runtime disabling the bezier pointer script, prevents its curve from displaying, which is good. But when I disable the simple pointer script, its laser keeps showing up while using the bezier pointer. 

I hope there is an easy workaround. Thanks

**Comment by thestonefox** [comment]
I think this is because the Teleporter only does a GetComponent to find the destination marker rather than a GetComponents (so it will just get the first one)

I can probably update it so it finds all scripts to register.

I'll take a look at the simple pointer not turning off issue as well.

**Comment by thestonefox** [comment]
@couba check out this PR

https://github.com/thestonefox/SteamVR_Unity_Toolkit/pull/221

Does it fix your problem? If so then I'll merge it into master

**Comment by couba** [comment]
I see you have already merged it. Just wanted to confirm that it is working. Thanks

**Comment by thestonefox** [comment]
I've given it a pretty rigourous test :) it seems to be working much better
