### ISSUE TITLE
Tooltips are broken when when the game is built

### ISSUE THREAD

**Issue by TMaloteaux** [thestonefox/SteamVR_Unity_Toolkit#224]
The controller tooltips works fine in Unity but are broken after the build process.

```
NullReferenceException: Object reference not set to an instance of an object
  at VRTK.VRTK_ObjectTooltip.DrawLine () [0x00000] in <filename unknown>:0 
  at VRTK.VRTK_ObjectTooltip.Update () [0x00000] in <filename unknown>:0``
```

**Comment by thestonefox** [comment]
Make sure you have the required shaders in you project Graphics Settings:

![image](https://cloud.githubusercontent.com/assets/1029673/16529594/b923cc32-3fbb-11e6-8bf4-9deeb30b6ee1.png)

You're most likely missing `Unlit/Color` and `UI/Overlay`

**Comment by TMaloteaux** [comment]
It works! thank you for your help :)
Where can i found required shaders to avoid this in the future? Do you have a list?

**Comment by thestonefox** [comment]
There isn't a list anywhere, but it's a good idea to do one, I'll put one in the readme
