### ISSUE TITLE
How to make controller semi-transparent

### ISSUE THREAD

**Issue by wheatgrinder** [thestonefox/SteamVR_Unity_Toolkit#227]
Hi,
thanks so much for this toolkit.  Im nearly done with my project thanks in large part to you!!!!

I would like to make my controller semi transparent.  All my techniques for manipulating color\alpha do not seem to work.  The values get updated, but nothing changes during runtime.  

I think its more to do with my ignorance on how the controllers are instantiated.  Any assit\guidance here would be appreciated. 

Thanks

**Comment by thestonefox** [comment]
![image](https://cloud.githubusercontent.com/assets/1029673/16681774/a79d9d2a-44ee-11e6-81b0-7c45a5549c49.png)


This points in the right direction for making controllers semi transparent

```
            foreach (var renderer in this.gameObject.GetComponentsInChildren<Renderer>())
            {
                renderer.material.SetInt("_SrcBlend", (int)UnityEngine.Rendering.BlendMode.One);
                renderer.material.SetInt("_DstBlend", (int)UnityEngine.Rendering.BlendMode.OneMinusSrcAlpha);
                renderer.material.SetInt("_ZWrite", 0);
                renderer.material.DisableKeyword("_ALPHATEST_ON");
                renderer.material.DisableKeyword("_ALPHABLEND_ON");
                renderer.material.EnableKeyword("_ALPHAPREMULTIPLY_ON");
                renderer.material.renderQueue = 3000;

                renderer.material.color = new Color(renderer.material.color.r, renderer.material.color.g, renderer.material.color.b, 0.5f);
            }
```

**Comment by wheatgrinder** [comment]
THANK YOU!

**Comment by thestonefox** [comment]
I'm going to make this part of the toolkit so you can call a method to set the transparency of the controller

**Comment by wheatgrinder** [comment]
well thank you.  Ill defintely use it

**Comment by thestonefox** [comment]
Completed with: https://github.com/thestonefox/SteamVR_Unity_Toolkit/commit/1dce8839fe716e919ba83f0349033dcaf07c2c95
