### ISSUE TITLE
ForceRelease during TriggerPressed causes problems for next pickup

### ISSUE THREAD

**Issue by moonylo** [thestonefox/SteamVR_Unity_Toolkit#230]
Hi there,

I have an object (arrow) grabed in one hand and a bow in the other hand. When the arrow is close to the bow string and the arrow controller presses down the trigger, I use ForceRelease, so that I can add the arrow to the bow (keeping it grabbed is not viable for rotation and distance issues). Then you can aim and once you release the trigger, the arrow is launched.

However, that causes a problem with the Controller that was holding the arrow before. When I try to pick something up after the arrow wa shot, I only have the item grabbed until I release the trigger (Important Note: "Hold Button To Grab" is false on all items). I am expecting it to stay. After the first item dropped for that reason, every Item works fine again.

I tried to track down the problem, but unfortunately couldn't find it. Any ideas?

Btw: Awesome work! :)

Best Regards
Jan

**Comment by thestonefox** [comment]
Is it because you're doing a ForceRelease (on the grab) but when you actually fire the object (with the trigger which is probably mapped to the use action) you would also need to do a ForceStopUsing (on the interact use script)?

**Comment by moonylo** [comment]
I don't make use of the "use" scripts and don't have them attached to my controllers. all the objects are also not VRTK-useable. Could it still be the issue?

**Comment by thestonefox** [comment]
maybe I'm not understanding the problem.

So you fire the arrow (you press the trigger to fire it). then after that any object that is set to "hold button to grab = off" requires you to hold the button to grab?

**Comment by moonylo** [comment]
Sorry for not explaining properly :)

I have the arrow in my right controller and then I press down the trigger on that controller, That ForceRelease's the arrow out of that right controller. [Then I add that arrow to my bow and do stuff there.] I am still holding the trigger down. When I now release the Trigger, the bow fires the arrow.

When I now want to pick up any other item with the right controller, e.g. a new arrow, that has "hold button to grab" = off, it feels like "hold button to grab" = true. But the issue is not on the item, but somehow conntected to the controller. Because if I do the same without the bow stuff before, it works perfectly fine. Also works again after I picked (and it automatically dropped) one item.

**Comment by moonylo** [comment]
I tried to reproduce the problem using one of your examples. I couldn't do it, there it works perfectly fine. Guess I overlooked something. I'll try to compare what happens using the working example. Thank you for your help! :)
