### ISSUE TITLE
touchedObject strange result

### ISSUE THREAD

**Issue by stevenwanhk** [thestonefox/SteamVR_Unity_Toolkit#235]
Way to reproduce:
1. Grab an object with your right controller, so touchedObject in interactTouch on right controller is this object now
2. Touch the object with left controller , so touchingObject in InteractableObject on the object is left controller
2. If I call SetActive(false) on that object, OnTriggerExit will not be called, so even ForceStopInteracting is called, the touchedObject on the right controller will stay as the object because touchingObject is the left controller, thus causing bug

**Comment by thestonefox** [comment]
Does this PR fix your issue?

https://github.com/thestonefox/SteamVR_Unity_Toolkit/pull/242

**Comment by thestonefox** [comment]
@stevenwanhk ok, what if the ForceStopTouching happens before the ForceRelease or ForceStopUsing as in this commit:

https://github.com/thestonefox/SteamVR_Unity_Toolkit/pull/242/commits/40fa57792b310b233aad4ce334809bde45346448

Does that fix it?
