### ISSUE TITLE
Touched object endless loop

### ISSUE THREAD

**Issue by smygarn** [thestonefox/SteamVR_Unity_Toolkit#236]
I've put some rumble on controller-touch. Sometimes it produced contiously rumbles.

When looked into this I found out that it will sometimes get into an endless loop in:

private void OnTriggerEnter(Collider collider)

private void OnTriggerStay(Collider collider)

**Reproduce**: Just two boxes close to each other with rumble or debug.log..

I can see that it's a behaviour between touchedObject and lastTouchedObject.

**Comment by thestonefox** [comment]
This PR should address the issue:

https://github.com/thestonefox/SteamVR_Unity_Toolkit/pull/239
