### ISSUE TITLE
Ability to teleport without pointer hitting an object

### ISSUE THREAD

**Issue by fyrefli** [thestonefox/SteamVR_Unity_Toolkit#243]
First, thanks for this great toolkit! 

I am trying to get a function where you can teleport without having to hit an object, so that you can travel the distance of your pointer length in any direction, including into the air without an object beneath you. Any ideas how to get this function?

**Comment by thestonefox** [comment]
Do you need to use the straight (Simple) pointer? If you use the bezier pointer then it always projects the beam to the ground.

If you do require the simple pointer, one thing you could do is always check the max length of the ray and if it's at full length and not hitting anything then you could create a temp game object (with a collider) to appear at the position of the pointer cursor then it will always have something to collide with.

**Comment by fyrefli** [comment]
Yes, I require the simple pointer, because I want to teleport into the air. The idea being you are not limited to teleporting to a ground plane or object, but have the capability to travel in open space (ie, if you were in water you could "swim" anywhere, not just to an object/ground). It sounds like your suggestion could be perfect to accomplish this. I'll test it out. Thanks!
