### ISSUE TITLE
CameraRig Missing from VRTK Prefabs Folder

### ISSUE THREAD

**Issue by Nova66** [thestonefox/SteamVR_Unity_Toolkit#244]
I don't know when this happened but the [CameraRig] is missing from the prefabs folder in the latest version of VRTK (Commit No. 247).

Is the intent that we use the [CameraRig] from Valve's SteamVR Plugin instead? And if so, are the reasons for forking the [CameraRig] in the first place no longer an issue?

I'm not a programmer so VRTK has been indispensable for my Architectural modeling workflow. I can't thank you enough for making these scripts available to all us noobs :-)

Thanks.

**Comment by thestonefox** [comment]
Yes the latest release supports the default steam vr prefab now
