### ISSUE TITLE
[Interaction] Ability to grab items on any point of the item (i.e. no snapping on the item)

### ISSUE THREAD

**Issue by thestonefox** [thestonefox/SteamVR_Unity_Toolkit#25]
This video for reference:
https://www.youtube.com/watch?v=nMYWpGFzcvI&feature=youtu.be&t=76

**Comment by thestonefox** [comment]
Refer to this as precision grabbing

**Comment by bcoyle** [comment]
Looks like the dev from that video used vrdev school to figure out the mechanic, http://learn.vrdev.school/courses/vive-developer-mini/lectures/832452

**Comment by thestonefox** [comment]
I have a hunch that if I don't set the position of the collided object to the transform position of the controller then it may just work as you want.

Let's hope it's that easy ! :)

I'll still make it an option on the interactable object so you can choose the grab method for objects

**Comment by bcoyle** [comment]
Love it. I really dig how you fold many of the options for the various mechanics into single scripts

**Comment by thestonefox** [comment]
Heh, it is as easy as I thought it would be....expect a new version in a couple of hours :p

**Comment by thestonefox** [comment]
Completed with b025c9a9e6980d11650481f8e45c8ad617f740f3
