### ISSUE TITLE
Any way to fake a button event on a controller?

### ISSUE THREAD

**Issue by jkredz** [thestonefox/SteamVR_Unity_Toolkit#252]
Hello,

  I was wondering if there was a simple way to "fake" a button event on the controller.  I am grabbing an object, which becomes a child of another gameobject when it collides.  The grabbed object loses its rigidbody as well.  I want the controller to EmitAlias(Button Alias.Grip, false ...), since the controller still thinks its grabbing the object, however most of the controller script properties and methods are private.

Any suggestions on tackling this?

Also keep up the good work with improving and updating this repo.

**Comment by thestonefox** [comment]
If you need to stop the controller from knowing it's grabbed an object then on the object there is a public method called `ForceStopInteracting()`

https://github.com/thestonefox/SteamVR_Unity_Toolkit/blob/master/Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_InteractableObject.cs#L298

If you call that on your object then it will force detach the controller's relationship with the object.

**Comment by jkredz** [comment]
Ahh, thanks!  I have an older version of the repo so I didn't see that method.  The repo just gets better and better.  

For other cases in the future, is there a simple way to fake a button event on the controller?  Or would it be relatively difficult process.

**Comment by thestonefox** [comment]
You could make the EmitAlias method public, that should do it. However, it may not be best to fake a button event rather than allow for what the button should be doing to be called another way,
