### ISSUE TITLE
snap point direction

### ISSUE THREAD

**Issue by smygarn** [thestonefox/SteamVR_Unity_Toolkit#253]
I don't understand the forward direction of snap points. To be able to correct setup a gun in the 014_Controller_SnappingObjectsOnGrab example, you have to point the red (x) angle in about 30 degrees to the right.

**Comment by thestonefox** [comment]
It would be better if an explanation of how you think they should work was provided and even better to provide a PR to show your solution.

Hard to deal with an issue based around someone not understanding something.

**Comment by smygarn** [comment]
The best solution is that the snapping point should point in the wanted controlled object space. It should be easy to point out the snapping in the editor. Now you have to make a mathematical transform by yourself, or a lots of trial to make it correct. ;)

The only way to test if you got it right is to pick up the tool in VR.

**Comment by thestonefox** [comment]
I looked at this issue last night.

The snap point works as expected when the model is built in the correct orientation (oriented to the controller).

If the model is built in a different orientation then the snap point will look odd as it's rotated in a strange way to meet the orientation of the controller.

I think a gizmo showing the orientation of the controller may help in the future. But in the short, if you add a cube as a child of the controller and model things around the position of the controller then the snap point works as expected.

**Comment by smygarn** [comment]
OK. It's a bit strange though because all my objects needed reorientations when swapping from NewtonVR to VRTK.

**Comment by ZackOfAllTrades** [comment]
I hate to beat a dead horse.. I don't get what your driving at. I read this and #472 but I'm not sure the correct way to use VRTK snapping.  The object being attached has strange rotations, like a previous commenter said the x value is off about 30 degrees.  I modeled a cube as the child of the controller but still same result, maybe I need clarification on what that means.  Thanks!!!!

**Comment by thestonefox** [comment]
this has been fixed in 3.3.0-alpha
