### ISSUE TITLE
Teleport to ground from the roof of a tall building

### ISSUE THREAD

**Issue by Nova66** [thestonefox/SteamVR_Unity_Toolkit#256]
I'm using the HeightAdjustTeleport script and I can no longer teleport down to the ground if I'm standing on the roof of a building that's higher than 40 or 50 meters.

I'm working with a multi storey gantry and it is easy enough to teleport up through the ceiling but once I'm on the roof, I can no longer teleport directly to the ground outside. This used to be possible in the past and it was a very quick and convenient way to get back to the ground.

I'm not sure if I'm missing an obvious setting somewhere or the behaviour of the HeightAdjustTeleport script has changed.

Thanks.

**Comment by thestonefox** [comment]
what pointer are you using? also what is the length of the pointer?

For instance, if you're using the simple pointer and the pointer length is less than the distance to the floor then the pointer wont be long enough to reach a target.

**Comment by Nova66** [comment]
Sorry, I should have mentioned this in my original post. I'm using the Bezier Pointer and the Pointer Length is set to 15.

For horizontal movement I don't think I want to set the Pointer Length much more than 15 so I don't know if that's going to be my solution. As I mentioned above, I used to be able to teleport from high buildings with previous vesions of VRTK.

I wonder if this issue is related to the fact that we are now using the [CameraRig] from Valve's SteamVR Prefab rather than VRTK?

**Comment by thestonefox** [comment]
From looking at the bezier pointer, the projected beam forward and projected beam down are both defined by the pointer beam length so it will only project down to 15.

I'm not sure if this is the correct behaviour. I would assume it should only project forward that length but always project down to the nearest floor.

**Comment by thestonefox** [comment]
looks like it was introduced in this commit:

https://github.com/thestonefox/SteamVR_Unity_Toolkit/commit/6177e13bc3fd79656ad77cdd73a6e9a83198a5c2

I'll fix it so it projects all the way back to the ground, give me an hour :)

**Comment by thestonefox** [comment]
fixed in https://github.com/thestonefox/SteamVR_Unity_Toolkit/commit/fcc6eb2a33fb0059e0fc38031f053f354db71814

**Comment by Nova66** [comment]
That did the trick Mr Fox :) 
Thanks so much for such a quick turn around.
