### ISSUE TITLE
Teleport and cursor issues

### ISSUE THREAD

**Issue by frozenMeatpopsicle** [thestonefox/SteamVR_Unity_Toolkit#26]
1. Cursors and teleporting do not work in a built game, ie. not in a built exe but only in the Unity editor.

2. (in editor)Can only teleport with one hand, despite both controllers being initialized correctly, before and during the game running.

Don't know if it's just me getting these problems though.

**Comment by bcoyle** [comment]
Maybe this explains why teleporting wasn't working for me in the latest release. I've been building one demo over and over trying to figure out what teleporting isn't working. Not sure if I'm just doing something wrong with how I bring the files into my own project.

**Comment by thestonefox** [comment]
Teleporting now uses a custom shader called unlit/transparentcolor

You need to make sure that shader is included in your build settings (it is in the project scene but in your own project you'll need to go to `project settings->graphics ` and add a new shader.

I'm going to do a video covering these sorts of issues along with an FAQ on the readme.

**Comment by thestonefox** [comment]
I've made a FAQ video on how to rectify the missing shader issue:
https://www.youtube.com/watch?v=IsmYoLTmX4c

**Comment by bcoyle** [comment]
Ah so this is still needed. I remembered it from before and tried unlit/color, forgot it was unlit/transparentcolor! Something also to be aware of is that Oculus has it's own version of this shader: Unlit_TransparentColor.shader (is SteamVR), and Unlit Transparent Color.shader (is Oculus). Although I haven't looked at their latest SDK which might have changed the files or names.

Is there any way to inject this shader into the graphics automatically? Or embed the update into a unity package? Each time there's an update to the toolkit, I'm going in and making a unity package to import into my project. Is there a better way to integrate?

**Comment by thestonefox** [comment]
I'm not even sure this toolkit would work on the Oculus (I mean it should because it supports SteamVR!) but I don't have one to test on.

The Unlit_TransparentColor is a custom shader I wrote so I'm hoping it's just universal (it's really basic)

I have no idea if they can be added to the project build settings automatically. I can look into it, it would be nice if you could (I wonder if the editor scripts in unity allow this?)

**Comment by bcoyle** [comment]
Yeah I haven't tested these scripts with Oculus (still no Rift in sight), it was just that I had some residual files in some older projects and noticed there were multiple Transparent Color shaders. So others are aware.

Can't wait to test the latest toolkit tonight! Hopefully it all goes smoothly :)

Thanks

**Comment by frozenMeatpopsicle** [comment]
Cool, that fixed the build issue. Thanks.

The one handed teleport is persistent though. Now I know it's the same in a built version. At least for me.

**Comment by thestonefox** [comment]
I "think" i know the issue with the controller.

The teleport script has a basic loop to check for the presence of the world pointer events (emitted from the controllers). It only checks 5 times, with a break of 0.25 seconds per check.

If the controller isn't tracking quite correctly when unity starts playing then the listener isn't added.

Potential solutions would be:

 * Increase the loop limit to something higher than 5 so you have more chances to check, which wouldn't be a massive performance issue as it's just done using invoke (which is a delayed event anyway).
* Perform a check for the world pointer event periodically in the update method of the teleporter (if it's not already been found). This would provide the ability to connect a controller after the game has started and it should then (eventually) work. This may suffer an initial performance hit when connecting a controller. Wouldn't be too bad though
