### ISSUE TITLE
Unity crash - Example 34

### ISSUE THREAD

**Issue by reddo123** [thestonefox/SteamVR_Unity_Toolkit#261]
Unity version - 5.4.0b24 personal - Windows
Unity crashes on opening GUI example - 034_Controls_InteractingWithUnityUI

**Comment by thestonefox** [comment]
This is an issue with unity beta b24, it seems to work ok on beta b20.

I'm assuming it's something Unity need to address, as any piece of code in the toolkit should not crash the Unity application.
