### ISSUE TITLE
How can I test this without a headset ?

### ISSUE THREAD

**Issue by punkouter** [thestonefox/SteamVR_Unity_Toolkit#262]
Can there be a mock headset or something so that when I am other places or do not want to stand up and use the headset I can just use the keyboard to move the headset/controllers around ?

**Comment by thestonefox** [comment]
That's a lot harder than it seems, I wouldn't expect anything like this soon, unless anyone wants to pick up the challenge of implementing it

**Comment by quintesse** [comment]
I actually have 2 cameras in my project: a normal one using normal controls and a VR one using teleportation mechanics etc. I just enable/disable the needed one at startup.

**Comment by thestonefox** [comment]
@quintesse  that's a way of exploring the scene, but it unfortunately doesn't mimic the vr interaction with the game world so the only way to do it is to put on the headset and grab the controllers.

**Comment by punkouter** [comment]
that's ok.. the main point is my headset and controllers exist in space and can bump into things.. for example I create a brick wall at work and want to see how punching the way would work.. I'm trying to figure out how  Ican simulate that .. and then fine tune it with the real headset when him..

**Comment by thestonefox** [comment]
as far as i know, people are putting their headsets on and standing up, the same as you

**Comment by punkouter** [comment]
I would need total control.. just enough to bump the 3 things around... like if you put the headset and controllers on a statue with wheels on the bottom.. I haven't done much with it yet so maybe I'm missing something.. just seemed like it would be helpful from the little I know.. Just have a checkbox on the prefab to go between testing and using the real headset

**Comment by 10FingerArmy** [comment]
I actually use a different technique which at least for me works very efficient. I sit in front of my PC. To my left I have a stand onto which I put the Vive headset, pointing to me. So when I press play, I see the camera as if I turn my head to the right. I then pick up the controllers and interact with objects to my right. To make that work effectively I simply move objects I want to try out to a location which would be exactly to the right of where I sit. This makes for super fast turn-arounds while still being able to use the controllers and I only put on the headset once I want to validate in 3D.

**Comment by thestonefox** [comment]
Initial PR to tackle this https://github.com/thestonefox/SteamVR_Unity_Toolkit/pull/324
