### ISSUE TITLE
Release grab during a collision

### ISSUE THREAD

**Issue by Cubiverse** [thestonefox/SteamVR_Unity_Toolkit#263]
I've a situation where I "nail" grabbed objects into static positions, in the OnCollisionEnter() of my VRTK_InteractableObject I set isGrabbed = false so that the object cannot be grabbed again.

However when the grab is released, the Ungrabbed() is called and the function LoadPreviousState() will set the grabbed back to previousIsGrabbable (along with the previousKinematicState)

In my case I don't want this, I'm not sure if a bug or just my use case but essentially I override the Ungraded method as such:

	override public void Ungrabbed(GameObject previousGrabbingObject)
	{
		base.Ungrabbed(previousGrabbingObject) ;
		/* Set grabbing, only if the item is not nailed up */
		isGrabbable = !bIsNailed ;
	}
		
This might help others, or you may be able to tell me what I'm doing wrong to require this code :)

**Comment by thestonefox** [comment]
you don't really want to short circuit the `isGrabbed` variable because it will cause your problem (obviously :p)

You want to call `ForceRelease` on the controller to make it stop grabbing the item. Then in the `Ungrabbed` overriden method (as you do above). You then want to set the relevant params (such as the isGrabbable` param)

**Comment by Cubiverse** [comment]
Thanks for the quick response, I'll try implementing it

**Comment by Cubiverse** [comment]
I ended up using the code found in the BowAim.cs as I could not get a way to reliably call ForceRelease() (or I couldn't figure out a way to call it from an VRTK_InteractableObject that worked 100% of the time.. )

**Comment by thestonefox** [comment]
If you want to call it from the Interactable Object then you can call `ForceStopInteracting()`

https://github.com/thestonefox/SteamVR_Unity_Toolkit/blob/master/Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_InteractableObject.cs#L298

Which will stop all interactions with that object.
