### ISSUE TITLE
Null reference error in DeviceFind when using The lab renderer.

### ISSUE THREAD

**Issue by smygarn** [thestonefox/SteamVR_Unity_Toolkit#264]
Since I don't have any SteamVR_Camera when using the lab render I got null reference in DeviceFinder when seting up teleport:
```

        public static Transform HeadsetTransform()
         {
 #if (UNITY_5_4_OR_NEWER)
             return GameObject.FindObjectOfType<SteamVR_Camera>().GetComponent<Transform>();
 #else
             return GameObject.FindObjectOfType<SteamVR_GameView>().GetComponent<Transform>();
 #endif
         }

         public static Transform HeadsetCamera()
         {
               return GameObject.FindObjectOfType<SteamVR_Camera>().GetComponent<Transform>();
           }
```

This worked for me:

```
		public static Transform HeadsetTransform()
		{
			return Camera.main.transform;
		}

		public static Transform HeadsetCamera()
		{
			return Camera.main.transform;
		}

```

**Comment by thestonefox** [comment]
Why are you removing the `SteamVR_Camera` from your `Camera (eyes)` game object?

The Lab Renderer instructions don't say to do this (as far as I can see) and the Lab Renderer camera works fine in conjunction with the SteamVR_Camera.

You can't just look for the main camera as the main camera may not be the VR camera for example in cases of mixed reality where a normal camera is also required.

**Comment by smygarn** [comment]
Well, I just used the same camera-model from the labs in the unity store and added controllers.

**Comment by thestonefox** [comment]
Right ok, that's because Unity 5.4 supports a VR camera by default with the basic Main Camera.

However, the toolkit requires the SteamVR CameraRig camera prefab to work (for a number of reasons as it has many more helpers applied to it).

In short, to use the toolkit you need to be using the SteamVR CameraRig.

**Comment by smygarn** [comment]
Yes it's not a big deal but I'm still using Camera.main myself as most of the unity developers, and I don't think you should tag a spectator camera to Camera.main.

I really like to use the embedded functions instead of looking for a specific type, tag or name.
