### ISSUE TITLE
Changing simple pointer's tip

### ISSUE THREAD

**Issue by reubengann** [thestonefox/SteamVR_Unity_Toolkit#265]
Edited because I discovered issues since my original post.

I'm working on something where I'd like to customize the pointer shown in the SimplePointer via a derived class. I know that Bezier Pointers have the ability to set the pointer to a custom object, but I'd prefer a straight pointer. Reason being is that the pointer will act as a "look", "speak", etc command as well as move. So when it's hovering over an object you can walk to, a walk symbol will appear, if you can talk it will turn into a mouth, etc.

The process was somewhat successful, but it's unfortunately not quite straightforward. I made a copy of the SimplePointer script and edited:
`//pointerTip = GameObject.CreatePrimitive(PrimitiveType.Sphere);
pointerTip = Instantiate(Resources.Load("WalkSymbol", typeof(GameObject))) as GameObject;`

The first issue is that the scale is hardcoded as 0.05f along all dimensions, and this makes my imported object tiny. I had to add a new property that was PointerTipScale and add code to handle this. The pointer object also doesn't quite anchor to the end of the beam, which you can see when it's close-up. I have no idea why this is at present.

Any advice would be appreciated. Thanks for all your hard work. Loving the tools.

**Comment by thestonefox** [comment]
I want to make it so you can provide a custom pointer tip object for the simple pointer (like you can provide a custom cursor for the bezier pointer).

I'll take a look at adding this today as i dont think it will take too long.

**Comment by thestonefox** [comment]
Check out this PR
https://github.com/thestonefox/SteamVR_Unity_Toolkit/pull/267

Would it work for you?

**Comment by reubengann** [comment]
Sorry for the late reply, but after updating to the newer version I cannot even get the examples running. I'm not sure what's going on. The prefabs folder in the master, for instance, is now missing the Camera Rig? I must be doing something wrong.

**Comment by reubengann** [comment]
The solution works, but it has the same issue that I had when I modified SimplePointer, which is that the model doesn't quite stick to the end of the ray. I've attached the model I'm trying to use as an FBX. I ended up changing the scale on it to 0.5 to not make it huge, but you can see the issue if you are near the object that you're pointing at. I think it might have to do with the anchor point of the object, but I'm not sure.

[WalkSymbol.zip](https://github.com/thestonefox/SteamVR_Unity_Toolkit/files/362465/WalkSymbol.zip)

**Comment by reubengann** [comment]
Also, if possible I'd like to add functionality to this. For instance, I want to be able to change the displayed tip based on what is being targeted. The pointerContactTarget in WorldPointer would do the job, but it's protected and hence inaccessible except from a derived class. When I try deriving a class from SimplePointer, the beam never displays (likely some problem with multiple inheritance, though I am not an experienced Unity user). Do you have a suggestion how to do this? Basically, I would prefer to do something like this:

1. Attach an empty gameObject as the pointerTip
2. on update, check what the pointer was pointing at and add the correct symbol to the gameObject, removing any invalid ones
3. If there are multiple interactions available (such as LOOK at a character or TALK to a character), then highlight one of the models and allow the user to switch between them with the touchpad.

Thanks so much

**Comment by thestonefox** [comment]
I'll have a think about this. Maybe it would be cool if the game object you attach as the pointer cursor could also have a script attached that would need to adhere to a certain interface but then you'd be able to hook in to the pointer in/ pointer out events on the pointer.

**Comment by reubengann** [comment]
One attempt to solve this was semi-successful, but of course it makes my code so that I can't keep it current with your project. I set the pointerContactTarget property of WorldPointer to public, which allowed me to see the object the pointer was colliding with. Then a separate script can just on top of that and look for changes in that variable. If so, the GameObject set to the pointer could be updated. That's not very efficient, and it would be better to listen to the function that initiates the change, but it did work.

What I haven't tried, though, is the material handling. The code updates the unlit material colors, but they would seem to apply to the whole object. I wanted to highlight one item, then change it in response to the users choice, highlighting one item. I haven't worked out how to do this yet.

**Comment by thestonefox** [comment]
I worked out a solution to the changing pointer issue. Where you have a script attached to a custom cursor and then listen for the pointerIn and pointerOut events on that script to swap the cursor.

You wouldn't need any custom code then. I worked it out on a twitch stream last night so I'll cut up the solution and put it on Youtube and link to it for you.

**Comment by thestonefox** [comment]
It would seem that twitch has decided not to save my past broadcast so I don't have the footage :(

I'll try recreate the script again at some point, but if you can't wait then the solution is to have a custom pointer (that works as the default pointer tip) then have children in that game object that act as the other pointer tips.

Then attach a script on that custom game object that listens for the pointer In and pointer Out events. Then on the pointer In you want to get the `e.target` and determine which pointer you want to display (I was just turning on the enable state of one of the child pointers and turning off the mesh renderer of the main object).

Then on pointer out, you want to turn off the custom pointer tips and turn the mesh renderer back on for the default pointer tip.

**Comment by reubengann** [comment]
I'm trying this out, but I'm possibly too n00bish here. I think what you're suggesting is I create a script on the GameObject that has code like
`public VRTK_SimplePointer Pointer;

        // Use this for initialization
        void Start()
        {
            Pointer.PointerIn.AddListener(() => UpdateCursor(Event e));
        }

        void UpdateCursor(Event e)
        {
              if(e.target == VRTK_InteractableObject)
              {
                   //do some stuff
              }
        }
`
I don't know know if that's what you mean. I immediately get an error that PointerIn is inaccessible. I feel like there's something big I'm missing.

Thanks for your continuing help.

**Comment by thestonefox** [comment]
Don't worry, I'll recreate the script and record myself doing it and put it on youtube as an FAQ. Hopefully it will be up by the end of the day.

**Comment by thestonefox** [comment]
Here is the gist to the custom code I wrote. I'll get the video sorted for it soon.

https://gist.github.com/thestonefox/02bb6a877ebe17572ae24f44bf939719

**Comment by thestonefox** [comment]
@reubengann here you go, video of how to do what I did :)

https://youtu.be/P_4ljG4_c8g

**Comment by reubengann** [comment]
Amazing work. That's great. One thing that's weird is that I have "restrict to navmesh" on for the teleportation, and when I pass it over an object that you can't teleport to the beam stays red. I would think since DestinationMarkerEnter was called that it would be green. I plan to handle the texturing of the cursor objects manually anyway, but I haven't investigated whether I can change the beam.

Thanks again

**Comment by thestonefox** [comment]
The reason it's red is because it's not a valid teleport location and the teleporter reports it's invalid back to the pointer to change its color.

**Comment by reubengann** [comment]
Right. I got around the issue with an (admittedly ugly) hack: I just manually set the SimplePointer miss color to green when it's over a valid target in my game, and set it back later.
