### ISSUE TITLE
Hinge Joint Rotation 

### ISSUE THREAD

**Issue by monozoo** [thestonefox/SteamVR_Unity_Toolkit#268]
I would like to rotate a hinged object according to the rotation of the vive controller. 
With the hinge anchor in the center of the object it is working, but when the hinge anchor is not centered 
it is not. 
I use the grab mechanic: Track_Object
Maybe its not really an issue, but an usage error? 

I have added an example project in case somebody is so kind to take a look. 

[Hinge Joint.zip](https://github.com/thestonefox/SteamVR_Unity_Toolkit/files/362275/Hinge.Joint.zip)

Thx in advance and thank you all for the great toolkit

**Comment by thestonefox** [comment]
i'll take a look and see if i can see what's going on.

**Comment by thestonefox** [comment]
So I managed to get the hinge joint to work. I couldn't get it to work in your scene. But in a fresh scene I added pretty much the same models as you. The one thing I did (not sure if it helped) was to make the cylinder a Kinematic rigidbody, then set the hinge on the cube to point to the cylinder for the Connected Body.

Seemed to work with the track object mechanism.
