### ISSUE TITLE
Using an object bug?

### ISSUE THREAD

**Issue by frozenMeatpopsicle** [thestonefox/SteamVR_Unity_Toolkit#27]
Ever since the recent addition of the analog trigger function, my previously working script on a usable object now seems to need at least a double press to "use". Could be the analog messing with it, but could also be my script. I'm not sure.

Might need to differentiate partial press and a full press? This is assuming they are actually separate, like a Steam Controller.

**Comment by thestonefox** [comment]
The trigger axis is a different event to the trigger press event so they shouldn't interfere with each other.

It may be a new interactable object setting causing the issue, see what you have set for `hold button to use ` and `hold button to grab`

**Comment by frozenMeatpopsicle** [comment]
Yea, swapping the buttons still gives me the same problem.

I hate to get you to troubleshoot my code, but since it's almost identical to your given examples, I don't understand why it's doing it.

```
using UnityEngine;
using System.Collections;

public class FlashLightVR : SteamVR_InteractableObject
	{
		public Light flashlight;
		public Light glowlight;
		public AudioClip flSound;
		private AudioSource flAudio;

	public override void StartUsing(GameObject usingObject)
	{
		base.StartUsing(usingObject);
		FlashlightToggle ();
	}

	void Awake ()
	{
		flAudio = GetComponent<AudioSource> ();
		flAudio.clip = flSound;
	}

	void FlashlightToggle ()
	{
		flashlight.enabled = !flashlight.enabled;
		glowlight.enabled = !glowlight.enabled;
		flAudio.Play();
	}
}
```
Everything works as it should, apart from the double-tap being needed. As said, this issue only appeared in a recent build of the toolkit, don't know when exactly.

**Comment by thestonefox** [comment]
Do you have the "hold button to use" option checked or unchecked?

If you've got it unchecked then it may be the same problem i had with the gun. When you press it once it toggles the "on" state and the "i'm using state".

When you press it again, it toggles the "off" state and "i'm not using state". Then you have to press it again to get it back to being on.

**Comment by frozenMeatpopsicle** [comment]
Okay, that has fixed it. Thanks.
