### ISSUE TITLE
034_Controls_InteractingWithUnityUI Unity crash

### ISSUE THREAD

**Issue by smygarn** [thestonefox/SteamVR_Unity_Toolkit#271]
Unity UI unfortunately crashes latest Unity, (5.4b24 and 5.4b25 tested) when just loading the scene. Not easy to debug either and probably an issue with Unity but have to make a report because it's very important.

Will send Unity a crash report as well.

Found out something here:
http://answers.unity3d.com/questions/831692/unity-crashes-when-loading-a-specific-scene.html

**Comment by thestonefox** [comment]
It's a problem with the beta. It's been fixed in the release candidate of unity 5.4.0F1
