### ISSUE TITLE
Using repository as submodule impossible

### ISSUE THREAD

**Issue by xfleckx** [thestonefox/SteamVR_Unity_Toolkit#272]
Hy, 

create job building and providing this package for free! 

I'm experimenting with a simple custom package management for Unity3D based on git considering the huge even crowing open-source community around Unity3D and the problem of dependencies between plugins and asset packages. I try to solve that by using git submodules and getting all plugins (dll's and stuff) together by automatically download them and put them in-place before Unity starts compiling.

So it's more a general question than an issue - so I appreciate a discussion on this!

Is there a specific reason for providing your package as a standalone Unity project rather than just as a Directory which must be cloned to <MyProject>/Assets/SteamVR_Unity_Toolkit.

One drawback of the current structure is that, I don't see the opportunity to add the project as a submodule into a repository for a existing project, which would be a nice way to use the your and in general open-source asset packages and easily receive updates. 

What do you think about that?

**Comment by thestonefox** [comment]
The github repo is kind of like a play ground for the latest cutting edge version of the toolkit. So the reason it's a project is so you can quickly open it in unity.

The version that is on the Unity asset store is stable and is just the relevant folder (this one should probably be used for active projects).

The asset store link is: https://www.assetstore.unity3d.com/en/#!/content/64131

**Comment by xfleckx** [comment]
Ok I get the point... I will reference the asset package.
