### ISSUE TITLE
Teleport to navmesh perhaps too permissive

### ISSUE THREAD

**Issue by reubengann** [thestonefox/SteamVR_Unity_Toolkit#277]
Maybe it's just me, but my environments are fairly close quarters. So the line in SimplePointer for determining whether a position can be teleported to,

`validNavMeshLocation = NavMesh.SamplePosition(target.position, out hit, 1.0f, NavMesh.AllAreas);`

is perhaps too permissive. If I'm reading this correctly, it will teleport to any position that is within 1 meter of the navmesh, which in my case is inside all sorts of objects. Perhaps this could be a setting? Sorry if I'm mistaken. Thanks.

**Comment by thestonefox** [comment]
Yeah I think making it a setting is a good idea

**Comment by thestonefox** [comment]
it seems any number under 1f for maxDistance and you struggle to teleport anywhere within the nav mesh :/

**Comment by reubengann** [comment]
Weird. In my script I use

`NavMeshHit hit;
                if (NavMesh.SamplePosition(e.target.position, out hit, 0.2f, NavMesh.AllAreas))
                {
                    LookCursor.SetActive(false);
                    WalkCursor.SetActive(true);
                    sphereCursor.enabled = false;
                }
                sp.pointerMissColor = MissColor;`

This code works fine and sets the cursor correctly. I don't get why it wouldn't work for teleporting itself.

**Comment by thestonefox** [comment]
Did you try that change on the NavMesh Teleporting example scene?

When I try that I can't teleport anywhere

**Comment by Cubiverse** [comment]
Just adding in my 2 cents, I found the NavMesh to be problematic as I used off-mesh links and it caused large "holes" round static geometry (like small wooden posts in the ground)

I added functionality to the teleport system to generate a collision box (using physics.overlapBox() ) to ensure that where the user was teleporting was valid (i.e. not too close to a wall).. It means they can teleport anywhere, as long as their "head" won't hit something (or be in something)..

Code looked something like..

			Vector3 headPoint = cameraPoint + new Vector3 (0, 1.5f, 0);
			Vector3 halfExtends = new Vector3(0.25f, 0.25f, 0.25f) ;
			Collider[] allColliders = Physics.OverlapBox (headPoint, halfExtends, new Quaternion());
			if (allColliders.Length > 0)
				validNavMeshLocation = false;

**Comment by thestonefox** [comment]
Found the issue, it was using the target origin for it's source point, not the destination position

the PR for it should resolve it

**Comment by reubengann** [comment]
Great. Can't wait to try it out. Thanks so much.
