### ISSUE TITLE
RadialMenu OnHold event bug fix

### ISSUE THREAD

**Issue by mattboy64** [thestonefox/SteamVR_Unity_Toolkit#278]
RadialMenu.cs line 79.

I believe it should be:
currentPress = buttonID; 
not 
currentPress = 1;

Thanks for an amazing tool!

**Comment by thestonefox** [comment]
Good catch, fixed it https://github.com/thestonefox/SteamVR_Unity_Toolkit/commit/f9cc5f6152785cc20722187d0320132b99b0b790
