### ISSUE TITLE
InteractGrab::ThrowReleasedObject() Bug/Suggestion

### ISSUE THREAD

**Issue by mattboy64** [thestonefox/SteamVR_Unity_Toolkit#281]
This might be intentional, but in VRTK_InteractGrab.cs around line 263 it reads:

 rb.velocity = origin.**TransformDirection**...

changing it to use TransformVector instead would maintain the scale of the object and the correct worldspace velocity of the throw. The original version breaks throwing of objects if the player is shrunk or grown if that is a game mechanic (like it is in my game).

Changing it for the angular velocity (next line) seems to not be a good idea though.

Like I said, this might be a design choice, but it seems like maintaining the scale would be a good idea. Let me know if you have any questions.

**Comment by thestonefox** [comment]
It used to use TransformVector

https://github.com/thestonefox/SteamVR_Unity_Toolkit/commit/44fcb01ba0194f6b7735a3e37041fd38232b8d17

But as you can see from that commit, using TransformVector caused unwanted effects in throwing and rotation multiplication. For instance, throwing an object would magnify it's rotation so it would spin off into the distance far too fast.

The solution that was agreed up was to use TransformVector and then to increase throwing power when you've scaled up would be achieved by increasing the throw multiplier to provide the scaling power.
