### ISSUE TITLE
How to get the controllers index?

### ISSUE THREAD

**Issue by Bugzoo** [thestonefox/SteamVR_Unity_Toolkit#289]
I've been using 'e.controllerIndex == 1', but the controller indexes change every run

**Comment by thestonefox** [comment]
What do you need the index of the controller for?

**Comment by thestonefox** [comment]
FYI, the index is on the `SteamVR_TrackedObject` script

So from a controller you can do `GetComponent<SteamVR_TrackedObject>().index`

**Comment by Bugzoo** [comment]
I'm trying to make operations work on only the left controller

**Comment by thestonefox** [comment]
Look at the `DeviceFinder` helper class. it can aid you to identify which is the left and which is the right controller

**Comment by Bugzoo** [comment]
How do I use 'GetControllerHandType'?

**Comment by thestonefox** [comment]
If you use `public static ControllerHand GetControllerHand(GameObject controller)`

And pass it the controller, it will return you the ControllerHand and you can check if it's the left or right controller
