### ISSUE TITLE
[Suggestion] FPS counter

### ISSUE THREAD

**Issue by bcoyle** [thestonefox/SteamVR_Unity_Toolkit#29]
If it doesn't exist, a simple way to affix an fps counter within view to make sure a project stays under the desired fps. Or if anyone knows of an existing way that's easy to use, I'm interested in knowing about it.

**Comment by Dendane** [comment]
When you click play in Unity there is a little button on the right above the play window called stats, click it, you should see this:

![image](https://cloud.githubusercontent.com/assets/18679719/15000096/6e7e9b50-118d-11e6-925d-64f188153400.png)

**Comment by Dendane** [comment]
ps: the above screen was done without steamvr running, with steamvr running the fps climbed to 90+ fps

**Comment by SirDigbyChickenCezar** [comment]
@Dendane interesting, do you know what steamvr does to improve fps? And do you know if this is the case for other VR applications that don't strictly rely on steamvr ( e.g. Virtual Desktop)? 

I'm assuming it isn't caused by reprojection.

**Comment by Dendane** [comment]
No clue, maybe unity is capped at 60 fps in the editor, except for vr ?
I guess the only way to know the correct fps is to build the unity project first then run it with some fps utility and no background processes.
But the stats button at least gives you an indication if it will run at +90fps without having to rebuild all the time.

**Comment by thestonefox** [comment]
I wonder if Unity has an automatic vertical sync applied to it? If so then it would cap to the refresh rate of the monitor (i.e. 60Hz for a screen and 90Hz for the Headset)

**Comment by Nic-vanDessel** [comment]
Fairly certain this is not the case because I've seen unity go into the thousands of fps in-editor

NIC VAN DESSEL
(M) 720-633-2263
nvandessel.weebly.com

**Comment by thestonefox** [comment]
Then I give up :) :p

**Comment by Nic-vanDessel** [comment]
As opposed to an avg FPS counter which is already built into the editor under stats (mentioned above) how about a minimum FPS counter for keeping your fps above 60? Not too difficult if I remember correctly...

**Comment by bcoyle** [comment]
something like this, http://talesfromtherift.com/vr-fps-counter/

I now use that FPS counter in the editor. But it doesn't help when you have the headset on and you're looking at a dense section of geometry. You have to pop it off and look at the editor. Which then you might have to walk over to and lose that view you wanted to double check.

**Comment by thestonefox** [comment]
I wonder why that doesn't work on the vive?

The code seems sound enough.

I'll have a fiddle, it should be pretty easy getting that to work on the headset. I've got UI elements to appear on the headset in the past.

**Comment by thestonefox** [comment]
I've got a working version of this FPS counter now in the Vive headset.

I'll push the commit soon :)

**Comment by thestonefox** [comment]
Completed with f161a309a859b0fb9790d878b374bab31f8b080d
