### ISSUE TITLE
Touchpadpressed bool keep pressed after release

### ISSUE THREAD

**Issue by cordonezVL** [thestonefox/SteamVR_Unity_Toolkit#290]
Is reproducible in the example scene 002. Any advice how to fix it?

**Comment by thestonefox** [comment]
I'll look into a fix shortly

**Comment by cordonezVL** [comment]
I'm sorry is related with the configuration of the enums in the controller Events script(with all of them in trigger works fine). I'll keep looking into it.

**Comment by thestonefox** [comment]
Fixed with https://github.com/thestonefox/SteamVR_Unity_Toolkit/commit/9bf7506fa65df13685abd91617c37b0d95a25a33
