### ISSUE TITLE
Compile list of games/apps that use the toolkit

### ISSUE THREAD

**Issue by thestonefox** [thestonefox/SteamVR_Unity_Toolkit#291]
If you have a game or app that uses the toolkit please mention it so I can add it to the README.

So far I have:

* QuiVR: http://store.steampowered.com/app/489380/
* Left Hand Path: http://store.steampowered.com/app/488760/
* Holodaze: http://store.steampowered.com/app/475520/
* ViveSpray: http://store.steampowered.com/app/494830/

If you don't want your game on the list then lemme know! :)

**Comment by RandomApathy** [comment]
VeeR Pong: [http://store.steampowered.com/app/494850](http://store.steampowered.com/app/494850 )

**Comment by wandp** [comment]
Emergence Fractal Universe:
http://store.steampowered.com/app/500470

**Comment by CTNeptune** [comment]
Ocarina of Vive: https://tomcat94.itch.io/ocarina-of-vive-shooting-gallery

**Comment by CTNeptune** [comment]
Also: Danc<R https://tomcat94.itch.io/dancr-alpha

**Comment by stitchlips** [comment]
Tower Island: Exlpore, Discover and Disassemble
http://store.steampowered.com/app/487740/

**Comment by AndersMalmgren** [comment]
Our game is based on both NewtonVR and SteamVR_Unity_Toolkit
http://virtual-warfighter.com/

**Comment by thestonefox** [comment]
That virtual warfighter looks cool. How easy was it to work with vrtk and Newton vr in the same project? Are there many/any places where they're incompatible?

**Comment by AndersMalmgren** [comment]
Thanks man!
I based it on NewtonVR and then took the parts I liked from your lib. So I can sadly not easily pull changes from either repositories. But we have added so much custom content to the code anyway.

**Comment by dziemid** [comment]
VR Regatta is using SteamVR_Unity_Toolkit :-) http://store.steampowered.com/app/468240/

**Comment by wheatgrinder** [comment]
Car Car Crash Hands On Edition uses SteamVR_Unity_Toolkit
http://store.steampowered.com/app/472720

**Comment by Cubiverse** [comment]
Zed VR (working title) - Mostly videos for the moment - https://www.youtube.com/channel/UCjTNNUlnm-bd-3TV9Z54Rxg

**Comment by Cubiverse** [comment]
We've now an official web-site, expect a alpha demo on 16th September...

[OneOfTheLast.Com](http://oneofthelast.com) is using StreamVR_Unity_Toolkit

**Comment by thestonefox** [comment]
@JamesHunter-DeepVoodoo cool i'll add it to the list! :)

**Comment by thestonefox** [comment]
People are submitting directly now, so I can close this
