### ISSUE TITLE
Radial Menu buttons broke?

### ISSUE THREAD

**Issue by Bugzoo** [thestonefox/SteamVR_Unity_Toolkit#293]
I have multiple Radial Menus on one controller, and each time I want to switch between them I use 
`pages[0].SetActive(false)` and `pages[1].SetActive(true)`, and that works, only for the fact that everytime I change, the buttons on the previous page are not visible but they are still functional

**Comment by thestonefox** [comment]
i think because maybe the events have been registered but you're not unregistering them when you switch menu.

**Comment by Bugzoo** [comment]
How do I unregister the events?

**Comment by thestonefox** [comment]
I think the script may need an OnDisable that removes the listeners (and then have the listeners registered in the OnEnable method)

I'm on vacation at the moment so I can't take a look, maybe if @Blueteak has time he may be able to take a look?

**Comment by thestonefox** [comment]
Should be fixed with https://github.com/thestonefox/SteamVR_Unity_Toolkit/commit/cbb9e6363b068fba8b50314d355aa2a0127594fd

**Comment by clamchoda** [comment]
Seems haptic feedback does not work when radial menu is attached to both hands.

**Comment by thestonefox** [comment]
@clamchoda does it do that in the example scene?

**Comment by clamchoda** [comment]
@thestonefox Yes it does but disregard, it's nothing to do with VRTK. After a little more testing - the whole controller is dead - not just haptics :( RMA in the middle of my dang game
