### ISSUE TITLE
Wrong touching logic

### ISSUE THREAD

**Issue by stevenwanhk** [thestonefox/SteamVR_Unity_Toolkit#294]
First you need to use
 `if (collider.gameObject.GetComponent<VRTK_InteractableObject>())`
               ` {`
 `                   lastTouchedObject = collider.gameObject;`
               ` }`
                `else`
               ` {`
                    `lastTouchedObject = collider.gameObject.GetComponentInParent<VRTK_InteractableObject>().gameObject;`
               ` }`
in `OnTriggerEnter()`, otherwise it will never equal to `touchedObject` if the collider is not in the same transform with `VRTK_InteractableObject`

Second, the current lastTouchedObject logic does not work if you touch 2 items at the same time, `OnTriggerStay()` for 2 different colliders will be called every frame without calling `OnTriggerEnter()`, that's why sometimes my haptic palse keeps activating when I touch 2 InteractableObject at the same time.

**Comment by thestonefox** [comment]
You need to specify a collider on the parent otherwise the script will never trigger on the interactable object.

You cannot touch 2 objects at the same time, you can only touch 1 object and if you do touch 2 objects then it should just add the touch to the last object touched (in sequence).

**Comment by stevenwanhk** [comment]
Nope, I can have a gameObject with `VRTK_InteractableObject` script but have no collider, I have place several colliders in its child, and the code still works since some places use `GetComponentInParent<VRTK_InteractableObject>()` to find the `VRTK_InteractableObject` script. Just check your own `OnTriggerStay` in `VRTK_InteractableObject`, the problem comes from `OnTriggerEnter` was not modified such changes.

Just open your example scene "005_Controller_BasicObjectGrabbing", change `RumbleOnTouch` to X=0.05 Y=5000 for objects "Cube_HighlightOnTouch" and "Sphere_NoHightlightOnTouch". Then you put them next to each other. Use your controller and try to touch them at the same time, you will eventually find a point that your controller will activate HapticPulse like crazy.

**Comment by thestonefox** [comment]
Which version of the toolkit are you using in regards to your rumble issue?

There was a commit that prevents multiple rumbles on touch from running at the same time.

Specifically this line: 
https://github.com/thestonefox/SteamVR_Unity_Toolkit/blob/master/Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_InteractTouch.cs#L166

It only allows another rumble on the controller after the previous rumble has finished, which if you touch something new after that time then it will rumble again.

**Comment by thestonefox** [comment]
also, does this PR fix your first issue?

https://github.com/thestonefox/SteamVR_Unity_Toolkit/pull/295

**Comment by stevenwanhk** [comment]
I downloaded the latest ZIP and tested "005_Controller_BasicObjectGrabbing" with the method I mentioned above, it has the same problem.

In short, the problem is caused by touching the 2 objects at the same time will call `OnTriggerStay` for BOTH objects without calling `OnTriggerEnter`, at least I used `Debug.Log` in these 2 functions and that was what I observed. As a result, `touchedObject` and `lastTouchedObject` will always be different because `lastTouchedObject` will not be changed, causing `touchedObject = null` in `ForceStopTouching()`, and thus those codes near `TriggerHapticPulse` run

**Comment by thestonefox** [comment]
Do you want to do a Pull request for a suggested fix?

**Comment by stevenwanhk** [comment]
I am still focusing on polishing our game and do not have solution yet. Just thought if you have a quick fix.

**Comment by thestonefox** [comment]
I'm not entirely sure I can see where the problem is so unfortunately no quick fix.

From my usage of it it seems to be working as I would expect.

**Comment by stevenwanhk** [comment]
Did you try "005_Controller_BasicObjectGrabbing" like I mentioned above?

**Comment by thestonefox** [comment]
Yes, I put the two cubes next to each other and when i move my controller between them I get a rumble for the alloted time, then another rumble wont start until that rumble has finished, when i remove my controller the rumble will complete.

I cannot get the controller to rumble unexpectedly

**Comment by stevenwanhk** [comment]
Did you set `RumbleOnTouch` to X=0.05 Y=5000? The hapticPulse is very significant and non-stop. I tried 2 cubes, also has this problem.

**Comment by stevenwanhk** [comment]
Somewhere like here
![untitled](https://cloud.githubusercontent.com/assets/20297911/17054235/aef8867a-5038-11e6-838a-6ab5241b2368.png)

**Comment by stevenwanhk** [comment]
![untitled](https://cloud.githubusercontent.com/assets/20297911/17054384/700369b6-5039-11e6-80b0-d87f213e152a.png)

**Comment by stevenwanhk** [comment]
I guess moving all the codes in `OnTriggerStay` to `OnTriggerEnter` may work, any concern?

**Comment by thestonefox** [comment]
Try this updated PR

https://github.com/thestonefox/SteamVR_Unity_Toolkit/pull/295

https://github.com/thestonefox/SteamVR_Unity_Toolkit/archive/fix/interact-touch.zip

See if it works for you now

**Comment by stevenwanhk** [comment]
Seems ok. Thanks.

**Comment by thestonefox** [comment]
Shall I merge that PR then?

**Comment by smygarn** [comment]
If I recall I also could get endless loop behaviour when touching objects. (I added debug log outputs)

I think thestonefox fixed that with extra state(s)/boolean(s). Personally I always consider other solutions than booleans, but often you don't have the time..

**Comment by thestonefox** [comment]
If you can find a better solution then please raise a pr

**Comment by stevenwanhk** [comment]
Tested for a period of time. No problem so far
