### ISSUE TITLE
Disabling pointer script doesn't clean up gameobjects

### ISSUE THREAD

**Issue by aronschatz** [thestonefox/SteamVR_Unity_Toolkit#296]
I'm attempting to use both the simple pointer and the curved one in my game. When you hit the pause button, a menu pops up which means that the simple pointer is best for UI work. When you unpause, the gameplay mode using the curved pointer for teleporting.

I can enable and disable each script on the controllers, but the pointer beams stick around. I've tried adding some methods to clean them up with OnDisable, but it seems a bit deeper than that.

The need is that the script will cleanup its objects when it is being disabled. OR at least a public method to turn off the beams entirely. Right now, there's no public way to toggle the beam on/off without player interaction that I can see.

**Comment by thestonefox** [comment]
This is actually something I'm going to be looking into when I get chance, it's something I need as well.

**Comment by aronschatz** [comment]
I can attempt to hack my way through it tonight if you give me some hints. If it works, I'll do a pull request (no promises). I'm not a pro at Mono stuff, though.

**Comment by thestonefox** [comment]
Check out this pull request

https://github.com/thestonefox/SteamVR_Unity_Toolkit/pull/325

It firstly cleans up the pointers OnDisable (and recreates them OnEnable).

But also there is a new method on the pointer classes of ToggleBeam(bool state) which allows you to turn on or off the pointer manually.

**Comment by thestonefox** [comment]
Fixed with https://github.com/thestonefox/SteamVR_Unity_Toolkit/commit/ef2106f7035e87cfa5f8ca777b7949b5bd0568eb
