### ISSUE TITLE
Discussion - Should teleport not exclude all objects by default?

### ISSUE THREAD

**Issue by Cubiverse** [thestonefox/SteamVR_Unity_Toolkit#300]
In regards to real world use of teleporting in a game, is it not the case that 99% of objects should be excluded by default - with only a few floors or areas included as teleport targets?

The current teleport system seems inverted, where you must exclude the objects by attaching a script (which is time consuming and very prone to error with thousands of objects on complex levels)

I can easily inverse this in the code, and appreciate for demo scene's (and new users) it's easier to use the current method.

**Comment by thestonefox** [comment]
In your use case maybe but if it worked where you had to include objects then people would ask for it the other way round (the way it is now)

More so, people would forget to include objects and think the teleport is broke. This is why it works the way it is. I have this question many times, it's worth searching the closed issues before asking questions to save time and effort.

**Comment by Cubiverse** [comment]
Thanks for spending the time to answer, I made the code changes to suit my "way round" and will investigate the closed issues more closely
