### ISSUE TITLE
IndexOutOfRangeException in SteamVR_Controller.Input, only one Controller active in Game Mode

### ISSUE THREAD

**Issue by Bamfax** [thestonefox/SteamVR_Unity_Toolkit#305]
Hi,

first things first, thank you very much for this awesome toolkit.

Now, in the examples (tried 01-03) I am getting an IndexOutOfRangeException in SteamVR_Controller.Input. Only one controller is active in Unity game mode at a given time, even though both are on and should be ok. Using the controller on/off button on any controller in Unity game mode inactivates the active controller, pressing on button on the previously inactive controller now turns this active.

Forcing the controller active in the inspector (setting the checkmark left to its name) throws the error. The exact error is:
IndexOutOfRangeException: Array index is out of range.
SteamVR_Controller.Input (Int32 deviceIndex) (at Assets/SteamVR/Scripts/SteamVR_Controller.cs:151)
VRTK.VRTK_ControllerEvents.Update () (at Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_ControllerEvents.cs:333)

I'm on Unity 5.3.5f1. SteamVR and Firmwares are latest. VRTK is 2.0.0. I hope I missing nothing obvious here.

Thank you for your help.

Regards,
Olli

**Comment by divergenteyes** [comment]
How'd you get past this issue? I had no problems the first few launches, then suddenly I started running into this issue

**Comment by Bamfax** [comment]
That is what I experienced. I don't remember exactly what triggered it, but it was something silly. Try restarting the whole environment and/or SteamVR, something like that.
