### ISSUE TITLE
Automatically showing pointer when pointing at UI

### ISSUE THREAD

**Issue by timminkov** [thestonefox/SteamVR_Unity_Toolkit#306]
I searched through the docs and code but can't seem to find anything. Is there a way to enable the pointer whenever it's pointing at any unity canvas/UI element? Or any object in general?

Additionally, how do I hide the controller when picking up specific objects (not globally)?

Unrelated, but is there a support/community channel for the toolkit?

**Comment by thestonefox** [comment]
There is no way at present to have the pointer show up automatically, but this would potentially be a good addition.

You also at present cannot hide the controller only on specific objects, there is an outstanding issue for this feature though: https://github.com/thestonefox/SteamVR_Unity_Toolkit/issues/79

The slack community channel can be joined via: https://vrtk-slack-invite.herokuapp.com/

**Comment by thestonefox** [comment]
I've just added a pull request to allow the pointer to be manually turned on or off:

https://github.com/thestonefox/SteamVR_Unity_Toolkit/pull/325

I'm going to look to extend the UI Pointer to emit an event when the canvas is hovered over, then you'll be able to hook the two together and turn on when you hover over a canvas.

**Comment by timminkov** [comment]
Thanks @thestonefox!

**Comment by andrewbrooke** [comment]
> I'm going to look to extend the UI Pointer to emit an event when the canvas is hovered over, then you'll be able to hook the two together and turn on when you hover over a canvas.

Was this feature ever implemented?

**Comment by thestonefox** [comment]
UIPointer has an enter/exit event

https://github.com/thestonefox/VRTK/blob/master/Assets/VRTK/Scripts/UI/VRTK_UIPointer.cs#L133-L140
