### ISSUE TITLE
With Unity 5.4.0f3 Bow, and exmample, don't work right

### ISSUE THREAD

**Issue by Rizzen1998** [thestonefox/SteamVR_Unity_Toolkit#308]
As of today, with either the latest SteamVR or with Unity 5.4.0f3, the bow disappears when you attach an arrow to it.   The arrow also no longer draws backwards.

**Comment by thestonefox** [comment]
Is anyone else having this issue?

**Comment by thestonefox** [comment]
I tried this just and it seems to be working fine for me.

May be worth checking out a new version of the toolkit and re-importing steamVR into a clean build.
