### ISSUE TITLE
UIPointer - Issues with canvas attached to controller

### ISSUE THREAD

**Issue by Cubiverse** [thestonefox/SteamVR_Unity_Toolkit#309]
This is more for the information of others who will have canvas's attached to their controllers (for example, ammo read outs on guns or health bars on controllers).

If using the UI Pointer it grabs all the world canvas and adjusts them to suit it's needs, when it grabs one (or more) canvas's on the controller it causes the rotation logic to be wrong (I'm not sure why it's wrong but, for example, my gun seems to be hitting something on certain axis causing it to be bend at an odd angle).

My solution was to simply add a tag called "IgnoredByPointer", set this on all controller attached canvas's and have the SetWorldCanvas do a quick check:

        public static void SetWorldCanvas(Canvas canvas)
        {
            if (canvas.renderMode != RenderMode.WorldSpace)
            {
                return;
            }

			if (canvas.gameObject.CompareTag ("IgnoredByPointer"))
				return;

**Comment by thestonefox** [comment]
I think this would be good to have as an additional propery on the UIPointer, something like "ExcludeTagOrClass" and it would work similar to how the teleport exclusion works.

**Comment by Cubiverse** [comment]
Yeah, probably a good idea to keep them similar..

At the moment most of these sorts of issues are "corner" cases (given they are sometimes specific to usage) but I suspect as more and more use the toolkit for real world games these scenario's will pop-up!

**Comment by thestonefox** [comment]
Keep this open as a reminder for me to do the work on the exclusions :)

**Comment by thestonefox** [comment]
PR to fix this issue at: https://github.com/thestonefox/SteamVR_Unity_Toolkit/pull/359
