### ISSUE TITLE
On multiple material objects, highlight on touch only changes the first material colour.

### ISSUE THREAD

**Issue by arkhint** [thestonefox/SteamVR_Unity_Toolkit#310]
This makes it difficult for the player to notice, if the first material is a small accent piece which isn't largely visible.

Ideally, the option to choose a single material #, or all material to highlight would be ideal. 

However, 'all material' would be a better default than the current.

Sample project with a dual material asset: https://dl.dropboxusercontent.com/u/85141892/Sample_Highlight_On_Multiple_Material.rar

**Comment by thestonefox** [comment]
Check out this PR, does it fix your problem?

https://github.com/thestonefox/SteamVR_Unity_Toolkit/pull/356

**Comment by arkhint** [comment]
That seems to work for all material on the object now. Thanks !
