### ISSUE TITLE
Disabling the InteractableObject script in the editor doesn't disable it.

### ISSUE THREAD

**Issue by arkhint** [thestonefox/SteamVR_Unity_Toolkit#311]
http://i.imgur.com/wg3swN1.gifv

E.g. 
Add interactableObject script to an object. 
'Untick' it to disable.
Hit run.
The object is still interactable. 

Tested in the stock VRTK sample scene..

**Comment by 10FingerArmy** [comment]
Are you on the latest version? This issue should be fixed.

**Comment by arkhint** [comment]
Ah I was using the latest version from the asset store (which had the issue). The latest here works, and is indeed fixed. 

Thanks !
