### ISSUE TITLE
Object is not properly grabbed in Network Scenario (Grab Precognition).

### ISSUE THREAD

**Issue by spaggi** [thestonefox/SteamVR_Unity_Toolkit#319]
I am currently implementing a simple VR multiplayer game using VRTK. Please note that I am not an expert in networking, this is my first attempt to do something like this.

What I do is that I simulate Rigidbodies with phyiscs for 2 players. Player 1 is the one that does the physics calculations and transfers the position and velocity information to player 2. So the Rigidbody is non-Kinematic for Player 1 and Kinematic for Player 2.

Now, Player 2 should be able to grab the Rigidbody. For reasons I do not really understand, there is some slight delay when grabbing, so when the object is falling fast, he was not able to catch it. What I did is to increase the parameter "Grab Precognition" to 10 and he can now grab it very well.

BUT what happens now is that the object is not properly attached to the controller, but has offset in position and rotation. I am using the "Child of Controller" Grabtype with no handles.

Showing the offset in the Scene editor
https://i.imgur.com/qbAJaZ4.png

The Child Obejct has offset to the parent
https://i.imgur.com/8YvCfDk.png

If I remove the Child offstet and rotation during the game, everything is fine.

The more I think of it, the more I believe this has to do with the Grab Precognition.

**Comment by thestonefox** [comment]
Any chance you could whip up an example project so i can test it locally and see the issue?
