### ISSUE TITLE
It's not obious that the VR Toolkit in the Unity Asset store is an official output of this project

### ISSUE THREAD

**Issue by kaze0** [thestonefox/SteamVR_Unity_Toolkit#320]
Asset store link: https://www.assetstore.unity3d.com/en/#!/content/64131

Is the Unity Asset store asset, an official representation of this repo?

**Comment by thestonefox** [comment]
Ok. for the next version I put on the Asset store, I'll make it clearer that it's the official stable release of this github branch.

But rest assured it is the same stuff :)
