### ISSUE TITLE
Pointer Interact / Trigger

### ISSUE THREAD

**Issue by B33T** [thestonefox/SteamVR_Unity_Toolkit#33]
Firstly i am just learning unity, so your library is a great help and i have used it to create some fun things and learn how to use vr and how to use unity.

Could you possibly add a script that enables the pointer to interact with objects, for example enable the pointer to point at an object and trigger something then this could be used to interact with menus etc (like in Whirligig the menu system is really good). 
For example
You point to a box and pull the "trigger" this then makes the box run a script/react etc.

**Comment by thestonefox** [comment]
It wouldn't be too hard to make the pointer affect an object. When the pointer touches something and the pointer button is released an event is thrown called "DestinationSet"

Which contains the target that the pointer was hitting. If you had something in the scene listening for this DestinationSet, then got the target in the listener code, you'd be able to call it's use function.

I've done a similar thing in a menu system for something I was messing around with.

I'll have a think about how this could be implemented in an example scene, my current implementation is very hacky.

**Comment by thestonefox** [comment]
Completed with 227c58b220bdd446502c4f51c563521985f9fdba
