### ISSUE TITLE
Re-implement Interact Touch collider

### ISSUE THREAD

**Issue by thestonefox** [thestonefox/SteamVR_Unity_Toolkit#334]
At present the interact touch collider is a basic sphere but this is really rudimentary and doesn't fit many use cases nor custom controllers.

The Interact Touch script doesn't need a collider on it, it only needs a rigidbody and then any child game objects with trigger colliders will be used for the touch script's trigger requirement.

**Comment by smygarn** [comment]
Great! I think that's much more important than cool new features ;)
