### ISSUE TITLE
SteamVR_InteractableObject run script

### ISSUE THREAD

**Issue by B33T** [thestonefox/SteamVR_Unity_Toolkit#34]
You could make it so that when you check things like "is Grabbable" it enables you to pick a textbox with a script that it runs when grabbed, the same could be applied to onuse etc
Not hugely fluent in unity so forgive me if this is a silly idea / notion

**Comment by thestonefox** [comment]
If you have an interactable object, you can write your own script that extends that class, which then calls the startGrabbing or startUsing method of your custom code.

Look at the Gun class in the examples scripts to see if that's what you mean,
