### ISSUE TITLE
SteamVR Unity Toolkit an Networking VR?

### ISSUE THREAD

**Issue by Vytek** [thestonefox/SteamVR_Unity_Toolkit#340]
It is possible to add a very important feature: Networking VR??

A superb Network Library like DarkRift (https://www.assetstore.unity3d.com/en/#!/content/16711) is free for 20 users !! The developer is writing the new core that is opens source: https://github.com/DarkRiftNetworking/Hazel-Networking
(for info: http://forum.unity3d.com/threads/darkrift-networking-2-the-next-level-of-networking.380800/page-2)

Please add Networking VR,  I dream the Metaverse!!
Your framework is awesome!!

Also only a tutorial or an example: Is it complex? How to integrate this features?

**Comment by thestonefox** [comment]
Quite a few people have been using PhotonPUN with VRTK (and also PhotonBolt) they seem to be having relative success.

**Comment by Vytek** [comment]
Any examples? Tutorial? Thanks...

**Comment by thacio** [comment]
Multiplayer for VR is just the same as normal multiplayer. You can start learning through Photon tutorials.https://doc.photonengine.com/en/pun/current/tutorials/photon-unity-and-networking-links

The hands and headset position of other network players are synchronized just like any other game object (by sending their transform info).
