### ISSUE TITLE
HeightAdjustTeleport on Single Object Ramps

### ISSUE THREAD

**Issue by mattboy64** [thestonefox/SteamVR_Unity_Toolkit#344]
If you make a simple ramp with a primitive, the height adjust teleport code won't move you up or down the ramp. It appears the reason is due to the VRTK_HeightAdjustTeleport.cs DropToNearestFloor() function. On around line 123 it queries:
                if (rayHit && ValidLocation(rayCollidedWith.transform) && !FloorIsGrabbedObject(rayCollidedWith) && (MeshYChanged(rayCollidedWith, floorY) || CurrentFloorChanged(rayCollidedWith)))

The CurrentFloorChange won't allow an adjustment unless it's a different object. 

I'm not sure why this limitation is in place. It seems a generic YChanged() type function should fix the issue. I don't know the reason for the limitation, but if jittering is a concern, perhaps a min Y change amount would work instead. 

This also breaks my falling code :cry:

**Comment by thestonefox** [comment]
yeah i think you may be right a YChanged may be better. I'll have a play and see.

**Comment by thestonefox** [comment]
I don't think Y Changed will work, because if you stand on a surface and you simply crouch down then the Y will change and you will teleport. That must be why i'm checking for the same surface.

**Comment by mattboy64** [comment]
yeah maybe. Seems to work on the meshes though, I wonder what's different about those.

**Comment by thestonefox** [comment]
On Meshes, the teleporter works incrementally and just doesn't do the blink fade

https://github.com/thestonefox/SteamVR_Unity_Toolkit/blob/master/Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_HeightAdjustTeleport.cs#L89


So...... maybe have it ignore the object change, but blink fade (if active) will only happen if the Y threshold has changed by enough of a margin? That could work?

**Comment by mattboy64** [comment]
I think you pass in if you want to blink fade, I don't think that particular section will do one so I _think_ it would be fine, just like if it's over a mesh.

**Comment by thestonefox** [comment]
I think I have a working solution where you can specify the Blink Y Threshold. Setting it to 0 means any time the Y changes then the headset blinks (but not if you're crouching because the Y takes your headset position into consideration)

I'll PR it in a mo and you can see if it sorts your stuff out
