### ISSUE TITLE
Tools for interaction: Hide Controller On Grab and Use Only If Grabbed

### ISSUE THREAD

**Issue by gpvigano** [thestonefox/SteamVR_Unity_Toolkit#346]
I'm working on a script to extend `VRTK_InteractableObject` for the interaction with other objects (should I put the scrpt in `Script/Tools/VRTK_Tool.cs`?), along with some animation and sound effects.
Here you can see the example scene developed to test this feature (not yet ready for a PR):
![vrtk_2016-08-03 13-31-45-13](https://cloud.githubusercontent.com/assets/20297129/17364576/38a575a8-5981-11e6-9615-ad2200a561fa.gif)
![vrtk_tools_inspector](https://cloud.githubusercontent.com/assets/20297129/17365366/26c131ba-5986-11e6-8b08-8de694bea5bd.png)

Two main issues arose with this work, the first one regards **hiding the controller on grab only for some objects**, the second one **preventing an object to be used if not grabbed**.

### Hiding the controller on grab only for some objects (Hide Controller On Grab)
There are different types of objects, those that does fit into the controller shape (e.g. drills, electrical screwdrivers, light sabers...), and those that don't fit (e.g. large tools or simple movable objects), according to the correlation between the controller to the virtual object shape (and buttons).
In each of these types the controller is expected to be hidden (objects that fit) or not (objects that don't fit).

Why don't move Hide Controller On Grab (`hideControllerOnGrab`) from Grabbing Interactable Object (`VRTK_InteractGrab`) to Interactable Object (`VRTK_InteractableObject`)?
For example in `VRTK_InteractGrab` this could coded like this:

```
var grabbedObjectScript = grabbedObject.GetComponent<VRTK_InteractableObject>();
...
hideControllerOnGrab = grabbedObjectScript.hideControllerOnGrab;
```
Another chance is to define the default behaviour for the controller and let the grabbed object override this if a specific behaviour is defined:
```
var grabbedObjectScript = grabbedObject.GetComponent<VRTK_InteractableObject>();
...
var grabbedToolScript = grabbedObjectScript as VRTK_Tool;
if (grabbedToolScript!=null) hideControllerOnGrab = grabbedToolScript.hideControllerOnGrab;
```

This let the controller (the `VRTK_InteractGrab` script) check if the grabbed object is a tool, in that case the flag "Hide Controller On Grab" of the tool would be used instead of the one of `VRTK_InteractGrab` (with this last solution should I use the same name `hideControllerOnGrab` as in `VRTK_InteractGrab`?).

### Preventing an object to be used if not grabbed (Use Only If Grabbed).
This is a feature required by many real tools (you should not use a drill if you didn't grab it).
I think this is more a generic feature, so I'd put it into `VRTK_InteractableObject` rather than in the tool script (e.g. `VRTK_Tool`).
For example put in DoStartUseObject() (in VRTK_InteractUse):
```
VRTK_InteractableObject vrobj = touchedObject.GetComponent<VRTK_InteractableObject>();
if (vrobj.useOnlyIfGrabbed && !vrobj.IsGrabbed()) return;
```

**Comment by thestonefox** [comment]
There's already an issue raised for overriding hide controller on certain objects:

https://github.com/thestonefox/SteamVR_Unity_Toolkit/issues/79

So I'd say your solution shouldn't be an extension into your own thing, make it part of the Interactable Object as this should be a core feature.

Also, same for `Use only If Grabbed` make this a core feature as it's useful for everyone.

That should answer the original question of where to put the extended file :) don't put it anywhere and just do the work on the interactable object :)

**Comment by gpvigano** [comment]
> There's already an issue

Yes, I missed that issue, now I read it and proposed another option.

> where to put the extended file :) don't put it anywhere and just do the work on the interactable object :)

I can apply the 2 changes (Hide Controller On Grab and Use Only If Grabbed) to VRTK_InteractableObject, but what about animations sounds and so on? Shuld I put everything into VRTK_InteractableObject.cs?

In the Inspector we will find a very long list of features, even if not used. This is related to the issue #60. By the way, am I missing some work already in progress for this topic?

Anyway I arranged things to let the script use a feature only if the corresponding item is set. For example a scaling is applied only if the related Transform is set in the Inspector.
With this structure an option could be to write an Editor script devoted to make each section disappear if the related target is not set (e.g. if no Transfom is set for scaling do not display scaling values, etc.).

**Comment by thestonefox** [comment]
If you're making an example with animations and sounds then put the script inside `Examples/Resources/Scripts`

I wouldn't suggest having animations and sound effects as a default core feature.

You're right about the crazy long list of params. I think this can be resolved with a custom inspector and put things into foldouts and hiding things as you say.

I keep meaning to get round to looking into how custom inspectors work and writing it. So if that's something you want to take a look at as well then that would be great!

**Comment by gpvigano** [comment]
Got it!
Anyway I will think about the inspector later, I'm going to work on the VRTK_InteractableObject script now.

**Comment by thestonefox** [comment]
Cool :)

Yeah the inspector is one of those things that probably needs doing, just never has the time for the love and attention it deserves :)

**Comment by gpvigano** [comment]
I need to add also two options in VRTK_InteractableObject to disable the teleport when grabbing or using an object:
```
        public bool disableTeleportOnGrab = false;
        public bool disableTeleportOnUse = false;
```
what do you think about it?
In case you agree with this change should I add it to the same PR where I put "Hide Controller On Grab and Use Only If Grabbed"?

**Comment by gpvigano** [comment]
I started with this PR #348, the example with sounds and animation will come with another PR.

**Comment by thestonefox** [comment]
fixed https://github.com/thestonefox/SteamVR_Unity_Toolkit/pull/348
