### ISSUE TITLE
VRTK_InteractGrab Precognition Bug/Fix

### ISSUE THREAD

**Issue by mattboy64** [thestonefox/SteamVR_Unity_Toolkit#349]
In VRTK_InteractGrab::Update() the grabPrecognitionTimer continuously grabs until the timer ends. If you grab and release before the timer ends however, it will not let go and the object will be stuck to your hand.

Proposed Solution:
Disable the timer after we've successfully grabbed an object.

Change:
```
if (grabPrecognitionTimer > 0)
            {
                grabPrecognitionTimer--;
                if (GetGrabbableObject() != null)
                {
                    AttemptGrabObject();
                }
            }
```

To:
```
if (grabPrecognitionTimer > 0)
            {
                grabPrecognitionTimer--;
                if (GetGrabbableObject() != null)
                {
                    AttemptGrabObject();

                    if (GetGrabbedObject() != null)
                    {
                        grabPrecognitionTimer = 0;
                    }
                }
            } 
```

**Comment by thestonefox** [comment]
You want to do a PR for it, or want me to do a fix? I'm happy either way

**Comment by mattboy64** [comment]
I figured it would be easier for you to just make the change

**Comment by thestonefox** [comment]
Cool i'll take a look now

**Comment by thestonefox** [comment]
I can't get it to stick to my hand. Your issue and solution look legit and make sense. But how do i recreate it?

I set the grab precognition to 20, i throw, catch, drop, but it drops as i expect

**Comment by mattboy64** [comment]
precognition is frame based and not timing based (something I want to change at some point). Setting it to 180 should get you 2 seconds of grace time.

**Comment by thestonefox** [comment]
Lol I'm a noob I'll make it timing based too :)

**Comment by mattboy64** [comment]
Sweet!

**Comment by thestonefox** [comment]
fixed with https://github.com/thestonefox/SteamVR_Unity_Toolkit/commit/b43b66b44e7696fbb7fb0c1c0ba34b24d38a5263
