### ISSUE TITLE
Question about Teleporting and imported meshes

### ISSUE THREAD

**Issue by pfschuyler** [thestonefox/SteamVR_Unity_Toolkit#35]
Thanks very much for these great tutorials and scripts.  I've gone through them and this is a great 1st start into using Unity with Steam VR (for a beginner).  I noticed that your terrain teleport script had the same teleport style as shown in Valve's "the Lab" (someone on Youtube had asked for this).   I've got teleporting working fine with the Unity Terrain and simple teleporting for other scenarios, but do you know how to maintain relative height off of an imported mesh?  I noticed that the terrain sample scene you provided had a terrain collider on the terrain object.  But how can this be achieved with any imported mesh?  Mesh collider doesn't seem to work for that.  But what I'd like to do is import a real-world terrain and have the teleporting work as expected on these imported terrains (which are actually meshes).   This would allow me to import elaborate terrain meshes, and then walk and teleport around on them....

**Comment by thestonefox** [comment]
The HeightAdjust Teleporter in this toolkit supports terrain colliders, but it doesn't support mesh colliders (at the moment)

So if you've imported your terrain from a 3rd party tool it probably has a mesh collider on it.

I will get round to looking at supporting mesh colliders soon! there is an open ticket for it:

https://github.com/thestonefox/SteamVR_Unity_Toolkit/issues/16

**Comment by pfschuyler** [comment]
Thanks.  Yes the files I'm importing (dae, 3ds, skp) have the option to "generate colliders" which I always check off when importing a 3d model asset.  The Unity interface doesn't specify what type of Collider that is, but I assumed that they were mesh colliders.  I've also tried mesh colliders independently.  And I think,  terrain colliders are only useful with Unity terrain objects...?  Thanks for your work.  This feature would be really useful, because it would be the missing piece that would allow me to import any cad model, and very quickly be teleporting around that in VR.  (amazing times!)

**Comment by thestonefox** [comment]
Yeah I really need to look into mesh colliders. Hopefully I'll get chance over the weekend.

**Comment by thestonefox** [comment]
I'm going to close this and point to the main ticket surrounding teleporting over meshes:

https://github.com/thestonefox/SteamVR_Unity_Toolkit/issues/16
