### ISSUE TITLE
ControllerTooltips.prefab is broken

### ISSUE THREAD

**Issue by rob100** [thestonefox/SteamVR_Unity_Toolkit#363]
The ControllerTooltips.prefab is broken at the moment. Unity cannot find the script reference. I think the reason for this is the commit e5680846279229360ca7a3dc3e0f827f314f8205 (move helper scripts to helper directory)

**Comment by thestonefox** [comment]
Does it still work in the example scene? But just doesn't work when you pull it in to a new scene?

**Comment by rob100** [comment]
Yes exactly, The example 029_Controller_Tooltips works fine. Perhaps I did something wrong?

**Comment by thestonefox** [comment]
I've just had 2 independent confirmations that it's working as expected for others using the latest version of the toolkit.

I've not been able to check myself yet. Do you have the latest version from github?

**Comment by rob100** [comment]
I am sorry, the problem was on my side. I don't know how, but in my project the guid of the scripts changed, so the prefab was broken.
