### ISSUE TITLE
How to spin an object?

### ISSUE THREAD

**Issue by mikerz** [thestonefox/SteamVR_Unity_Toolkit#366]
I've gone through all of the examples.

I initially figured that my best bet would be to subclass the VRTK interactable object, and override some of the default grab and update behavior, but that's not really working out -- I don't want to mess with the private methods, and I'm fighting too much default behavior.

My intended use case could be exemplified with a globe that you can spin around on an axis. I want the object to stay in the same position throughout. The initial collision point with the object should be the point which tracks to the controller (but will only affect rotation). When I let go of the object, it should continue spinning according to how quickly I was moving when I let go, and slow down until it comes to a complete stop.

Is there a recommended VRTK route for this problem? I'd like to integrate with the event system at minimum. Should I try doing this with an interactable object, or a totally custom route?

Thanks

**Comment by thestonefox** [comment]
You could try an interactable object with a hinge joint at the top (or bottom) of the sphere and set it's Grab Attach Mechanic to Rotator_Track.

That may work.

**Comment by mikerz** [comment]
Thanks, working with hinges was the key. That was much simpler than I imagined!
