### ISSUE TITLE
In-Editor slowdown in Unity 5.3 (5.3.3f1) with SteamVR Unity prefabs

### ISSUE THREAD

**Issue by daveyj** [thestonefox/SteamVR_Unity_Toolkit#37]
Using the modified Steam VR / Unity Toolkit [CameraRig] causes in-editor slowdown and lagginess in even the most basic scenes as compared to standard Steam VR (from asset store). 

ps: work so far is great :)

**Comment by thestonefox** [comment]
What happens when you open the TestThrow scene in the SteamVR plugin?

Does that cause the same slowdown? The CameraRig prefab in this toolkit is lifted straight from that example.

Also, I experience no difference in performance between the two locally.

**Comment by daveyj** [comment]
The TestThrow scene is fine, as are the example scene you supply. It's only when I create a blank scene and plop the CameraRig prefab down that it becomes 'sticky'. Am going to try upgrading to 5.3.4 to see if that fixes the issues.

**Comment by thestonefox** [comment]
I'm on 5.3.4f1

Apparently the new version of SteamVR 1.0.9 has a bunch of stability fixes and improved performance on 5.4 as well. Hopefully I'll get the upgrade done in this repo today!

If they're going to actively maintain the SteamVR plugin, I may separate out the required plugin from this repo as it is dirty to have it in here!

**Comment by daveyj** [comment]
Thanks @thestonefox , I'll run some tests in the newest 5.3 branch of Unity and see if I can't diagnose the issue!
