### ISSUE TITLE
tooltips visible when controller is hidden on grab

### ISSUE THREAD

**Issue by gregdowning** [thestonefox/SteamVR_Unity_Toolkit#378]
If you check the hide controler on grab option for the controller and you are using tooltips on the controllers you only see the tooltips when you grab an object. I think most toolkit users would expect the tooltip to inherit the hide function from the controller on grab or an option to hide the tooltip on grab.

**Comment by thestonefox** [comment]
I wonder if a "HideController" / "ShowController" event should be thrown then you could manage this but also would be useful for other things to know when the controller is visible or hidden perhaps
