### ISSUE TITLE
Teleporter not blinking

### ISSUE THREAD

**Issue by jamcar23** [thestonefox/SteamVR_Unity_Toolkit#39]
Is there something else you have to do besides dragging the pointer to the controller and the base teleporter to the camera rig in order for blink to work? I've tried adding SteamVR_Fade to the camera rig and tried change the amount of time for fading but neither worked.

**Comment by thestonefox** [comment]
Which version of the Prefab are you using? The one included in the Prefabs folder of this toolkit or the one in the Prefabs folder in the SteamVR plugin?

If it's the one in the SteamVR plugin then you need to put the SteamVR_Fade script on the [CameraRig]->Camera (head)->Camera (eye) object

**Comment by jamcar23** [comment]
Wow, I can't believe I didn't think of that. On a side note, adding the fade script to the eyes also fixed a head elevation issue I was having. Thanks for the help and library!

**Comment by thestonefox** [comment]
I should probably add that script component automatically to the object, I was lazy to start with and just auto put stuff on the prefab :)

Glad it's working for you now!
