### ISSUE TITLE
Dynamic FOV for natural motion

### ISSUE THREAD

**Issue by HyppoNymous** [thestonefox/SteamVR_Unity_Toolkit#390]
I add a textured plane in front of the VR camera as child object in the hierarchy , to bring dynamic FOV and try it with linear motion instead of teleport.
**https://www.youtube.com/watch?v=lHzCmfuJYa4**
The child plane doesn't stay in front of the camera when we look anywhere, what could i do ?

**Comment by AndersMalmgren** [comment]
Use the standard asset camera effect,  works for our game
