### ISSUE TITLE
Rumble examples currently not working

### ISSUE THREAD

**Issue by borrowedLadder** [thestonefox/SteamVR_Unity_Toolkit#40]
Example scene 016_Controller_HapticRumble doesn't seem to be working in Unity, no rumble detected

**Comment by thestonefox** [comment]
What version of Unity are you using and what version of the SteamVR Unity Plugin are you using?

**Comment by thestonefox** [comment]
I can confirm it's working for me in Unity 5.3.41f and SteamVR Plugin 1.0.9.

You have to swing the sword with a certain level of force against the boxes to make it rumble, just tapping them won't cause enough force to initiate the rumble.

You also need to make sure the "SteamVR_Controller_Actions" script is attached to the controller objects within the "CameraRig"
