### ISSUE TITLE
Climbing example and camera collision

### ISSUE THREAD

**Issue by HyppoNymous** [thestonefox/SteamVR_Unity_Toolkit#407]
Using the climbing example, the head camera can go throught walls or objects we climb, it results we see a black screen and we are stuck in the game.
How to get the camera not passing throught walls ?

**Comment by thestonefox** [comment]
If you put your head into a wall whilst climbing and release it "should" move your head back to the last good position so you don't fall inside a wall. Are you testing on the latest version of the toolkit?

**Comment by HyppoNymous** [comment]
I use latest version.
I was asking for a rigid body usage like the example "17-trackpad moving", so we could never enter meshes moving our head because of collision. If we move hour head inside a mesh, the camera keep the actual valid position of the physic object that doesn't enter in the mesh.

**Comment by thestonefox** [comment]
Oh right, where you physically get pushed away from the wall if you try and put your head in it?

**Comment by HyppoNymous** [comment]
If the head camera is child of a sphere rigidbody , and the sphere is moved by headset movement,  the sphere can't go into the wall whatever the movement of the headset because it is a rigidbody.
Only have the camera never go throught walls or 3D collision objects.

**Comment by xEvoGx** [comment]
Actually this is still an issue. I'd rather we not _forget it_ unless you found a suitable solution @HyppoNymous ?
