### ISSUE TITLE
RigidBody for character ? 

### ISSUE THREAD

**Issue by HyppoNymous** [thestonefox/SteamVR_Unity_Toolkit#408]
Actually VR system don't use a physic object to jump, move or interact with environment.
What about having some alternative module or script using a capsule for character movement, jump, fall and collision interaction with the environment ?
The rigidbody would not be displayed as a mesh on screen and would not collide with camera or VR controllers.

**Comment by thestonefox** [comment]
I'm not sure I fully understand this issue, could you elaborate further?

**Comment by smygarn** [comment]
I think he means more like the FinalIK's character controller and corresponding behaviour to the environment and physical objects. It's quickly getting complicated but it's cool to be able to stand on a moving platform for example..

**Comment by HyppoNymous** [comment]
I mean like touchpad walking where we use a rigid body to walk and collision with environment.
For head camera we could attach another sphere Rigid Body to prevent entering in 3D meshes.
Depending on what game you do and how you design it, you can need these rigid body collision.

**Comment by thestonefox** [comment]
This already exists, the VRTK_PlayerPresence script does this
