### ISSUE TITLE
Disabling "enable teleport" on Bezierpointer at runtime will still show bezier curve

### ISSUE THREAD

**Issue by 10FingerArmy** [thestonefox/SteamVR_Unity_Toolkit#409]
If enable teleport is disabled then also the curve should not be shown anymore

**Comment by thestonefox** [comment]
Enable teleport just prevents the event from being emitted, the beam is still correct to be shown at this point. If you don't want the beam to be shown, then it's best to disable the script ,which in turn would disable the teleport function anyway.

**Comment by 10FingerArmy** [comment]
valid point! works like you said.
