### ISSUE TITLE
How do I make/use a button?

### ISSUE THREAD

**Issue by Thundercleez** [thestonefox/SteamVR_Unity_Toolkit#410]
There don't seem to be any button samples in the example scenes and I can't seem to get a button to work at all. I've added the VRTK_Button and VRTK_Interactable_Object scripts to my button and VRTK_Interact_Touch, VRTK_Controller_Actions, and VRTK_Controller_Events to each of my controllers. A script then sets the button callback on scene load. But when I hit my button, it's not depressed and the callback is never called. The touch highlighting does work though.

**Comment by 10FingerArmy** [comment]
Is maybe scene 025 the example scene you are looking for?

**Comment by thestonefox** [comment]
Also, don't forget you need to press a button with another rigidbody object, so if you want to press with the controller, you need "Create Rigidbody when not touching" on the Interact Grab script so your controller gets a rigidbody when you press the grip button when not touching anything.

**Comment by Thundercleez** [comment]
Thanks, I didn't realize the controls scene (25) had a button example in it. Also had to add VRTK_Interact_Grab to the controllers. Seems to work now, though it'd be preferable to not have to hold the grip button to push a button. I tried unchecking the "hold button to use" property on the button, but I still had to press grip.
