### ISSUE TITLE
Press Trigger. Start Function.

### ISSUE THREAD

**Issue by cinematixx** [thestonefox/SteamVR_Unity_Toolkit#416]
Hello,

I'm very new to all this but first of all: Thank you for publishing this Toolkit. It is simply incredible :-)

Now to my problem:
I created a circle that highlights when the controller touches it. What i'd like to do now is that when i press the trigger on the controller, while touching the circle, a function should start. For example create a cube above the circle that looks like an infobox with text on it.
On a second trigger press the cube should disappear.

Please help. I'm lost :-D

**Comment by thestonefox** [comment]
If you make a new script for your objects that you're touching and make that script extend `VRTK_InteractableObject` you can then override the `StartUsing()` method. This method gets executed when you are touching an interactable object and press the using button on the controller.

Take a look at some of the example scenes with the guns in them (and the gun script) for further examples of how to do this.
