### ISSUE TITLE
Custom texture or color inside meshes

### ISSUE THREAD

**Issue by HyppoNymous** [thestonefox/SteamVR_Unity_Toolkit#417]
When the head camera is going into a 3D mesh object, the actual color is black.
How can we change the color or draw some texture pattern like horizontal red lines ?

**Comment by thestonefox** [comment]
At the moment, the fade to black is done by the headset collision fade script.  You can change the colour that it fades to, but I'm not sure if you can provide a texture as it just uses the SteamVR_Fade script which only takes a colour property.

**Comment by HyppoNymous** [comment]
I seen some special effect in the game Raw Data, it was some sort of blue background with red lines drawing. It was pretty neat effect because it suggestes pretty well to the player the camera is inside a mesh, instead of a black screen that can look like a game bug instead.

**Comment by thestonefox** [comment]
Related to https://github.com/thestonefox/SteamVR_Unity_Toolkit/issues/436
