### ISSUE TITLE
Can't teleport outside of a mesh ? 

### ISSUE THREAD

**Issue by HyppoNymous** [thestonefox/SteamVR_Unity_Toolkit#418]
If i teleport near a wall, sometimes i can teleport middle inside the wall mesh, the view is black and it seems from inside i can't no more teleport outside , so the player is stuck.
How to avoid this situation ?

**Comment by thestonefox** [comment]
Yeah this is an issue when your head is stuck in a wall and the headset collision fade kicks in it prevents you from teleporting (to stop cheating) but it's not very good and is going to be rewritten soon

**Comment by HyppoNymous** [comment]
In Vanishing Realms game, when you stay inside a mesh 1 second , it fades screen and teleports you near outside of the mesh on a good position.

**Comment by thestonefox** [comment]
that will be possible when the headset collision stuff is re-written

**Comment by thestonefox** [comment]
Related to https://github.com/thestonefox/SteamVR_Unity_Toolkit/issues/436
