### ISSUE TITLE
Radial Menu : bad button pressed detected

### ISSUE THREAD

**Issue by lepoup** [thestonefox/SteamVR_Unity_Toolkit#420]
With the radial menu, if you press the touchpad, a button pressed is detected even if touchpad is not touched,
Your question : how to press touchpad without touching it ?
Answer : press touchpad on the border, use your nails.
This kind of bad pressing happens a lot with long nails peoples.

**Comment by thestonefox** [comment]
Are you saying the radial button press is happening when you touch the touchpad?

Touchpad touch is a valid event on the SteamVR controllers.

But the actual button press is done on the Touchpad click event, which means you need to press the button down:

https://github.com/thestonefox/SteamVR_Unity_Toolkit/blob/master/Assets/SteamVR_Unity_Toolkit/Scripts/Controls/2D/RadialMenuController.cs#L98

If you're able to create a click event on your controller by pressing an area with your nails then that sounds more like a hardware problem with the controller than a bug in the code.

**Comment by lepoup** [comment]
The radial button press is happening when I press the touchpad without a valid position on it.
A click event is detected and I can see the round position dummy on the center of the touchpad until I release it.
I have verified it with 4 controllers.
Nothing is happening when you press the touchpad with nail on your side ?

**Comment by lepoup** [comment]
Fixed ! Maybe by another bug fix ? I don't know. There is no more false position on press :)
