### ISSUE TITLE
PanelUIController Component (for review)

### ISSUE THREAD

**Issue by WildStyle69** [thestonefox/SteamVR_Unity_Toolkit#422]
I've been working on a component for my project, that gives you the ability to easily access context settings for an VRTK_InteractableObject, via a UI panel. Idea is that when you pick up the object, if the UI controller and related sub-panel components are available, then you can access / open / manipulate the UI via the Vive touch-pad.

The core of what makes it useful I suppose if the mechanism for open / closing the panels and events and swipe interactions that you can handle at the UI level, to make the UI behave as you would like. A good portion of the code and design patterns I've adapted from VRTK, although its not really optimized yet.

I've created a quick demo video, which is pretty pants... however hopefully you can see enough to understand how it works.

https://www.dropbox.com/s/yvs8qxlh5s3fvzn/GB-PanelControllerUIComponent-Demo-19-August-2016-1.flv?dl=0

Let me know if you think its useful, then perhaps we can collaborate to evolve it into something that's good enough for VRTK.

**Comment by HyppoNymous** [comment]
You could resize the spray can red tip to define the opacity or change it's color. Or attach a 3D linear or circular button to the spray can to keep it full VR.

**Comment by thestonefox** [comment]
It's always worth just raising a PR to review and create a discussion point on new features :)

**Comment by WildStyle69** [comment]
OK got it... I'll create a PR request, in the next few days.
