### ISSUE TITLE
VRTK_ControllerActions > SetControllerOpacity Error?

### ISSUE THREAD

**Issue by WildStyle69** [thestonefox/SteamVR_Unity_Toolkit#425]
So I'm using custom hands in my project and when I make the controllers transparent, I've been getting an error at the console.

`Material doesn't have a color property '_Color'
UnityEngine.Material:get_color()
VRTK.VRTK_ControllerActions:SetControllerOpacity(Single) (at Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_ControllerActions.cs:80)`

The line in question is:

`renderer.material.color = new Color(renderer.material.color.r, renderer.material.color.g, renderer.material.color.b, alpha);`

I've fixed this locally by using the following check:

`if (renderer.material.HasProperty("_Color"))
{
    renderer.material.color = new Color(renderer.material.color.r, renderer.material.color.g, renderer.material.color.b, alpha);
}`

**Comment by WildStyle69** [comment]
Possible fix required, or am I doing something else wrong?

**Comment by thestonefox** [comment]
your fix seems legit

**Comment by thestonefox** [comment]
Fixed with https://github.com/thestonefox/SteamVR_Unity_Toolkit/commit/88dcf8e8cc84feabe0e9b4858463fe155ea5f55c

**Comment by WildStyle69** [comment]
Thanks for fixing man!
