### ISSUE TITLE
New Locomotion to prevent sickness

### ISSUE THREAD

**Issue by HyppoNymous** [thestonefox/SteamVR_Unity_Toolkit#439]
I found this one could be interesting as some alternative to teleport

[https://www.youtube.com/watch?v=4xX-X4OE884](https://www.youtube.com/watch?v=4xX-X4OE884)

It is linear movement paused every 0.3 seconds, and this should prevent sickness.

**Comment by thestonefox** [comment]
https://github.com/thestonefox/SteamVR_Unity_Toolkit/issues/65
