### ISSUE TITLE
Object not abiding by FixedJoint on Grab?

### ISSUE THREAD

**Issue by BenWoodford** [thestonefox/SteamVR_Unity_Toolkit#44]
For some reason after updating the toolkit, SteamVR and Unity (to 5.4 b17) whenever I try to pick up an object it dangles below the controller like it's trying to fall, and keeps falling a bit then resetting to the attach point, rinse and repeat.

This doesn't seem to happen on the example so I'm not entirely sure what I'm missing. It's just a basic cube Rigid Body with a mass of 1, 0 drag, box collider for collision, etc. Set to Simple_Snap.

Any thoughts on what may be up here?

**Comment by thestonefox** [comment]
Which camera rig prefab are you using? The one that comes with the toolkit or the one included with the steamvr unity plugin?

**Comment by BenWoodford** [comment]
It's got all the objects and rigid bodies so I assume it's the one from the toolkit. I'll start from the prefab again, add my scripts back and see what happens.

**Comment by thestonefox** [comment]
Did you solve you issue? Or identify the problem?

**Comment by BenWoodford** [comment]
Haven't had an opportunity to test it yet, I'll report my findings when I do.

**Comment by thestonefox** [comment]
This may be being cause by objects that have joints already on them no longer get a FixedJoint attachment to the controller. Instead they get a SpringJoint

After consideration, this new SpringJoint idea is not very good. It will be removed in the future in place of a better way of interacting with hinged objects.

**Comment by thestonefox** [comment]
This may be fixed now due to the new grab mechanics. I'll close it, but if you're still having issues then let me know.
