### ISSUE TITLE
Disable pointer whilst holding an object in hand?

### ISSUE THREAD

**Issue by xx1guardian1xx** [thestonefox/SteamVR_Unity_Toolkit#441]
How would I go around disabling the pointer when I've grabbed an object?

**Comment by thestonefox** [comment]
You can disable the pointer script in the "Grabbed" method on the interactable object:

https://steamvr-unity-toolkit.readme.io/docs/vrtk_interactableobject#section-grabbed-1

and then enable it again in the "Ungrabbed" method.

Or you could write a custom class that just listens for the grab/ungrab event and disable/enable the script globally.

**Comment by TThom1108** [comment]
Hey, Having this problem and the link is not working? Would you mind terribly updating, please.

**Comment by bddckr** [comment]
@TThom1108 Join [![Slack](http://sysdia2.co.uk/badge.svg)](http://invite.vrtk.io) instead.
