### ISSUE TITLE
Locomotion  like ArmSwinger plugin

### ISSUE THREAD

**Issue by HyppoNymous** [thestonefox/SteamVR_Unity_Toolkit#443]
I found this way of locomotion that feels natural and could avoid sickness 
[https://www.youtube.com/watch?time_continue=50&v=JjZNLGN_k-A](https://www.youtube.com/watch?time_continue=50&v=JjZNLGN_k-A)

**Comment by thestonefox** [comment]
This should belong to the existing issue on this subject

https://github.com/thestonefox/SteamVR_Unity_Toolkit/issues/65
