### ISSUE TITLE
snap objects in place.

### ISSUE THREAD

**Issue by koffertje** [thestonefox/SteamVR_Unity_Toolkit#445]
i don't know if this is something for the VRTK. But because you can move objects, it is also nice to have the option to snap objects in place. or take objects away from the snapped position.

lets say you have multiple object, and you want to combine them. but the objects have there own snapping position and rotation.

**Comment by thestonefox** [comment]
just reference to the other issue in case others find this one:

https://github.com/thestonefox/SteamVR_Unity_Toolkit/issues/196
