### ISSUE TITLE
VRTK_Height Adjust Teleport causes problems with grabbing objects with hinges

### ISSUE THREAD

**Issue by jerricko** [thestonefox/SteamVR_Unity_Toolkit#448]
Using the Height Adjust teleport script causes objects with hinges to move away from their hinge area and attach itself to the controller, rather than swinging open where it is. Upon letting go of the object, it will snap back into place.

To replicate:

Open the example scene _021_Controller_GrabbingObjectsWithJoints_ and add the _VRTK_Height Adjust Teleport_ script to the _[CameraRig]_ object and _VRTK_Beziel Pointer_ script to one of the controllers. Play the scene and try opening the door or the case.

Edit: I just found that it's related to the "Play Space Falling" option. With it unchecked, everything works as normal.

**Comment by thestonefox** [comment]
confirmed, looking to fix it now

**Comment by thestonefox** [comment]
Try this PR and see if it fixes your problem https://github.com/thestonefox/SteamVR_Unity_Toolkit/pull/451

**Comment by jerricko** [comment]
Yep, that did the trick! Thanks!

**Comment by thestonefox** [comment]
Cool, I'll merge that pr in the morning!

**Comment by jerricko** [comment]
I may have spoke too soon. I'm still seeing the same issue only on certain hinged objects. They're the only hinges that aren't reachable from the ground floor. Have to walk on top of a wing and open hatches. Looking at your updated code, I'm wondering if it's related to walking on an uneven mesh collider.

**Comment by thestonefox** [comment]
Yes I think it is. I have another fix, try setting the interactable object of the hinged item to have a specific tag like "excludeteleport" then on the teleporter set the ignore tag or class to the string "excludeteleport".

See if that works, I'm guessing it won't yet but I can apply a fix to make that set up work.

**Comment by jerricko** [comment]
Nope, still the same. I did change the line:
`if (floorY != previousFloorY)`
to 
`if (Mathf.Abs(floorY - previousFloorY) > 0.1f)`

and that seemed to fix it for my needs, at least.

**Comment by thestonefox** [comment]
I'll look into a proper fix in the morning. Your solution will only work under specific circumstances. Really needs a way of setting an item to not be able to teleport with when grabbed.

**Comment by thestonefox** [comment]
The PR has been updated with a more robust solution:

https://github.com/thestonefox/SteamVR_Unity_Toolkit/pull/451

There is now another option on an interactable object to prevent it from being able to be teleported when you're grabbing it: 

  > **Stay Grabbed On Teleport:** If this is checked then the object will stay grabbed to the controller when a teleport occurs. If it is unchecked then the object will be released when a teleport occurs.

If you set any handle or hinged item to have the `Stay Grabbed On Teleport` to `false` then they won't follow the controller on teleport.

This "should" fix your issue. Let me know how you get on with it.
