### ISSUE TITLE
Height teleport exclusion?

### ISSUE THREAD

**Issue by frozenMeatpopsicle** [thestonefox/SteamVR_Unity_Toolkit#45]
Is it a possibility to eventually exclude things from the height teleporter?

For instance, in a multi storey house, you'd want to be able to scale stairs and move up/down levels, but not be able to climb on prop like a table, or something like a statue.

Another problem is that a table(assume one with legs) could have physics objects on top of and underneath it. This would mean you could teleport into it, as well as on top of it; depending on what type of teleporter you're using.

**Comment by thestonefox** [comment]
Yeah, this is something I've been pondering the best way to do it.

Effectively you want to be able to have something applied to the objects that the teleport beam is hitting. If "whatever" the thing is that is applied to that object is present then you don't want to throw the destinationSet event in the world pointer.

This is how the new "Interactable Object" pointer beam activates thing works. If that is ticked on an interactable object then you don't teleport.

Could do it easily enough with a script (like no_teleport) that simply is used as a marker. I'd use tags, but they're so limiting as you can only have 1 tag per object.

Any other suggestions?

**Comment by frozenMeatpopsicle** [comment]
Not a suggestion, but just a realization that it would also need to take into account the "room scale" height movement too. Not just the pointer/cursor.

**Comment by thestonefox** [comment]
I've been giving the height thing some thought recently. The play area cursor prevents you teleporting to places where your head would clip, but if you were crouching then you should be able to teleport there. Would make for some interesting game mechanics.

Teleporting is definitely something that can be improved upon, let's keep this discussion going, hopefully more will join in too!

**Comment by couba** [comment]
Generally I'm trying to do somthing like this https://www.youtube.com/watch?v=wsWibz4aCto. I do it by scaling the [CameraRig]. The scale transition works, but it won't teleport me from "god mode" to the right place down. There is also a problem of the size of the pointers, as they are created at the beginning of the scene. When I change scale they remain either too small or too big. Is it possible to make it work without too much struggle?

**Comment by Epseni** [comment]
First of all thank you thestonefox for this excellent package, it really helps me with my own development!

In general the teleporting with meshes works well, but I have issues with sloped meshes like roof of a house. If you go to the top you sink in the mesh and if you teleport near the edge you hover high in the air. Also stairs as one mesh causes the same scenario. Can you think of a way to work around this?

**Comment by thestonefox** [comment]
@Epseni 
Do you have "Play Space Falling" option checked on the HeightAdjustTeleporter on the CameraRig?

This should always adjust your Y height to the nearest collidable floor. So when you walk up and down stairs, you should naturally just move up and down the objects.

**Comment by thestonefox** [comment]
@couba yeah I think just scaling things around you will probably cause some issues. I'll take a look when I get chance

**Comment by Epseni** [comment]
@thestonefox I have tried with it too, but it does not change the behavior. Falling will work excellent if each step has been modeled as single mesh, then you can go up and down walking in your space. However if the whole staircase is one single mesh then I have the before mentioned result.

You can test this by creating a plane and angling it for example 20 degrees if you go to high end you sink in, and at low end you hover.

**Comment by thestonefox** [comment]
@Epseni hmm that may be to do with the raycast code that checks to see if it should move you. It only moves you if the colliding object is the same.. Perhaps it would be better to move you if the y has changed.

I think that's what it does. I'll take a look later.

**Comment by thestonefox** [comment]
@Epseni Yeah it's what I thought the issue was.

Problem is because the y distance changes so much when you're walking over a mesh, you're stuck in a constant fade. If you take the fade out in this instance you get a sickly feeling.

I'll make the commit, push it up to a branch and you can check it out on that separate branch and see what you think

**Comment by Epseni** [comment]
@thestonefox This works absolutely perfect! I have no issues with sickness, as my problem was teleporting up a staircase, teleporting on sloped roof and teleporting on long sloped road made out of single mesh. Now it is possible to go up on each step without going in or above the object. 

Thank you very much, your work is really awesome! I hope I can contribute something going forward. There is not a lot of people pioneering this stuff.

**Comment by thestonefox** [comment]
@Epseni That's cool, ok I'll merge the changes in to the main branch

**Comment by pixelvspixel** [comment]
I'd be really interested in being able to limit teleportation as well to certain surfaces.

Thanks for all your awesome work!

**Comment by thestonefox** [comment]
@Epseni Your mesh traversal stuff is in the main branch now :)

**Comment by pixelvspixel** [comment]
Hey Stonefox I was trying to make a simple change to restrict my teleporting to just the floor mesh, as I keep moving into desk, walls and what not. I've added some code to the SteamVR_BasicTeleport script.

`if (e.target && e.enableTeleport && GameObject.FindWithTag("Teleport"))`

I tried just adding a simple check to look for a Tag "Teleport" that I've only addd to my flood, but it just seems to bypass the code. Am I inserting this in the right place?

**Comment by thestonefox** [comment]
if you're trying to check the target tag then you need to check it on e.target.

so something like 
`if (e.target && e.enableTeleport && e.target.gameObject.tag == "Teleport")`

This will check the target object for the "teleport" tag.

Doing `GameObject.FindWithTag` just finds any game object in the world with that tag.

Hope that helps.

**Comment by pixelvspixel** [comment]
Perfect! Thanks a ton for all of your help. It insane how quickly your toolkit is shaping up and improving!

**Comment by thestonefox** [comment]
Rolling this issue up into a new issue:

https://github.com/thestonefox/SteamVR_Unity_Toolkit/issues/105
