### ISSUE TITLE
012_Controller_PointerWithAreaCollision - Examples Tour - [SteamVR Unity Toolkit] issue with movement

### ISSUE THREAD

**Issue by Tbrosky** [thestonefox/SteamVR_Unity_Toolkit#459]
here are the screenshots of what I reported on the video as you can see after taking a few steps forward in the play area I "fall" off of the pillar and the play area is now around the pillar allowing me to get inside was just curious if there is an easy fix. thanks in advance.
![before movement](https://cloud.githubusercontent.com/assets/16121958/17941985/86b48710-6a03-11e6-8295-fd064f747aaa.jpg)
![after movement](https://cloud.githubusercontent.com/assets/16121958/17941987/8a516276-6a03-11e6-8f6b-6ed43b781232.jpg)

**Comment by thestonefox** [comment]
It depends what your ideal solution would be.

You can prevent yourself falling from the platform at all (but then you can walk and float in the air)

Or maybe when you walk into an item it resets your position to a safe location?

**Comment by HyppoNymous** [comment]
You can bake a navmesh area  with large agent radius, and as he fall move the player in the nav area. 
We have the example "033_CameraRig_TeleportingInNavMesh", we would need "falling into NavMesh".

**Comment by Tbrosky** [comment]
Awesome thanks guys!
