### ISSUE TITLE
Consequence of Issue 449

### ISSUE THREAD

**Issue by kylamon1** [thestonefox/SteamVR_Unity_Toolkit#461]
So after more testing I believe there is a new bug. Teleporting to an interactableObject does work well, but I can not "Use" an interactableObject using the "Hold button to use" option. I can only use an object using the "Pointer Activated Use".

I can replicate this bug on Test Scene 019. The one on the right side of the long table. I cant get it to activate.

**Comment by thestonefox** [comment]
Can you provide detailed steps of how to reproduce the issue in scene 019. I've had a quick play with the scene and it all seems to work as expected for me.

**Comment by kylamon1** [comment]
I couldn't get my scene 019 to work(specifically, the block you had to hold the button to use), so I figured I screwed with the code a little too much somewhere. 

1. I downloaded a clean copy of the entire VRTK from here deleted my old files and imported the new ones.
2. I loaded up scene 019 not changing any settings.
3. I can't get the capsule that requires the button press to activate,  I can get the one that is activate on pointer to spin, and the one that is just "use".

**Comment by thestonefox** [comment]
I've tried all the capsules in scene 019 and they all seem to work as I expect.

How are you trying to activate the capsules? with the pointer?

**Comment by kylamon1** [comment]
I just recorded a video of what happens.
https://youtu.be/-QTXLoz_ooY

Im wondering if some setting in unity got changed.....

One of the settings I changed was under Project Settings-->Physics-->Queries Hit Triggers, but toggling that did not change the outcome. Is there a way to set Unity setting back to default?

**Comment by thestonefox** [comment]
I can see in your video for some reason the collider on that cube is way off.

I'm not getting the same issue as you, have you tried pulling down a fresh copy of the project and opening it in a new unity project?

**Comment by kylamon1** [comment]
That's what eventually fixed the problem. I made a new project then it all
worked finr. I went back to the old one and it didn't work again. So it is
defiantly something on my end nit yours.
