### ISSUE TITLE
Error using last version

### ISSUE THREAD

**Issue by HyppoNymous** [thestonefox/SteamVR_Unity_Toolkit#465]
I have an error making the scenes unusable

Assets/VRTK/SDK/SteamVR/VRTK_SDK_Bridge.cs(4,11): error CS0246: The type or namespace name `Valve' could not be found. Are you missing a using directive or an assembly reference?

I am using Unity 5.3.5

**Comment by thestonefox** [comment]
You need SteamVR installed as per the quick start instructions:

https://github.com/thestonefox/SteamVR_Unity_Toolkit/blob/master/README.md#quick-start-for-steamvr

**Comment by HyppoNymous** [comment]
I already have SteamVR installed and games.
Perhaps i missed a new update ?

**Comment by thestonefox** [comment]
I mean the SteamVR unity plugin as mentioned in the readme link:

`Import the SteamVR Plugin from the Unity Asset Store`

**Comment by HyppoNymous** [comment]
My bad, i forgot the Unity plugin.
