### ISSUE TITLE
Calling SetParent method on an ineractable object causes Index out of range

### ISSUE THREAD

**Issue by jamieengelhard** [thestonefox/SteamVR_Unity_Toolkit#466]
Hi,
As part of a script I am writing, I need to make an interactable object the child of another interactable object. After setting the parent property or calling setParent, the next time I collide the controller with this new parent object, it throws the following errors:

IndexOutOfRangeException: Array index is out of range.
VRTK.VRTK_InteractableObject.ChangeColor (System.Collections.Generic.Dictionary`2 colors) (at Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_InteractableObject.cs:574)
VRTK.VRTK_InteractableObject.ToggleHighlight (Boolean toggle, Color globalHighlightColor) (at Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_InteractableObject.cs:273)
VRTK.VRTK_InteractTouch.OnTriggerStay (UnityEngine.Collider collider) (at Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_InteractTouch.cs:213)

I am thinking I need the script to reinitialize on the parent so that it knows the child count has changed. I am very new to all of this, so please excuse me and redirect me if there is some better forum to request assistance with this.

Below is my code - I'm sure it is terrible, but here goes:

using UnityEngine;
using System.Collections;
using VRTK;

public class DriveMountTrigger : MonoBehaviour {

    private Transform driveMount;
    private Transform driveMountParent;
    private Transform collidingObject;
    private VRTK_InteractableObject collidingObjectVRTKIO;
    private Rigidbody collidingObjectRB;

    // Use this for initialization
    void Start () {
        driveMount = gameObject.transform;
        driveMountParent = driveMount.root;
        Debug.Log(driveMountParent.name + " has " + driveMountParent.childCount + " children");

    }

    // Update is called once per frame
    void Update () {
	
	}

    void OnTriggerEnter(Collider coll)
    {
        if (coll.transform.name == "NX-3060_HDD")
        {

            collidingObject = coll.gameObject.transform;
            collidingObjectRB = collidingObject.GetComponent<Rigidbody>();
            collidingObjectVRTKIO = collidingObject.GetComponent<VRTK_InteractableObject>();

            collidingObjectVRTKIO.ForceStopInteracting();
            collidingObject.rotation = driveMount.rotation;
            collidingObject.position = driveMount.position;
            collidingObject.SetParent(driveMountParent);

            Debug.Log("My world position = " + driveMount.position);
            Debug.Log("My position relative to my parent " + driveMountParent.name + ":" + driveMount.localPosition);
            Debug.Log("My parent's world position = " + driveMountParent.position);
            Debug.Log(driveMountParent.name + " has " + driveMountParent.childCount + " children");

            //Debug.Log("Colliders Parent = " + collidingObject.parent.name);

        }

    }
}

**Comment by thestonefox** [comment]
This may actually be a bug, let me have a look and i'll create a PR for what I think a potential fix may be, give me about an hour and i'll push the PR up

**Comment by thestonefox** [comment]
What I thought the issue was doesn't seem to be an issue.

Is there anyway you can make an example scene to highlight the issue and send it over so i can debug locally?

**Comment by jamieengelhard** [comment]
Thank you!

By the way, I am forever indebted to you for this incredible piece of work. As an inexperienced programmer, I would have probably abandoned VR development as soon as coding the movement and interactions got tough. But your work has allowed me to get 10x further and faster than I could have imagined. So now I believe I can pretty much realize whatever I want, limited only by my creativity, time and energy. A million thanks!

-----Original Message-----

**Comment by jamieengelhard** [comment]
In attempting to create a sample scene for you I was not able to reproduce the issue using simple geometry. So I imported my main models and, sure enough it happens. So it has something to do with my models/meshes it seems. What I have determined is that I can fix the issue by breaking the model prefab (for instance by deleting one of its child objects or even by reordering components within the inspector) but it does not seem to matter HOW it gets broken just as long as it does. Any thoughts? I can provide you with the scene & scripts so you can see.

**Comment by thestonefox** [comment]
Yeah sure send me your files through that are actually broken with steps to reproduce and i'll take a look

**Comment by jamieengelhard** [comment]
OK, I figured it out. It is something very specific to my workflow and the tools I am using, but you may want to be aware. The issue is caused by conflicting object names within my models. I use SketchUp to create all my models and then export each to a separate .fbx which I import to Unity. Each .fbx file contains iterative names for each sub-mesh (Mesh1, Mesh2, etc) within the model. When I make one of these models the child of another, it creates a naming conflict and your highlighting code does not like this. If I rename the mesh objects, the issue does not occur. What's strange is that I can't reproduce this with entities I create in Unity, so there must be a bit more to it. But, alas, I have lost too much time on this already so I am going to have to leave it at that.

Thanks for your help, and I hope you didn't devote much time to this! As far as I am concerned this is closed, but I'll let you be the final judge of that.

**Comment by thestonefox** [comment]
That would make sense as the code uses the object name as a reference in the array:

https://github.com/thestonefox/SteamVR_Unity_Toolkit/blob/master/Assets/VRTK/Scripts/VRTK_InteractableObject.cs#L531

This could be fixable by not using the game object's name but instead using the game object's instance ID

`GetInstanceID()`

As this is always unique to every game object.

I'm considering this a valid bug.

**Comment by thestonefox** [comment]
Check out this PR and see if it fixes your issue:

https://github.com/thestonefox/SteamVR_Unity_Toolkit/pull/506

**Comment by jamieengelhard** [comment]
Resolved - thanks!
