### ISSUE TITLE
Split up VRTK_InteractableObject

### ISSUE THREAD

**Issue by Mishkun** [thestonefox/SteamVR_Unity_Toolkit#474]
One of the core scripts of this wonderful toolkit, VRTK_InteractableObject looks little messy.
[https://i.gyazo.com/747173e5caa15278a87b49528d714164.png](url) 

What about splitting it in three scripts, like those one attached to controllers?

**Comment by thestonefox** [comment]
It doesn't look like that now as a custom editor has been added to make it easier to digest the available options

**Comment by Mishkun** [comment]
Looks like I missed some pulls when was working on my project.
