### ISSUE TITLE
Controller Events Aliases Don't Imply VRTK default bindings

### ISSUE THREAD

**Issue by neilsutcliffe** [thestonefox/SteamVR_Unity_Toolkit#476]
Okay this is a hard to explain, but I'll try

The Controller Events has dropdowns which are set to names like the following.

- Touchpad_Press
- Grip
- etc

However, these are prewired to other components such as the BasicTeleport and grabbing objects. This is not implied by the variable names. Components tie into these, and there is no clear indication that this needs to be changed to disable this.

If these were named something like VRTK_Global_Grip or something like that, then one could easily see they are linked up and disable them if needed.

Unless I'm missing out on how the binding system works.

**Comment by thestonefox** [comment]
These controller aliases are specifically set to certain events.

The teleporter doesn't have a button alias on it. It expects a destination marker event which can come from anything not just a controller

**Comment by neilsutcliffe** [comment]
Closed as I'm talking nonsense.
