### ISSUE TITLE
Support "rec room"-like teleporting

### ISSUE THREAD

**Issue by 10FingerArmy** [thestonefox/SteamVR_Unity_Toolkit#477]
Inside rec room there are is a very nice teleport system: you can see the play area while teleporting and also your current position, which even updates while you move and still hold teleport.

**Comment by thestonefox** [comment]
You can already do this, if you turn on the Play area cursor then it shows the boundaries of your play area when you point the beam, it also shows you your position in those boundaries and can also be used to detect collisions and prevent you from teleporting if it is clipping a wall or something.

https://www.youtube.com/watch?v=OwACH7nhW1Q

**Comment by thestonefox** [comment]
Did I answer the question with my comment? I'll close in assumption of yes :) but I'll reopen if not
