### ISSUE TITLE
Provide snapping mechanism

### ISSUE THREAD

**Issue by 10FingerArmy** [thestonefox/SteamVR_Unity_Toolkit#478]
In order to work on a lock, key hole, "insert radio active rods here", plug something into electric sockets and many more we need a general purpose snapping mechanism. 

It should be proximity and direction based (e.g. don't snap the key if you are not facing the hole) and then rotate the object into the needed position. Once snapped, it should only allow limited movement, e.g. move along x-axis (min/max) or rotate around z (min/max).

**Comment by thestonefox** [comment]
Ok to merge this issue in with this issue?

https://github.com/thestonefox/SteamVR_Unity_Toolkit/issues/90


I think you're talking about the same thing.

I'm planning on doing this for the 2.2.0 release

**Comment by 10FingerArmy** [comment]
Merging is always good. I'll paste my text there.

**Comment by getwilde** [comment]
Not completely related, and too minor to actually log an issue, but here's some newbie user feedback if you're touching this in 2.2.0.  The "Precision Snap" setting seems to work opposite of what I'd expect.  If I **untick** it, then objects "snap" to a predefined point.  If I do tick it, objects **don't snap** but stay exactly where I grabbed them at. Worth considering a name like "Snap to Controller", or inversely "Precision Grab"?  

Thanks for a great toolkit!

**Comment by thestonefox** [comment]
@getwilde i guess it should be "Precision Grab" as you're right it's not actually snapping.
