### ISSUE TITLE
Radial Menu : Some bug about OnHoverEnter()

### ISSUE THREAD

**Issue by Jeff-xue** [thestonefox/SteamVR_Unity_Toolkit#479]
I have defined two methods.
public void HoverEnter(int i)
{
        Debug.Log("Enter Element " + i);
}
public void HoverExit(int i)
{
        Debug.Log("Exit Element " + i);
}
Assign methods to Buttons. such as Element 0, HoverEnter() assigned to OnHoverEnter() and i is 0, HoveExit() assigned to OnHoverExit() and i is 0. The same way, In the Element 1, i is 1.

Now, I defined tow buttons. 
When I touch Element 0, it will debug:
        Enter Element 0
And than I move my finger to Element 1, it will debug:
        Exit Element 0
        Enter Element 1
However, I raise my finger, it will debug:
        Exit Element 1
        Enter Element 0
**Enter Element 0** is the Bug!!!
And then if I touch Element 0, it no debug, after raise finger, it will debug:
        Exit Element 0
        Enter Element 0
when I touch Element 1, it will debug: 
        Exit Element 0
        Enter Element 1
After raise finger, it will debug:
        Exit Element 1
        Enter Element 0

On the other hand, I defined 3 buttons.
when I touch Element 0, it will debug: 
        Enter Element 0
And than I move my finger to Element 1, it will debug:
        Exit Element 0
        Enter Element 1
However, I raise my finger, it will debug:
        Exit Element 1
        Enter Element 2
**Enter Element 2** is the Bug!!!

**Comment by Jeff-xue** [comment]
Untiy 5.4.0f3

**Comment by thestonefox** [comment]
I can't recreate your issue. I wonder if it's a hardware fault with the actual controller registering a ghost touch?

Your proposed solution may cause you an issue though because if you change the touchpad axis from 1,1 and then touch precisely at 0,0 then you won't register a touchpad axis change which is incorrect as you have changed position on the touchpad axis.
