### ISSUE TITLE
Pointer interaction with world-based UI canvases

### ISSUE THREAD

**Issue by phr00t** [thestonefox/SteamVR_Unity_Toolkit#48]
In my SteamVR game, I want players to be able to point a controller at a world-positioned UI canvas & use the trigger to click a button -- just like the player interacts with the official SteamVR interface. Is this possible with the current toolkit? If so, how is it done? If not, can this feature be added?

**Comment by thestonefox** [comment]
Hey, I'm not sure if that would work (i can look into it though)

But I think the canvas sits on the camera view and not in the game world, so the pointer exists in the game world and points to game objects (that require a collider).

**Comment by phr00t** [comment]
Check this project out:

https://github.com/VREALITY/ViveUGUIModule

It'd be nice if this was integrated with this toolkit!

**Comment by thestonefox** [comment]
Cool, thanks for the link looks like a cool idea. I'll download it and check it out

**Comment by phr00t** [comment]
If it significantly simplifies implementation, I don't think it is that important for players to be able to hit UI elements while not looking at them (as done in the ViveUGUIModule).

**Comment by thestonefox** [comment]
I agree that being able to just use the UI elements for menu options is a lot easier than having to make up 3d objects that work as some sort of menu (which is how I've seen pretty much all games do it up till now)

**Comment by phr00t** [comment]
Something related to this feature & using it in Unity 5.4:

http://forum.unity3d.com/threads/vrinputmodule-not-working-in-5-4.403381/

**Comment by thestonefox** [comment]
@phr00t nice find! Good for reference.

**Comment by IARI** [comment]
Thx @phr00t for that link - that one bugged me :)

@thestonefox I'm working on a non-game application using this toolkit with ViveUGUIModule.
Particularly It would be good, if Events were not thrown when the raycast hits ugui.

I'll do what I can to support an integration.

**Comment by thestonefox** [comment]
Completed with https://github.com/thestonefox/SteamVR_Unity_Toolkit/commit/5fa29d7f159b00d9e719455f16d1d4f0bfc6b6b1
