### ISSUE TITLE
VRTK_UI_Pointer doesn't respect gameobject colliders

### ISSUE THREAD

**Issue by getwilde** [thestonefox/SteamVR_Unity_Toolkit#485]
If there's a worldspace UI behind a gameobject with collider, the simple pointer will stop at the collider but the UI elements behind it are still hit/highlighted.

To replicate, open Scene 034 (InteractingWithUnityUI), and add a collider (or a whirlygig object from scene 19, or whatever) in front of the WorldKeyboard.  You can see that the laser pointer correctly terminates on the surface of the collider, but that the UI Button elements behind are still being hit and highlighted.

This is particularly problematic for scenes where pointing to and using a gameobject opens up a UI panel.  If any button happens to appear behind the gameobject's collider, but still in view of the raycast, their click event is also fired immediately (even though the user only intended to open the panel, not also push a random button too).

I imagine this has something to do with UIPointer and SimplePointer BOTH firing a raycast, and not knowing about one other?

**Comment by thestonefox** [comment]
You can set the raycast blocking object on the `Graphics Raycast` component of the event system.

If you look at the Unity docs at:

https://docs.unity3d.com/Manual/script-GraphicRaycaster.html

You'll see it has a `Blocking Objects` setting. If you set this accordingly then the UI raycast will not pass through 3d objects.

The simple pointer has nothing to do with the UI pointer and is purely used as a visual aid. You can use the UI pointer without the simple pointer to interact with UI elements and therefore you need to specify the Blocking Objects on the Graphics Raycast to adhere to Unity standards.

**Comment by getwilde** [comment]
Thanks for the response. I learned something new!  However, I am still
seeing the issue occur when the blocking object is close enough to GUI
elements. To replicate:

   - Open Scene 34
   - Set "Canvas" position = (0, 0, 0)
   - Create a cube w/ collider. Set position = (0.3, 1, 0), scale = (0.2,
   0.2, 0.2)

At runtime, if you aim at the cube from the correct angle, the raycast
passes through and highlights buttons behind it.

**Comment by getwilde** [comment]
Okay, I think I found the issue.  At runtime, GraphicRaycaster is copied then deactivated, and a VRTK_UIGraphicRaycaster component is added in its place.  This class has a private constant UI_CONTROL_OFFSET which is set to 0.5f .  What's the purpose of this?

**Comment by thestonefox** [comment]
I'll look into this further and treat this as a bug

**Comment by thestonefox** [comment]
I think `UI_CONTROL_OFFSET` was originally there to fix an old issue that has subsequently been resolved another way. I'm going to make a commit that removes the need for it as it fixes your issue and it's redundant anyway (i believe)

**Comment by thestonefox** [comment]
Fixed with https://github.com/thestonefox/SteamVR_Unity_Toolkit/commit/284a5adc03a49e2544bb56475514bac79a45bcd4
