### ISSUE TITLE
Successfully Raycast Without Adding Component Rigidbody?

### ISSUE THREAD

**Issue by getwilde** [thestonefox/SteamVR_Unity_Toolkit#486]
I've avoided using rigidbody components unless necessary, even if set to kinematic. I haven't benchmarked anything but I imagine it adds some level of overhead, even if not to the physics engine.  

It took a while, but eventually I noticed that rigidbody components are being added at runtime to all of my InteractableObjects, even when they're not set to Grabbable. It looks like maybe(?) this is being done for raycasting purposes? But my understanding is that raycasting does not require rigidbodies, just colliders.  [Here's a recent article on the topic.](http://www.theappguruz.com/blog/collision-detection-without-rigid-body-in-unity) It may not be a big deal, but I thought I'd capture this here as a possible optimization.

On a related not, it took me a while to realize that if I had Interactable_Object component attached to a gameobject, **even if it was not active/enabled**, it would still add a Rigidbody component.  I'd expect the component to not affect my gameobject if it's not active.

BTW, thank you SOOO much for this toolkit.  :)

**Comment by thestonefox** [comment]
The rigidbodies aren't added for raycasting purposes, they're added so you can interact with the objects.

The controllers use a trigger collider so to even `Touch` an interactable object they require to connect to a rigidbody collider.

Grabbing is just an extension of being able to touch, so without being able to touch something then your object is never interactable in the first place and therefore wouldn't need the interactable object class applied.

**Comment by getwilde** [comment]
Thank you for the explanation. That makes perfect sense.

**Comment by thestonefox** [comment]
you can, but then they won't interact with physics objects or have gravity applied to them

**Comment by PraxxP** [comment]
I just want to grab and move the objects and let them stay in position, when I release the grab button (kinematic, no interaction with other objects, no gravity).
Could you please tell me how I can do that?
