### ISSUE TITLE
Undesirable UI interaction via Gaze under certain conditions

### ISSUE THREAD

**Issue by getwilde** [thestonefox/SteamVR_Unity_Toolkit#487]
I've run into an issue where under certain conditions, UI elements cease to be highlighted by UIPointer and instead are highlighed by the headset.  It's as if Camera (eye) or Camera (head) are firing an invisible raycast which interacts with UI elements, even when there is no pointer component attached to the head or eye.  The HMD actually hijacks pointer input from the controller -- or the controller relinquishes input control somehow -- and the only way to point at those UI elements is via the headset (and then pulling the trigger to actually click). 

I am having a hard time reproducing this in a simpler example scene.  Wondering if anyone else has seen this?

UPDATE:  Found the problem. It happens when a gameobject containing Canvas component is **not active** on Start. VRTK_UIPointer iterates through all **active** canvases in the scene and registers them.  I do see that I can call SetWorldCanvas() method to register it later, ie FindObjectOfType<VRTK_UIPointer>().SetWorldCanvas(canvas);  Unfortunately when I try to call that on Start(), VRTK_UIPointer returns null.

I'm trying to manage the number of Canvases ever active.  (I'm forced to use individual canvases for various camera culling masks.) Any thoughts?

Also curious about the gaze behavior... is it expected that the **headset** would start highlighting GUI elements on canvases that UIPointer doesn't find?

**Comment by thestonefox** [comment]
You have to manually register your own canvases if they're not in the world on start.

The UI example does this when you generate a new canvas, check the example code to see how it's done. If it's not working in Start for you, then run it in a co-routine and wait till the end of the frame to execute your code.

If the element is being highlighted then the UI Pointer is finding it. If you can provide an example of where this isn't the case then it can be looked in to.

**Comment by getwilde** [comment]
The co-routine approach worked great.  Once again, I learn something new.  So thank you.

Regarding the gaze behavior, it doesn't particularly bother me but here's a way to replicate it.
Open Scene 34

- In Inspector, deactivate WorldKeyboard checkbox
- Hit Run
- In Inspector, activate WorldKeyboard checkbox
- Use touchpad to interact with one or more elements in other Canvas (like "Hover", "Dropdown", etc)
- Release touchpad
- While pressing touchpad again, look at WorldKeyboard.  Notice how moving your HMD highlights different buttons.

Again, it's not causing a problem for me, so take it FWIW. :)

**Comment by thestonefox** [comment]
The outlined issue is because the canvas hasn't been registered.

If you start the scene with the canvas active in the inspector then the UIPointer will find all world canvases and register them for you.

However, if you start the scene with it disabled in the inspector, then enable it at runtime the UIPointer doesn't automatically register the canvas and you have to do it manually using

`VRTK_UIPointer.SetWorldCanvas(canvas)`

After this is called then the canvas will operate normally.
