### ISSUE TITLE
Aim or point at an object, and then use it as a separate action

### ISSUE THREAD

**Issue by getwilde** [thestonefox/SteamVR_Unity_Toolkit#488]
It would be nice to be able to aim a SimplePointer at an object, and then click Use button to begin using that object.  This is useful when the scene has smaller interactable objects and precision is required.*  VRTK supports the equivalent with UIPointer and GUI elements, but I haven't found the right combination of settings with SimplePointer and InteractableObjects via the Inspector panel, if they exist.  (For now I'm just handling it in code by subscribing to PointerIn, PointerOut, and desired Trigger events.)

BTW, I love the new custom Inspector panels for InteractableObjects! :)

*When Oculus Touch is released, we'll be able to use our outstretched index finger and get decent precision.  But for Vive, precision seems achieved either via custom Controller meshes or laser beam pointers.

**Comment by thestonefox** [comment]
You can already do this as standard:

https://www.youtube.com/watch?v=NhmGAbj5Hvo

**Comment by getwilde** [comment]
Thank you.  I did a bad job explaining my goal, which is to Use objects by aiming at them and pulling the trigger.  I have PointerVisibility=Always_On.
 
The way to make it work is to set PointerToggleButton = Trigger_Click, _and_ PointerSetButton = TriggerClick.  I erroneously assumed that PointerToggleButton would be ignored if PointerVisibility is Always_On, and the behavior had me scratching my head.  

Should "Pointer Set Button" be renamed to "Pointer Use Button"?

Thanks again for a great toolkit!
