### ISSUE TITLE
"Interface not found(105)”

### ISSUE THREAD

**Issue by luojc0517** [thestonefox/SteamVR_Unity_Toolkit#491]
Hi
I got an error "Interface not found(105)" when I run the example scene with htc vive,it didn't work at all and the controllers in the hierarchy is not active

**Comment by thestonefox** [comment]
This doesn't seem like an issue with the toolkit, This seems like an issue with either SteamVR or the Vive.

**Comment by luojc0517** [comment]
Thanks for your reply!,it turns out I didn't update the SteamVR runtime
