### ISSUE TITLE
Null Reference on CreateTouchCollider

### ISSUE THREAD

**Issue by justinISOFORM** [thestonefox/SteamVR_Unity_Toolkit#492]
Hello,

I just downloaded the toolkit and the newest version of the steamvr plugin on the asset store. Just trying to make a simple pick up objects and I am getting a null reference error in VRTK_InteractTouch.cs at CreateTouchCollider(). Is the toolkit not compatible with verion 1.1.1 of the plugin?

Thanks!

**Comment by thestonefox** [comment]
They should be compatible. Try the latest version from github and see if you still get any issues.

I never saw this issue when testing for the unity asset store 2.1.0 release

**Comment by justinISOFORM** [comment]
Must have been an issue on my end. Rebuilt the project and it is working fine. Sorry about that!
