### ISSUE TITLE
Radial Menu : Some bug about OnHoverEnter() And I soved it

### ISSUE THREAD

**Issue by Jeff-xue** [thestonefox/SteamVR_Unity_Toolkit#497]
#479 Radial Menu : Some bug about OnHoverEnter()
I proposed a bug that is the #479.
Now I soved it.
This is your Script in the VRTK_ControllerEvents
703      if (Vector2ShallowEquals(touchpadAxis, currentTouchpadAxis))
            {
                touchpadAxisChanged = false;
            }
Now I changed it
703      if (Vector2ShallowEquals(touchpadAxis, currentTouchpadAxis)  **|| currentTouchpadAxis == Vector2.zero)** )
            {
                touchpadAxisChanged = false;
            }
The Bug was be soved.
Thank you.

**Comment by thestonefox** [comment]
Any chance you can raise a pull request to fix this?

**Comment by thestonefox** [comment]
I'll close this ticket because it's referenced in a related issue
