### ISSUE TITLE
InteractableObject detachThreshold changes whiled grabbed ineffective

### ISSUE THREAD

**Issue by wheatgrinder** [thestonefox/SteamVR_Unity_Toolkit#498]
When grabbing an object I want to first set its detachThreshold to mathf.infinity 
and then in 1/10th of a second change the detachThreshold to some smaller number.  
This is to support the natural tendency to push down when first tying to pick something up, which normally  breaks the grab action.. thereby frustrating folks

The value of detachThreshold in the inspector is set to 5000
then when the object is grab my code does this:
```
....
GetComponent<SteamVR_InteractableObject>().detatchThreshold = Mathf.Infinity;
Invoke("undoInfinityBreak", 0.1f);
....
```

```
private void undoInfinityBreak()
    {
        GetComponent<SteamVR_InteractableObject>().detatchThreshold = 5000;
    }

```
Changing the detachThreshold via code wile the object is "grabbed" to infinity works, but the subsequent reset to 5000 in the undoInfinityBreak() code changes the value in the inspector, but the object behaves as if it still has an infinity detachThreshold.  I.E. the object does not "Force Release" , it doest break. 

Any thoughts on how to fix.  This is an odd case so just looking for help to fix.

Thanks

**Comment by thestonefox** [comment]
Try using the pause collisions on grab setting to pause collisions for a short amount of time when you initially grab to stop the immediate detach

**Comment by wheatgrinder** [comment]
ah man, great idea.. I should have saw that.   Instead of course I implemented a much more complex solution of disabling all the colliders on the object. and then re-enabling them.. yada yada.,. flipping the ignore collisions bits is much more graceful..   Im the stupidest smart person I know!

**Comment by wheatgrinder** [comment]
My issues is "resolved" but is there still and underlying bug you want to look at?

**Comment by thestonefox** [comment]
This is because the detachThreshold is only used at joint creation time to set the joint break distance. Changing that value after the joint has been created wouldn't change the joint. You're better off finding the joint on the object and changing it there instead.
