### ISSUE TITLE
Scene 021 - Unable to Swap Object Between Hands

### ISSUE THREAD

**Issue by xEvoGx** [thestonefox/SteamVR_Unity_Toolkit#50]
**021_Controller_GrabbingObjectsWithJoints**

This could and probably does pertain to any other given scene supporting object grabbing. When you hold an object in one hand, then (while still maintaining the hold) you grab the same object with the other hand, then subsequently let go of the previous hand, depending on how far apart you moved either hand while both were grabbing the object, the object will 'swing' off of the remaining grabbing hand as if on an invisible string _(phew that was some sentence!)_. 

Think of the magic trick where a card is suspended between the magicians hands by very thin, _invisible_ wire.

Cheers

-Steven

**Comment by thestonefox** [comment]
Yeah I can see why that is doing that.

The new code checks to see if the object has a joint already on it, then attaches a spring joint instead of a fixed joint.

I'd probably need to check to see if the object is being held already before allowing another controller to grab it. Then the spring (or any other joint wouldn't be added).

**Comment by xEvoGx** [comment]
This may or not be related, but I loathe to overwhelm you with posted Issues haha...

...but the physics begins to falter and fail when you try to push a held object into another rigid body (say the table the objects were sitting on). I understand **Unity physics** can be janky, but perhaps there should be a dampening and/or limiter _fail safe_ of sorts that auto-disconnects the held object from the controller after _X_, and harmlessly drops to the floor rather than furiously fight to maintain it's position in the hand. 

(If this should be it's own issue we can separate it out)

Thanks Stonefox! (Theston?)

-Steven

**Comment by thestonefox** [comment]
I think that is to do with the Unity physics solver. A higher number helps it work out better collision resolution.

However, it may be a nice idea as you suggested to just break the grip if it goes crazy.

You see the same crazy collision resolution issues in things like job simulator and the lab.

**Comment by xEvoGx** [comment]
Exactly and yea I know it's an all-purpose issue with engine physics, which is why I'm amazed that more implementations don't simply mitigate it by relaxing the pull of the body to the hand, or altogether disconnect it.

If an end-user fails to understand that a mug does not naturally pass through walls, the floor or you monitor and it falls out of their hand, that's on them methinks!

**Comment by thestonefox** [comment]
I think it's a fair trade off to say if you're trying to do something stupid with physics then just drop the object.

**Comment by xEvoGx** [comment]
Exactly!

**Comment by thestonefox** [comment]
I think this can be solved by just adding a break force to the joint created on the controller.

If an object starts going crazy in the physics its because a large force is being applied and the physics engine doesn't know what to do.

So a force on the joint will cause a natural break.

**Comment by thestonefox** [comment]
Magic trick effect removed.

No more magic allowed in VR.

Fixed with commit f8e1dacb243220dd1c67d50113107ccab75fed93

**Comment by xEvoGx** [comment]
Wonderful I try it out asap!
