### ISSUE TITLE
VRTK_Player Presence Crashes on stopping

### ISSUE THREAD

**Issue by sbmhome** [thestonefox/SteamVR_Unity_Toolkit#500]
I'm noticing that since I added in touchpad walking to my game Unity would crash when I pressed PLAY to    stop my code in Unity UI.

I narrowed it down to the VRTK_Player Presence script. I attached a short video showing that as soon as I uncheck it in the UI, it crashes Unity.

Since Unity crashes, I have no idea what is causing the issue.

Video showing issue (its unlisted :))
http://www.youtube.com/watch?v=5WsBLheKX90

**Comment by thestonefox** [comment]
what version of unity are you using?

**Comment by sbmhome** [comment]
5.3.4f1


Regards,
Steve

**Comment by sbmhome** [comment]
@thestonefox 
This issue can be closed. At this time, I don't think its an issue with VRTK. 

I still haven't figured out WHY this is an issue, but I was able to get it to work somehow.
