### ISSUE TITLE
Climbable objects distance issue

### ISSUE THREAD

**Issue by HyppoNymous** [thestonefox/SteamVR_Unity_Toolkit#505]
On example scene  037_CameraRig_ClimbingFalling, people can't climb things when they are too far one from each other some times, because they have shorter arms.
This is the issue with some VR games where people proportions can matters.

How to deal with each people varying height and arms lenght for such games gameplay ? 
Make several different levels with different lenght and distance between climbable objects ? Or manke one that works for everybody ?

**Comment by thestonefox** [comment]
Is this an issue with the toolkit or more of a general design issue?

**Comment by HyppoNymous** [comment]
A general design issue.
If you must hold one object with one hand and grab another object with the other hand that is placed 2 meters away , many people won't be able to grab the second object that is too far.
In the example 37 on the kit , there is many items i can't grab because they are too far from each other.

**Comment by mattboy64** [comment]
This was purposefully designed like this to force the player to jump for certain holds and to explore different ideas and design ideas. In a real game you'd have a tutorial to tell you that, but since it's just an example it obviously doesn't. It's definitely a consideration to keep in mind for actual games. Glad you like the demo enough to play it that much, and thanks for the input :)

**Comment by HyppoNymous** [comment]
I never figured we could jump in the game , some tutorial explaining you can jump would solve the problem.
A small jump and fall is so fast, that it would need a new type of grabbing for climbable objects.
You have one controller grabbing a climbable object and the other is controller free , from here you jump , you  hold the trigger button down on the controller that will grab a higher object, when your controller touches a climbable object while jumping it would automatically grab the climbable object and you could release the trigger button.

I mean a keep trigger button down on a controller to prepare it to grab a climbable object, when you controller enters in collision with a  climbable object, the controller automatically grabs the object and you can release the button trigger.
I think this would help for games needing jumping, however i am not sure the majority players will like jumping a lot in a game or it will be small game sessions.
And you can jump on sides of your living room without breaking some stuff also, because not every player has a big empty room to play/

**Comment by thestonefox** [comment]
@HyppoNymous you can already do pre-cognitive grabbing, it's just a setting on the controller grab script. I'm pretty sure the climbing scene already uses it too

also, this really isn't an issue with the toolkit, unless there is any reason to keep it open, i'll look to close this soon.
