### ISSUE TITLE
Teleporting Up/Down Y When Controller Directly Under HMD

### ISSUE THREAD

**Issue by xEvoGx** [thestonefox/SteamVR_Unity_Toolkit#51]
This could easily be my fault, as I merely added the _Bezier Pointer_ Script to the **Controller**, and the _Height Adjust Teleport_ script to the **CameraRig**, but I cannot seem to find a difference between my scene and the sample scenes you've provided. 

As spoiled in the _Subject_, when I move either controller directly underneath the HMD, I teleport up on Y as if standing on my controller beneath me. Move the controller away and I of course teleport back down to the ground.

If this was covered in your amazing tutorials I apologize for missing it!

Cheers

-Steven

**Comment by thestonefox** [comment]
Look on the camera rig teleporter script, try unchecking "player space falling"

However, if it's tracking your controller on the floor then this is a bug as it shouldnt be treating the controller as a floor.

**Comment by xEvoGx** [comment]
Yea no it is treating my controller as a floor. While unchecking _Player Space Falling_ works, that behavior is clearly needed ultimately.

Just interesting it works fine in your sample scenes, but not my reconstructed one. Possible another script is conflicting? It might not be a bad idea to have a **Master Demo Scene** that has every available option activated (i.e. grabbing, jointed objects, teleporting, falling, etc)

**Comment by thestonefox** [comment]
The controllers do get a collider added to them by one script (if I remember) and that should be ignored by the headset raycast. I'll look into fixing that.

I'm going to (one day!) get round to doing a super scene with loads of cool examples in. At the moment, each of the example scenes is hopefully small enough to understand what's going on with the particular scripts.

**Comment by xEvoGx** [comment]
Ah! Speaking of colliders and while I have your attention...

...are you considering too making the controllers be participating rigid bodies themselves? **Job Simulator** for example lets you you simply flap your hand against objects without grabbing, as such that you can slap buttons or doors to activate them without button presses. Play it if you haven't yet!

**Comment by thestonefox** [comment]
Yeah, I'm considering the best and appropriate way to allow the controllers to interact.

I'm not sure just whacking a rigidbody on the controller is the best move, maybe an option or something that generates it on your behalf.

I'd definitely like to be able to directly hit things around with the controllers though. Only problem is when grabbing stuff you could constantly push it away, so maybe the rigid body needs to be slightly smaller than the collider.

**Comment by xEvoGx** [comment]
That sounds likely what Job Simulator does, as it's not always 1:1 accurate when 'pushing'.

Not you have me wondering, so I'll go drop into Job Simulator tonight and pay attention to how they may be implementing it. 

You could consider (perhaps as a _toggle_ option in the Inspector) that pulling the trigger when NOT near any interactable object, turns on it's rigid body, so you'd effectively be in _'push shit around'_ mode. If unchecked then yea, it would behave like Job Simulator. Odds are good that they only **Rigidbody** the palm and not the fingers...

**Comment by thestonefox** [comment]
Fixed in commit 406225f047b760dc690d5e1b173effdb1398f01d

(this is a fix for the original issue which was controllers cause you to teleport)
