### ISSUE TITLE
Player presence script prevents leaning over objects like tables

### ISSUE THREAD

**Issue by thestonefox** [thestonefox/SteamVR_Unity_Toolkit#513]
Is there a way to allow for leaning?

**Comment by xEvoGx** [comment]
The only thing I can think of is to have a collider that is a bit lower and rearward of the {eyes}. 

**Lower** so a player can _lean_ left or right around a corner to peek, and **rearward** so the player can lean forward without triggering the height adjustment or whatnot.

Then again hard to solve for player presence. What we really need are pucks to attach to the waist and the ankles/shoes for full body awareness. Would mitigate all these issues hehe

**Comment by sbmhome** [comment]
Either that or have 2 colliders. One for the feet to restrict walking, the other for above the waist to allow the player to be collided with but can go over objects.

**Comment by thestonefox** [comment]
@sbmhome how would you know where to position the colliders when you lean?

At present the colliders are underneath the headset, so if you have 2 colliders and both are underneath the headset, then you still wouldn't lean over things.

**Comment by sbmhome** [comment]
Sorry, I do see the issue more clearly now. This is not an easy one since only the headset it tracked and a rearward collider for below the waist would only cause issues with walls.

**Comment by thestonefox** [comment]
This is going to be addressed in https://github.com/thestonefox/SteamVR_Unity_Toolkit/issues/603
