### ISSUE TITLE
Make prevent teleport on headset collision optional

### ISSUE THREAD

**Issue by thestonefox** [thestonefox/SteamVR_Unity_Toolkit#514]
It may not always be desired to block teleport on headset collision

in fact it may be better off letting this be done by a separate script that hooks the two events up.

**Comment by HyppoNymous** [comment]
I agree.
If the headset collision with some ennemy during gameplay, the player should be able to teleport away. Otherwise any collision that occurs with game objects would block the player teleport movement.

**Comment by thestonefox** [comment]
There's a PR for this if you wanna check it

https://github.com/thestonefox/SteamVR_Unity_Toolkit/pull/515
