### ISSUE TITLE
Archery - Arrow snapping issue.

### ISSUE THREAD

**Issue by Mark12000** [thestonefox/SteamVR_Unity_Toolkit#520]
Hello, thanks for the awesome toolkit! Has been very helpful so far.... However, when I put my arrow (arrow has mesh collider) onto my bows handle box collider the arrow snaps to the handle and rotates the bow to another direction. The bow then acts strangely and you can sort of spin it around and stuff.... I think the arrow also shoots from the side of the bow instead of the front. If you'd like I could send you my concept project files... It's only about 300MB, less if compressed. Otherwise, any ideas what could be the problem? I know you can't really tell anything just from this comment but any thoughts would be helpful.

I will upload my project to mediafire and mega.nz tomorrow as I forgot to transfer the files to my flash drive before going home (and take said drive :P). I will try to get it working again tomorrow.... If I do I might post what the problem was so that it might help other people, if I can't get it working I'll upload my project and state what everything is (there's not much really, just a bow and arrow that I'm trying to get to work (also a Crossbow that can be ignored)) so that you know what everything is and what they do.

Ok, so below is my setup, So MedievalBow is the parent object I suppose as it contains the root (the bone that moves the string and deforms the bow itself), it has a rigid body, the animator, the animation itself and the bow animation, bow aim and interactable object scripts. The Bow is the model itself and just has the mesh renderer and rigidbody. The arrownockingpoint has the Follow script attached and Handle has the Bow Handle script attached. The collision just contains the collision of the bow itself, none set to triggers. finally snapPoint is just an empty game object that has been put in the handle.

For the MediavalArrow, it has a rigidbody, mesh collider, and the interactable object and arrow notch scripts. The Arrow (the actual Model) has the mesh renderer, rigidbody and Arrow script. and the SnapPoint here is also just an empty game object. If anything changes today I'll update this thread (and upload project files if I can't work out what's wrong), thanks!
![capture](https://cloud.githubusercontent.com/assets/22027985/18293409/a39c7f4e-74d1-11e6-98b6-1471b5d131fc.JPG)

**Comment by Mark12000** [comment]
Update info. Will continue working on this today to see if I can get somewhere.

**Comment by thestonefox** [comment]
This may be better asked in the slack channel: Invite yourself at:

https://vrtk-slack-invite.herokuapp.com/

As it doesn't seem to be an issue specifically with the toolkit but rather with a setup and someone in the channel may be able to help out quicker.

**Comment by Mark12000** [comment]
Hello, thanks for the link.... But after about 14 hours I still haven't got an email. Does it usually take this long?

**Comment by thestonefox** [comment]
@Mark12000 no it shoudn't take that long.

drop me an email with your email and i'll manually invite you/

thestonefox at gmail

**Comment by Mark12000** [comment]
Thanks but it just came through like an hour before you commented hahah, not sure what happend but all good now.
