### ISSUE TITLE
Namespace collisions

### ISSUE THREAD

**Issue by jcrombez** [thestonefox/SteamVR_Unity_Toolkit#521]
While trying to add VRTK to my existing game, i had to remove all examples because i had collisions with some classes (`Bow`, `BowAim`, `Sword`) but the more problematic one is the collision with `RadialMenu` because it's not part of the examples. Anyway, deleting stuff from the plugin is not a solution as i would have to do it again at every update.

Those classes should be namespaced like the rest of this library to avoid this kind of problems, don't you think ?

**Comment by 10FingerArmy** [comment]
Definitely! +1
