### ISSUE TITLE
Player Presence with a Capsule rather than Box Collider?

### ISSUE THREAD

**Issue by xEvoGx** [thestonefox/SteamVR_Unity_Toolkit#523]
With just a Box Collider, It's very easy to get snagged onto very tiny edges, requiring that collision volumes are precisely aligned (this is easier said than done and quiet tedious if there are a lot of them).

Capsule would allow for smooth traversal

**Comment by thestonefox** [comment]
Yeah this is a good idea

**Comment by mattboy64** [comment]
I thought about using a capsule, but I thought the slide might cause discomfort and have an odd (and potentially long) transition between slow falling and actual falling. Worth trying out, but a cylinder might work better.

**Comment by xEvoGx** [comment]
Well I'm concerned about that hard edge at the feet. Right now with the Box Collider I get stuck on the smallest of edges, and as you know being that precise lining up Col vol's is very tedious.

That said, regarding nausea/discomfort...this IS arguably an advanced or 'Intense' mechanic as it is, so it might not matter once the person is committed to the gameplay. As I've mentioned elsewhere, my VR legs are coming along nicely and I'm prone to motion sickness...and I'm kind of tired of teleporting everywhere lol.

**Comment by mattboy64** [comment]
Yeah, I get the reasoning. Have you tried replacing it to see how it works? I could see both being valid alternatives. Maybe a dropdown to select the collision type? Adjusting the friction could help as well with the capsule.

**Comment by xEvoGx** [comment]
I have not and yea a dropdown is probably the best way to go. Options always good. More than not I'll be trial and error certainly
