### ISSUE TITLE
Some VRTK_InteractableObjects deform their parent's mesh after grab/release

### ISSUE THREAD

**Issue by lleti** [thestonefox/SteamVR_Unity_Toolkit#526]
Unsure of what is causing this, but it's reproducable. Please reach out for the full Unity Project folder if required.

Appears to happen with very small objects.

Example - small cube primitive at the start of a scene being played: http://i.imgur.com/g0DAS64.png

Same cube, after being grabbed/released around 10 times: http://i.imgur.com/k1q5obb.png

Scale did not increase in the spector, albeit it appeared to have went to around 1.5x on the z axis, and 0.5x on the y axis. The mesh itself seems to have also skewed itself to one side. No custom scripts in use, standard settings on the object in the inspector; http://i.imgur.com/REHPXOH.png

- lleti

**Comment by lleti** [comment]
Found that this issue appears to occur when you set the scale of a parent object, but set a child object as grab-able. Parent object was at about 0.02, 0.02, 0.04 - when parent object was set back to 1,1,1, and the child object (the cube itself) was set with this scale, the problem stopped occurring.

**Comment by thestonefox** [comment]
So have you resolved your situation? Can this issue be closed?
