### ISSUE TITLE
[Bug] Dash Teleport Does Not Height Adjust

### ISSUE THREAD

**Issue by xEvoGx** [thestonefox/SteamVR_Unity_Toolkit#534]
I know we talked about this on Slack and you confirmed it worked, but unless I'm doing something wrong, it does not.

I simply loaded a clean **038 Climbing**, removed **Height Adjust** (I did verify THIS was at least working before removing it) and added **Dash Teleport**, and all that happens is that it _blinks_, but doesn't actually move me upwards one way or the other. 

For a simple test, I just teleport over to that small cube nearest the scene default starting point and lean the HMD over it. I pop on top of it with **Height Adjust**, but not with Dash.

An added bonus? I found it difficult to teleport 'close' to the cube with the Dash script active, but had no problem with the Height Adjust script.

**Comment by xEvoGx** [comment]
Oh and to be clear I can otherwise Dash Teleport around the game world just fine, so we do know that dashing works...

**Comment by thestonefox** [comment]
I'm confused, are you loading the climbing example or the dash example?

Climbing is 037 - Dash is 038

Dash example does not have the "Height Adjust Teleporter" script on the camera rig, it just has the Dash script on it.

And I can confirm that the Dash example allows you to change your height when dashing.

**Comment by xEvoGx** [comment]
Dash works, yes, when using the pointer and 'teleporting'. When you walk around the play space thoug your height is not adjusted. What I want is for **Height Adjust Teleport** to work _like a Dash._ 

When you're climbing in **038**, **Height Adjust Teleport** allows you to complete the climb by "standing" on top of the surface; you're set to the correct height on top of that collider. Problem is that it's instantaneous...

...I would prefer a smooth Lerp that **Dash** offers, but for Height adjustment, not 'teleporting' up and onto a higher surface.

The easiest way to see what I'm talking about is trying to lean over a collider in any example, and see the difference between Height Adjust Teleport and Dash Teleport. This has nothing to do with pointer teleporting.

**Comment by thestonefox** [comment]
Right ok gotcha, so it does change your height when normal teleporting, but when the "drop to nearest floor" bit is supposed to kick in then it doesn't dash?

**Comment by thestonefox** [comment]
Should be fixed with: 

https://github.com/thestonefox/SteamVR_Unity_Toolkit/commit/de6358c5d8b6e6065fca7c61894669505da2a465

I'll raise another issue for the teleport position issue as I've noticed that too.

**Comment by thestonefox** [comment]
Actually it seems as if this bug fix, fixes the other issue as well :)

**Comment by xEvoGx** [comment]
Nice I'll check it out asap!
