### ISSUE TITLE
Highlighting not toggling off correctly after interactable object is made child of another

### ISSUE THREAD

**Issue by jamieengelhard** [thestonefox/SteamVR_Unity_Toolkit#544]
I have two interactable objects, both with highlight on touch enabled. If I make one object the child of the other, the child object's highlighting sometimes does not get turned off after touching and untouching the parent. Touching and then untouching the child object will properly turn off the highlighting. From my testing, it may be that it only happens when the two objects are colliding at the exact right moment either when setParent is called or immediately thereafter.

You should be able to reproduce this with the attached file. All you need to do is touch the small cube to the yellow trigger, which establishes the parent/child relationship. Then touch and untouch the big cube - the small cube stays highlighted.

I am giving you the entire Unity project - let me know for future reference if you just need the scene and scripts?

[VRTKIOsetParentDebug.zip](https://github.com/thestonefox/SteamVR_Unity_Toolkit/files/463041/VRTKIOsetParentDebug.zip)

**Comment by thestonefox** [comment]
I'm currently re-writing the highlighters so i'll take a look at this issue and see if i can resolve it at the same time.

**Comment by thestonefox** [comment]
Can you try this again using the latest version on github, the highlighting and touch have been rewritten so it may fix the problem
