### ISSUE TITLE
[Locomotion]: Implement walking with touchpad

### ISSUE THREAD

**Issue by thestonefox** [thestonefox/SteamVR_Unity_Toolkit#55]
Ability to move the play area using the touchpad and always walk forward in the direction the headset is facing.

**Comment by thestonefox** [comment]
Branch demoing solution: https://github.com/thestonefox/SteamVR_Unity_Toolkit/tree/feat/touchpad-walking

**Comment by bcoyle** [comment]
I could see a use in some of my projects where you want to initially orient the game experience to your physical space. So moving, rotating the play area until aligned with a spatial marker. Then locking it off could be interesting.

Imagine one controller would be used as a marker to place on a table or chair, and the other controller would move/rotate you until the controller aligns/sits on the virtual surface.

**Comment by thestonefox** [comment]
@bcoyle I've seen blogs about that sort of thing, where you can position things in the real world then tag them with the controller current position (or something) then those objects can be created in the game world. So you know where tables are to put the controllers.

Would be cool to implement something like that.

**Comment by thestonefox** [comment]
This isn't working in Unity 5.4 beta due to the way the headset is located.

**Comment by thestonefox** [comment]
Related to this issue: https://github.com/thestonefox/SteamVR_Unity_Toolkit/issues/62

**Comment by thestonefox** [comment]
The latest version of this branch:
https://github.com/thestonefox/SteamVR_Unity_Toolkit/tree/feat/touchpad-walking

Has a fix for unity 5.4 so should be working.

**Comment by thestonefox** [comment]
New version of this branch is now live. Resolves the unity 5.4 issue also tracks the person collider to where the headset it and also allows for crouching.

**Comment by thestonefox** [comment]
Need to prevent being able to stand up in areas where you're not allowed to stand up otherwise it goes crazy trying to resolve the rigid body.

One way to resolve would be to track the highest height that the headset has been at, then track the position of the play area whilst it was at that highest point.

Then on conflict just move the play area back to the last good known position. Will be jarring for the user as they will just be sucked back to a previous position, however there is no way of stopping the user standing up and causing a rigidbody conflict.

**Comment by xEvoGx** [comment]
Yup that's what they do in Budget Cuts. Thankfully upon standing we fade to black so that's on the player.

**Comment by thestonefox** [comment]
Yeah I think if the player is going to do something unnatural in game, then it's fair to resolve it with an unnatural response (i.e. fade to black and teleport to last good location)

**Comment by xEvoGx** [comment]
Yup we're clearly on the same page here (see #65 hehe)

**Comment by bcoyle** [comment]
Another post about trackpad movement, https://www.reddit.com/r/Vive/comments/4k7an5/something_changed_im_now_ok_with_trackpad/

**Comment by thestonefox** [comment]
@bcoyle I'm working on the touchpad movement script right now!

Just got the collision resolution working, hopefully should be pushing the branch soon!

**Comment by thestonefox** [comment]
Ok new branch for people to try:

https://github.com/thestonefox/SteamVR_Unity_Toolkit/commits/feat/touchpad-walking


It now supports collision reset, so if you crouch and walk under something then try stand up, you just get put back to your last good standing position.

There is also a collider offset you can apply to make it lower than touching the headset to prevent grabbing objects hitting the collider (you could also toggle this offset via script at point of grab as it's public).

**Comment by thestonefox** [comment]
First version completed with: 3582c87173378ef8c1169d4d0ce63c42a9c0965b
