### ISSUE TITLE
Bug: Climbable VRTK_InteractableObject creation in code adds a Rigidbody

### ISSUE THREAD

**Issue by mattboy64** [thestonefox/SteamVR_Unity_Toolkit#554]
The VRTK_InteractableObject Awake function checks to see if the object is static (climbable). If not it auto adds a rigid body component. That's fine if you set it up before hand, but unfortunately if you try to create one in scripts, the Awake is called before I can assign it as a climbable object. Not only is the rigid body not needed, but it is doing some funky things when I grab it. I'm not sure how to fix this one. Passing the grabtype to an overloaded constructor might work, but that makes the object state unserializable. I don't really understand what that means enough to know if that is a problem or not here. Suggestions?

**Comment by thestonefox** [comment]
why do we even need that auto rigidbody creation?!?!

**Comment by thestonefox** [comment]
would this help in the awake?

```
protected virtual void Awake()
{
    rb = GetComponent<Rigidbody>();
    autoRigidbody = false;
    if (!AttachIsStaticObject())
    {
        // If there is no rigid body, add one and set it to 'kinematic'.
        if (!rb)
        {
            rb = gameObject.AddComponent<Rigidbody>();
            rb.isKinematic = true;
            autoRigidbody = true;
        }
        rb.maxAngularVelocity = float.MaxValue;
    }
    forcedDropped = false;
}
```

If a flag is set, then you know it's been auto created and you can delete it.

Plus, you can always override the Awake method and do whatever you want :)

**Comment by thestonefox** [comment]
I think this was resolved? I'll close and see if anyone moans :)
