### ISSUE TITLE
VRTK_ControllerEvents.Update() creates significant performance spikes

### ISSUE THREAD

**Issue by mattboy64** [thestonefox/SteamVR_Unity_Toolkit#555]
Trying to climb up a single climbable object quickly gives me some super large performance spikes (169ms). I'm not sure if this is primarily an editor issue or if it is a release issue as well. Here's a screenshot of what I'm seeing:
![image](https://cloud.githubusercontent.com/assets/7003769/18408883/031579dc-76f1-11e6-9f8a-f5280fedfc36.png)

I'm running an i7-5820k, NVidia 970, Windows 10 64 bit, 16 GB of RAM

**Comment by thestonefox** [comment]
Any chance you can isolate the spike to a specific line in the update code?

**Comment by mattboy64** [comment]
Yeah, did a deep profile and it showed a lot more. Looks like DeviceFinder isn't caching some info and is calling FindObjectsOfType(). I have uhhhh.....a lot of objects in my scene, so it's understandable that it would be sloooooow.

![image](https://cloud.githubusercontent.com/assets/7003769/18409205/cdf5cbde-76f6-11e6-87d6-b427df1a1949.png)

**Comment by mattboy64** [comment]
Actually, when did caching go in? Maybe I don't have that update?

**Comment by thestonefox** [comment]
Not long ago. But the controllers aren't cached. I don't think the find object of type stuff should be hit in controller events though :/

**Comment by thestonefox** [comment]
I've just done a PR that caches the controllers to prevent a FindObjectsOfType call

https://github.com/thestonefox/SteamVR_Unity_Toolkit/pull/556

But that was only happening in the PlayerClimb ungrab code, so not sure if it's related.

**Comment by mattboy64** [comment]
I've tested with the latest code drop and can confirm that the controller cache fixes the problem. 

Closing out the issue.
