### ISSUE TITLE
Unexpected behaviour for teleport

### ISSUE THREAD

**Issue by gpvigano** [thestonefox/SteamVR_Unity_Toolkit#566]
An unexpected behaviour occurs with the following settings.
_VRTK_Controller Events_:
* _Pointer Toggle Button_ set to _Touchpad_Press_ (or any button
different from _Pointer Set Button_),
* _Pointer Set Button_ set to _Trigger_Click_ (or any button different
from _Pointer Toggle Button_)

and also with both _Pointer Toggle Button_ and _Pointer Set Button_ set
to _Touchpad_Press_ (or any other button)

_VRTK_Simple Pointer_:
* _Pointer Visiblity" set to "Always_Off"
* _Hold Button To Activate_ unchecked

The teleport works only pressing Touchpad_Touch after the teleport
is deactivated (and only once until the pointer is activated and
deactivated again).

A scene is attached here for testing (Example 4 with settings changed, Unity 5.4).  
[004_CameraRig_BasicTeleport_Bug.zip](https://github.com/thestonefox/SteamVR_Unity_Toolkit/files/469257/004_CameraRig_BasicTeleport_Bug.zip)

These weird settings come from a trial to remap buttons on GearVR (see my comment to   #502 ).

**Comment by thestonefox** [comment]
ok I can recreate, i'll look into it

**Comment by thestonefox** [comment]
PR to resolve this issue https://github.com/thestonefox/SteamVR_Unity_Toolkit/pull/567

See if it works for you.

**Comment by gpvigano** [comment]
OK, it works!
