### ISSUE TITLE
Teleporting

### ISSUE THREAD

**Issue by piapple1** [thestonefox/SteamVR_Unity_Toolkit#57]
I cannot seem to teleport with my left controller anymore. I tried to look into it but I am not that experienced haha. Any help would be amazing. Thanks!!

**Comment by thestonefox** [comment]
Try closing Unity (maybe even restarting SteamVR app on your desktop). then make sure both controllers are synced before starting the game world.

Sometimes this happens when it can't find the controller. I need to try and make it more robust.

**Comment by piapple1** [comment]
Thanks so much, I will try this right now. This toolbox is a godsend.

**Comment by piapple1** [comment]
That cleared the issue up immediately. This might be a dumb question but what is there a way to turn off teleportation for one controller but still have the pointer that can interact?

**Comment by thestonefox** [comment]
Check out this tutorial:
https://www.youtube.com/watch?v=NhmGAbj5Hvo

Is that what you're after?

Or do you want that but on the one controller the beam never teleports even if it's not touching an interactable object?

**Comment by piapple1** [comment]
Oh okay I thought I saw something similar before in your videos. What I meant was the second thing you said, never teleporting under any circumstance but can still interact. Does that make sense? I am just getting into VR dev.

**Comment by thestonefox** [comment]
Ok no worries, Give me a couple of hours and i'll add it as an option to the pointers so you can toggle them to never send the DestinationSet event (which is used by the teleporter)

**Comment by piapple1** [comment]
Thanks that's great. I appreciate it.

**Comment by thestonefox** [comment]
Fixed in commit 821bb5e1522bfb1ce615545723a3e0908cd28fc2

There is a new option now on the pointer "Enable Teleport" if you uncheck it then the pointer will never teleport the player.
