### ISSUE TITLE
[Structure] Replace script prefix from SteamVR_ to something else (maybe SVRUT_)

### ISSUE THREAD

**Issue by thestonefox** [thestonefox/SteamVR_Unity_Toolkit#58]
Whilst it seemed like a good idea at the time to call the scripts within this toolkit the same prefix as the SteamVR plugin scripts, it's actually really dumb.

If there is ever a script in  the plugin with the same name then there could be confusion or even compile errors.

Need to change the script names in this toolkit to something more distinct to reduce confusion and prevent issues in the future.

Suggested prefix: `SVRUT_`

**Comment by bcoyle** [comment]
1. `VRTLKT_`
2. `VRTOOLKIT_`
3. `VRTK_`
4. `VRUTK_`

A few other possible options.

**Comment by thestonefox** [comment]
I quite like `VRTK_`

**Comment by Frostlock** [comment]
+1 for VRTK.
SVRUT just sounds horrible :-p

**Comment by thestonefox** [comment]
Completed with 96468f5624a8c03bce4f77fccadb823cf54ad736
