### ISSUE TITLE
Highlighting looks terrible on many meshes, including cube

### ISSUE THREAD

**Issue by SmartCarrion** [thestonefox/SteamVR_Unity_Toolkit#581]
There are a number of visual bugs with the highlighting:

1.  It can have large gaps between the items and the highlight faces
2. It changes width depending the distance from the camera
3. it doesn't highlight just the world edges of meshes, it can highlight internal edges too

Here is one example pic, the blue is highlighting a red box:
![big gaps](https://cloud.githubusercontent.com/assets/5105110/18614617/a5580790-7d46-11e6-8d02-00b88d2227df.png)

There are a couple objects that look ok, but most come out messed up.  Is this just my problem?

thanks!

**Comment by thestonefox** [comment]
What highlighter are you using?

**Comment by SmartCarrion** [comment]
Just the standard one from the git:  OutlineBumpedDiffuse.shader

I could be doing something wrong though

**Comment by thestonefox** [comment]
That's an issue with that shader. Not the toolkit.

**Comment by SmartCarrion** [comment]
Agreed!  I still need a solution :-)

**Comment by thestonefox** [comment]
Take a look at this pull request https://github.com/thestonefox/SteamVR_Unity_Toolkit/pull/578

It may do what you need

**Comment by SmartCarrion** [comment]
will do, thank you
