### ISSUE TITLE
Steam_VR_Play_Area script causes massive lag in Unity editor

### ISSUE THREAD

**Issue by boeremak** [thestonefox/SteamVR_Unity_Toolkit#59]
Hi,

Just wanted to give you a heads up. Wanted to try something in Unity with my Vive and your scripts are pretty much something you come across immediately when wanting to do something useful with it. So thanks for that. :)

After importing the Unity toolkit into my project using the video you made and creating the Camera_Rig you provide in the toolkit interactive performance of Unity itself tanks.

I found out that I turn off the play_area script the editor works like it should. In the bottom right I get the following error:

> Failed to get Calibrated Play Area bounds!  Make sure you have tracking first, and that your space is calibrated.
UnityEngine.Debug:LogWarning(Object)
SteamVR_PlayArea:GetBounds(Size, HmdQuad_t&) (at Assets/SteamVR/Scripts/SteamVR_PlayArea.cs:48)
SteamVR_PlayArea:BuildMesh() (at Assets/SteamVR/Scripts/SteamVR_PlayArea.cs:93)
SteamVR_PlayArea:Update() (at Assets/SteamVR/Scripts/SteamVR_PlayArea.cs:213)

My game area is calibrated, am I missing something obvious.

**Comment by thestonefox** [comment]
Try restarting steam vr and unity. There seems to be an issue with one of those two things.

The problem isn't with the toolkit but with steamvr or the steamvr unity plugin

**Comment by boeremak** [comment]
Ok, will do. Thanks.

**Comment by thestonefox** [comment]
I always find that SteamVR is needed to be running before you start Unity otherwise things go weird.
