### ISSUE TITLE
Dropping of objects on leaving "Stream VR Environment"

### ISSUE THREAD

**Issue by JamesHunter-DeepVoodoo** [thestonefox/SteamVR_Unity_Toolkit#596]
1. Grab an object (say my gun)
2. Press the system button to show the steam VR environment
3. Press system button to hide it..  
4, The gun is immediately dropped, BUT the controller is invisible until you pick up the gun again.. 
5. The gun's "Hold To Grab" it turned from false to true (i.e. you must now hold the grab button to keep hold of the gun, which was not the original setting)

**Comment by thestonefox** [comment]
I'm not able to recreate this in an example scene.

Any chance you can see if you can replicate the issue in an example scene?
