### ISSUE TITLE
[Structure] Add inspector tooltips and better parameter grouping on scripts

### ISSUE THREAD

**Issue by thestonefox** [thestonefox/SteamVR_Unity_Toolkit#60]
The script parameters in the editor could do with tooltips and better grouping using headers, etc.

It may be worth writing some collapsible group panels too to toggle parameter visibility based on other items selected.

**Comment by Hexagon-Vienna** [comment]
no matter what I try to code in unity for my VR Simulation... Yours is so much better and you are so much faster :DDD
Really good work, the whole Toolkit. Thank you very much!
I tried other scripts as well, but actually came back to your Toolkit and it has grown so much !

**Comment by thestonefox** [comment]
Thanks for trying it :)

**Comment by bcoyle** [comment]
@thestonefox is there any way I can help with tool tips?

**Comment by thestonefox** [comment]
Urm, I guess coming up with good easy to understand text for what each option does would be a great help.

Maybe in the format of:

Filename: ParameterName [Tooltip description]

**Comment by thestonefox** [comment]
Trello Card https://trello.com/c/v8uwi7WG
