### ISSUE TITLE
line renderer shows double vision in HMD

### ISSUE THREAD

**Issue by taridyn** [thestonefox/SteamVR_Unity_Toolkit#600]
I tried using a line renderer.  It showed up fine in the unity window, but in the headset 2 different lines showed up.  The line shown in the left eye was correctly positioned, the one in the right eye was tilted about 10 degrees to the right (pivot point seemed to be the head).  It moved in world space as I moved/tilted my head.

I was able to get it to function properly on game objects which also had a VRTK_interactable object script (but only in VRTK 2.0).  Adding the script in 2.2.1 doesn't fix the problem.

**Comment by thestonefox** [comment]
What are you applying the line renderer to?

Could you provide more details about the set up of your scene so I can attempt to recreate the issue.

**Comment by taridyn** [comment]
I managed to replicate the issue reliably.  But in doing so, I realized it isn't an issue with VRTK.  it is a problem that occurs when using the single pass rendering in unity (edit - player - single pass stereo rendering).  Sorry for the confusion.  This has nothing to do with your addon.  I will remove the bug log.


By the way, thanks for the wonderful work you have done.  I really learned a lot by going through the demos.  And if my current work pans out well, I think I might have something to add back.  I will let you know if/when my ideas work.

________________________________

**Comment by taridyn** [comment]
I have no idea how to remove this bug report...  Can somebody else do it?

Btw, if you want to see the issue, just add a line renderer to anything and turn on single pass stereo renderer.  It is fairly obvious.  But, it is a unity bug, not VRTK.

**Comment by thestonefox** [comment]
Yeah there seems to be some issues with single pass in unity at the moment, really messes up effects too!
