### ISSUE TITLE
RadialMenuButton not updating current selection

### ISSUE THREAD

**Issue by eetteri** [thestonefox/SteamVR_Unity_Toolkit#608]
Adding radial menu for controller let's you hover and interact with buttons ok, but after pressing any button, the highlight indicating currently selected button won't change from button on 90 degree angle. This is evident also on the 030 example scene.

**Comment by thestonefox** [comment]
Are you able to provide steps to reproduce on the 030 example scene?

**Comment by eetteri** [comment]
Actually I think what I'm seeing is the #609 what I was mistakingly thinking was highlight on currently selected menu item.

Steps would be just open the 030 example straight from repo and start interacting with either of the controller.

**Comment by thestonefox** [comment]
There is a PR open to fix that

https://github.com/thestonefox/SteamVR_Unity_Toolkit/pull/610

Hopefully will be merged soon
