### ISSUE TITLE
VRTK_Lever connectedTo property for attaching to moving objects

### ISSUE THREAD

**Issue by mlabus93** [thestonefox/SteamVR_Unity_Toolkit#611]
@10FingerArmy The VRTK_Button script has a public member GameObject 'connectedTo' for attaching the button object to another game object (for movement purposes). The VRTK_Lever script does not. I added this locally for me in the same style as the button script. I think it would be a nice enhancement. Let me know if there is something issue I'm not seeing that would break it.

**Comment by 10FingerArmy** [comment]
Great! The only reason it's not there yet is that I didn't have time to add it. If it works I recommend you do a PR to get it officially into the toolkit!

**Comment by mlabus93** [comment]
Ok cool, this is my first commit to this repo and I will try to get it done tonight.
