### ISSUE TITLE
VRTK_OutlineBasic.shader isn't drawn atop skybox

### ISSUE THREAD

**Issue by getwilde** [thestonefox/SteamVR_Unity_Toolkit#623]
When seen in front of a skybox, the VRTK_OutlineBasic.shader isn't visible.

Solution is to change `ZWrite Off` to `ZWrite On` at line 36.  (I see your existing inline comment asking whether this should be a property.)

**Comment by thestonefox** [comment]
if zwrite is on though, it will also show up through any object, right?

i wonder why a skybox blocks the outline, i would have thought it would be at the back of the z index :(

**Comment by getwilde** [comment]
I wondered about that too. But it doesn't seem to be an issue. The controller (for example) is still drawn on top of the outline.

**Comment by thestonefox** [comment]
But if you put the controller behind another object does the outline still draw on top so you see the outline through other objects (like wall hack)

**Comment by thestonefox** [comment]
"should" be fixed with https://github.com/thestonefox/SteamVR_Unity_Toolkit/commit/336cf787a75ebea05f4e0193e583a9a97e7ed2ca

**Comment by getwilde** [comment]
The fix you came up with seems to work as well (and makes more sense).  Thank you!
