### ISSUE TITLE
Scene 006 Doors won't open

### ISSUE THREAD

**Issue by kjm16** [thestonefox/SteamVR_Unity_Toolkit#63]
Nothing happens when I hit the use button on the doors, but I can pick up and throw the cube.
Unity 5.4.0b17

**Comment by thestonefox** [comment]
What button are you pressing to use items?

**Comment by kjm16** [comment]
Trigger

**Comment by thestonefox** [comment]
Are you able to try in unity 5.3 to see if it's a problem with 5.4?

**Comment by kjm16** [comment]
Fresh install of 5.3.4f1 same issue.

**Comment by thestonefox** [comment]
Try the latest version (commit 2e28c99f859d156bc1d209da1806c79141ed599b )

And see if it has fixed the issue.

**Comment by kjm16** [comment]
It works now tested in 5.4! Now the only issue is the head collision not working.

**Comment by thestonefox** [comment]
Cool. I'm going to try install 5.4 today and try see what's going on
