### ISSUE TITLE
Scene 008, 013, 014, and 019 trigger doesn't activate "use" on items

### ISSUE THREAD

**Issue by kjm16** [thestonefox/SteamVR_Unity_Toolkit#64]
I can pick up the whirlygig and gun but can't make them shoot or spin. On 019 the pointer mechanic works but trigger doesn't work on the non-pointer activated one.
Unity 5.4.0b17

**Comment by thestonefox** [comment]
I'm wondering if all these issues are related to your version of unity. Could you try it in unity 5.3?

**Comment by braden-smith** [comment]
Getting same on guns on scenario14 (haven't tried any other scenarios yet). Using Unity 5.3.4

Old version SteamVR_Unity_Toolkit repository + upgrade to SteamVR1.10 = guns still fire.
Current version (1 hour ago) of SteamVR_Unity_Toolkit + upgrade to SteamVR1.10 = guns no fire

**Comment by kjm16** [comment]
Just did a fresh install of 5.3.4f1 re-downloaded everything in a new project and got the same results.

**Comment by thestonefox** [comment]
OK I know what the problem is, I'll fix it later today

**Comment by thestonefox** [comment]
Fixed with commit 2e28c99f859d156bc1d209da1806c79141ed599b
