### ISSUE TITLE
Something strange in VRTK_BasicTeleport_UnityEvents.OnDisable()

### ISSUE THREAD

**Issue by gpvigano** [thestonefox/SteamVR_Unity_Toolkit#642]
I found, by chance, that in VRTK_BasicTeleport_UnityEvents.OnDisable() event handlers are added again (+=) instead of being removed (-=), is this a bug?
In case this can help, I also checked every OnDisable() method in VRTK and none of them include a "+=".

**Comment by thestonefox** [comment]
What line are they getting added in again?

**Comment by thestonefox** [comment]
Oh in the UnityEvents Helper for it. Yeah that will be a bug they should be `-=`

**Comment by gpvigano** [comment]
OK, anyway I checked all the other OnDisable() in VRTK and they all have `-=`

**Comment by gpvigano** [comment]
I can't see any commit after this issue, so I made a PR ( #644 ).
