### ISSUE TITLE
Always enabled pointer

### ISSUE THREAD

**Issue by thesbros** [thestonefox/SteamVR_Unity_Toolkit#70]
Is there a way to always have a pointer enabled, instead of having to use a button?

**Comment by thestonefox** [comment]
There isn't but I could add an option to allow this if you want.

What would you expect it to do though? always be on but only throw the destination set event (i.e. teleport me now event) when you press a button?

**Comment by thesbros** [comment]
@thestonefox I was thinking for something like a main menu screen, where I can point at different buttons (e.g. Singleplayer, Multiplayer, Options), then hit the trigger and change the scene.

**Comment by thestonefox** [comment]
@thesbros Ok so basically the beam is always on but doesn't throw it's event till you hit the button.

I'll look to add this feature (maybe today)

**Comment by thesbros** [comment]
Exactly. Thanks!

**Comment by thestonefox** [comment]
Completed with f690eb229231563cccbec1e852c439f9028bd9f3

There is a new option on the pointer script called "Beam Always On"

Should do what you need.
