### ISSUE TITLE
[Interactable Object] Create a bow and arrow firing action

### ISSUE THREAD

**Issue by thestonefox** [thestonefox/SteamVR_Unity_Toolkit#74]
Copy the Longbow mechanic in The Lab.

Also may be worth having an option to get the arrow from your back like in Holopoint

**Comment by EctoArckanox** [comment]
Great ! An if I may, make sure it's 100% ambidextrous, like in the Lab.

**Comment by thestonefox** [comment]
@EctoArckanox Yeah definitely, the ability to support left/right handed players is a must.. Some devs are forgetting about this for some reason :/

**Comment by ecaginicolau** [comment]
+1 for this feature
Thanks for the hard work on your toolkit

**Comment by jakk2809** [comment]
This is a great idea! I've been trying to work on this, but also retain the functionality of the toolkit. In the Lab, the bow (and balloon item which is usable) can only be dropped at specific locations and those items hide the controller. I ended up adding a public variable isGrabbable to the InteractableObject instead so that the object decides if the controller is hidden.

I'm also trying to experiment with turning parameters on and off when the object is grabbed. For example, the bow in the Lab clips through objects so I had to turn on isKinematic to get the same effect. I'm still trying to figure out how to make the bow not pass to my arrow hand when I want to load an arrow. I think it's hitting the bow's collider and just grabbing it like normal.

Thanks for working on this toolkit!

**Comment by thestonefox** [comment]
@jakk2809 Cool, maybe you could work on this feature too if you have some good ideas.

I think the concept of the specific placeable location of items as seen in The Lab is something I'm definitely going to implement, but it should be for all objects.

I'm guessing the way it works is you attach this script to your object and it creates a new object where you place the item in the editor, then it sets this as being the only place you can pick it up or put it down. Need to figure out how to do the outline shape of it though as done in the Lab (maybe first iteration I'll just have a box appear).

I also want to do object snapping boundaries, like seen in Job Simulator where you only need to put an object into a near approximation and it will know how to snap into place.

I also like your idea that objects may not want to hide the controller. I wonder if the interactable object should have an override, something like never hide on interaction?

**Comment by jakk2809** [comment]
For the outline, I think they are using a custom shader something like (http://wiki.unity3d.com/index.php/Silhouette-Outlined_Diffuse). Also, I think you're right about creating another object where the item's default location is. If you pickup the bow from the table and keep your hand there, the controller model hides, but the outline of the controller stays which might mean that the controller is detecting a touchable object which is just the collider of the "placeholder" object.

Anyway, back to the bow XD. I saw this video of someone trying to get one to work, but it's very "messy" and relies too much on transforms (https://www.youtube.com/watch?v=lq0zyLtohdY). I'm really new to Unity and just learned about Configurable joints (joints in general actually lol) so I'm guessing that's how the Longbow works. The arrow can be constrained to slide along a single axis relative to the bow and and alignment with two hands will have certain constrains on the grab points so it allows you to twist your controller a bit.

**Comment by thestonefox** [comment]
@jakk2809 That custom shader is a bitch on the standard unity controllers because they have so many outlines on the controller base (every button, touchpad, trigger is also outlined).

I wonder if The Lab created their own controller model or whether they're doing another trick (which is to have a second camera that just deals with the outline shading). I've not cracked this outline thing yet, it would be nice if that shader just did it, but it doesn't :(

Yeah you're right, it will rely on a joint with a limit. I haven't had a play with it yet, I hope to start on it next week.

**Comment by jakk2809** [comment]
@thestonefox I think I've seen the 2nd camera trick used for bloom in a regular 3D game, but I haven't tried it in VR. I noticed there are different variants of highlighting, when in the Valve loading screen and when in the Lab scene. In the Lab scene the trigger is not outlined, only the body. I wonder if they have a second more solid controller body model just for the outline, but keep it transparent so only the outline can be seen (like the placeholder for the bow).

**Comment by thestonefox** [comment]
This guy has done a pretty awesome job on a bow mechanic for Unity

https://www.youtube.com/watch?v=shxS2-ebARQ

I'd love him to bring it over to the toolkit, not sure though as he's building a game around that mechanic.

**Comment by jakk2809** [comment]
@thestonefox Yeah, he's using your toolkit and he got it to work all the grabbable stuff. I'm having trouble using joints for the bow since there are joints already attaching the bow and arrow to the controllers separately. It's like you have to destroy the joint and use a configurable joint so you can rotate your controllers and still do 2-handed aiming.

**Comment by thestonefox** [comment]
@jakk2809 I spoke to the dev on reddit he said he's happy to help out building something for the toolkit.

I'm going to ask him for his code as a starting point which should help loads.

**Comment by jakk2809** [comment]
@thestonefox Sounds great! I'm glad I'm not the only one that had trouble with joints as the default grab mechanic.

**Comment by thestonefox** [comment]
Joints seem only useful for holding items like guns or swords. Anything that stays fixed really. There is also the tracked object grab type but it suffers from the catch up issue.

There may be a requirement for a new grab type for things like bows.

**Comment by jakk2809** [comment]
Parenting perhaps? I've seen lots of people use that and they just work with transforms. Physics probably isn't required while actually drawing the bow. The only time it would be needed is when the arrow is released.

**Comment by thestonefox** [comment]
Yeah I think parenting is a good solution. You want fixed tracking, well actually you are just saying the bow is the controller model instead of a hand. That could work quite well.

**Comment by Blueteak** [comment]
I'm the dev for the archery game linked above (thanks for the kind words!). I think you will need a bow/arrow prefabs for a full experience. Not sure exactly how to create the actions if objects are not present. I will check into a super simple prefab setup. Also I had to change the joint system to a parenting system to get it to work!

**Comment by thestonefox** [comment]
@Blueteak hey :) nice to see you here!

Yeah I think a parenting grab mechanic is required, which I think will be useful for other items as well anyway so it's a good addition, I'm going to take a look at implementing that mechanic, should be straight forward enough.

Hopefully I'll make a start on this sometime this week!

**Comment by jakk2809** [comment]
@Blueteak Hey! Thanks for helping with this project! (I'm ikonakona on reddit and youtube, still have to change my github name XD).

Yeah, an arrow prefab might be the way to go. I noticed when trying to implement 2 handed aiming that the default orientation of the bow is important. When I parented the bow to the controller, I had to set a non-zero snapToRotation to fix it.

I'm wondering if the bow can have empty childs that are adjustable to define things like the grip, arrow rest, and nock so that it can be easily adjustable based on what model is used.

**Comment by Blueteak** [comment]
Added pull request with fully functional Archery firing system (Ambidextrous).

**Comment by thestonefox** [comment]
@Blueteak just downloaded it and checked it out! awesome work!!

just looking through the PR now, i'll comment on the PR, somethings like finding the Game_View will need updating because Unity 5.4 doesn't have a Game_View script anymore (the SteamVR plugin actively removes it on 5.4! go figure!)

but seriously, awesome work, that bow feel is so nice and natural!

**Comment by thestonefox** [comment]
Added a new branch with some preliminary work in:

https://github.com/thestonefox/SteamVR_Unity_Toolkit/tree/feat/archery-mechanic

Most of the work is from @Blueteak pull request, it's largely a refactor, clean up and to get working with existing code (that is newer than the @Blueteak remote branch).

Check it out, give it a test, and gizza feedback :)

**Comment by thestonefox** [comment]
New version of the branch, has some new additions:

https://github.com/thestonefox/SteamVR_Unity_Toolkit/tree/feat/archery-mechanic

  * You can now fire an arrow and then pick the arrow back up and fire it again
  * The quiver is now a generic object that is an arrow spawner and can be placed anywhere, in this scene there is a spawner (the red cube) and one that is attached to the camera head (like a head quiver). This makes it possible to spawn arrows from anywhere.
  * Fixed the issues with controllers disappearing when dropping arrows (or bow)

I'm sure I've done other stuff, well it's working pretty well (imho) but as always feedback is wanted!

**Comment by thestonefox** [comment]
Quick update to the branch, added haptic feedback on the pull

**Comment by thestonefox** [comment]
completed with commit 08a2cc0c24c830f00c5150f170c34492ad12ce4f
