### ISSUE TITLE
[Project] Make initial release and tag future releases with version numbers

### ISSUE THREAD

**Issue by thestonefox** [thestonefox/SteamVR_Unity_Toolkit#75]
As things are starting to get a bit more settled, it's worth now doing a release and tagging any new releases so people can have consistency in their own projects.

Each release should also come with a unity package to allow easy import. It's also worth putting these packages onto the Unity asset store.

Do the following issues before do this:

https://github.com/thestonefox/SteamVR_Unity_Toolkit/issues/55
https://github.com/thestonefox/SteamVR_Unity_Toolkit/issues/58
https://github.com/thestonefox/SteamVR_Unity_Toolkit/issues/60

**Comment by mmd1080** [comment]
This may warrant its own issue, but have you considered using Github's Wiki feature? The readme is pretty unruly for newcomers (though everything before "What's In The Box" is excellent and absolutely appropriate)

**Comment by thestonefox** [comment]
@mmd1080 I did apply for a free readme.io account (some time ago) because I agree, the documentation in the readme is not very useful.

readme.io don't seem interested in getting back to me with a free open source offering though as they advertise :(

I'll take a look at github wiki and see if it's appropriate :)

**Comment by thestonefox** [comment]
I've done this. Still want to update the wiki, I'll create a new task for that.
