### ISSUE TITLE
[Suggestion] Teleportation Recharge & Ability to teleport to certian objects

### ISSUE THREAD

**Issue by xx1guardian1xx** [thestonefox/SteamVR_Unity_Toolkit#77]
Hi, first off the kits great I just have some issues, a lot of the code you've written isn't explained and I have no idea where certian parts do what so I whilst I did try to do these parts myself and got it working in some cases, it's extremely buggy.

A teleport recharge option would be nice, so that once a player has teleported they can no longer teleport for the next 3 seconds or so.

The other issue is teleporting onto certian things, right now you literally can teleport onto anything if you can see it, including say a knee high table which breaks A.I. Trying to get to you. I sorta made a fix which makes the pointer check if an object has a certian tag but it's really halfassed.

Great kit though!

**Comment by thestonefox** [comment]
I can add a teleport delay on the teleport because script.

I'm still pondering the best way to prevent teleport to other objects. Tags are one way but tags are really limiting.

The other options are apply a script to other items or items have a certain name.

**Comment by xx1guardian1xx** [comment]
Whilst limiting, tags seem like the most viable. Having to apply That many scripts in big levels is going to be rather annoying in my opinion.

**Comment by thestonefox** [comment]
Problem with tags is if you need to then use the tag concept for something else you're out of luck as you can only apply 1 tag per object.

Having a script that you apply to each object is more versatile, I think you can apply a script to multiple objects at the same time too.

**Comment by xx1guardian1xx** [comment]
I guess you could put all your terrain under a certian empty game object and have some script that applys it to all child objects under that empty which could work

**Comment by thestonefox** [comment]
Yeah that's another possible idea. I wish unity would support multiple tags, would make stuff like this much easier

**Comment by thestonefox** [comment]
Completed "teleport recharge" by adding pointer "Activation Delay" paramater in commit a1dba98d1d43faade90ac4367794df3075e052a1

**Comment by xx1guardian1xx** [comment]
Sweet! Thanks!
