### ISSUE TITLE
[Controller] Override controller hide on certain objects

### ISSUE THREAD

**Issue by thestonefox** [thestonefox/SteamVR_Unity_Toolkit#79]
Something in The Lab where the controller is hidden on interaction, but not always, the loading scene with the valve doesn't hide the controller.

My thoughts are:

Interactable Object has a "Do not hide controller" option, which overrides the controller "Hide on" option.

or the other way is:

Interactable Object has a "Hide on touch/grab/use" option which overrides the controller option.

The second way is more like the highlight colour override so is more in line with what currently happens.

Anyone else have any views?

**Comment by jakk2809** [comment]
I made a public bool hideControllerOnGrab variable in the InteractableObject script and changed these in the InitGrabbedObject and InitUngrabbedObject methods in the InteractGrab script.

`if (hideControllerOnGrab || grabbedObject.GetComponent<SteamVR_InteractableObject>().hideControllerOnGrab)
        {
            controllerActions.ToggleControllerModel(false);
        }`

`if (hideControllerOnGrab || grabbedObject.GetComponent<SteamVR_InteractableObject>().hideControllerOnGrab)
        {
            controllerActions.ToggleControllerModel(true);
        }`

I think this is similar to the second way you mentioned, but it needs the hide on the controller disabled.

**Comment by thestonefox** [comment]
@jakk2809 Yeah that's the basic premise of the second idea

I can probably make it so it overrides whatever you select on the controller (the touch override does this).

I'm just torn over which way round to do it...

Interactable objects either have a toggle overrides the hide, so it always shows.

or

Interactable objects can just have a hide toggle directly on them, so you dont need the hide controllers on the controller toggled for it to work.

The option that has the hide toggle on the controller means, you can't really mix and match very well.

Which is why i think the override to show works better.


This is the scenario.

  * Hide controller on grab is set on the controller

  * So all objects when grabbed hide the controller.

  * Then when you want an item not to hide the controller you would toggle that on a specific item.

------

The problem with this is the inverse scenarion

  * Hide controller on grab is turned off on the controller

  * So all objects when grabbed show the controller

  * Now if you want to hide the controller on a specific item, this checkbox no longer works.


Need to figure out which is the more common scenario.

**Comment by thestonefox** [comment]
Trello card https://trello.com/c/LGCuAyoM

**Comment by gpvigano** [comment]
What about using in VRTK_InteractableObject an enum with 3 states?
```
        public enum ControllerHideMode
        {
            Default,
            OverrideHide,
            OverrideDontHide,
        }
        public ControllerHideMode hideOnGrab = ControllerHideMode.Default;
```

**Comment by thestonefox** [comment]
yeah that's a good idea, nice solution

**Comment by thestonefox** [comment]
fixed https://github.com/thestonefox/SteamVR_Unity_Toolkit/pull/348
