### ISSUE TITLE
'assetPath' does not exist in current context. StramVR_SkyboxEditor and Unity 5.2.1f1

### ISSUE THREAD

**Issue by BeyondReal** [thestonefox/SteamVR_Unity_Toolkit#80]
In the script SteamVR_SkyboxEditor the variable 'assetPath' cannot be seen on lines 322 and 369 when Unity5.2.1f1. 

Is there a way to show this variable? I see the Platform dependent compilation at the top of code but I am unsure how to edit it.

**Comment by BeyondReal** [comment]
Sorry this is the steam VR utility and not this toolkit. Please delete this issue.

**Comment by thestonefox** [comment]
No worries :)
