### ISSUE TITLE
[Interaction] Allow controller to push objects, buttons when not grabbing

### ISSUE THREAD

**Issue by thestonefox** [thestonefox/SteamVR_Unity_Toolkit#82]
This is the concept that the controller can be used to push items around and push buttons.

The solution so far is:

When you aren't touching any interactable object but press the grab button, then a rigidbody child is added to the controller which will push items around or push buttons from the tip of the controller.

If you're touching something when you press the grab button, the rigidbody isn't created so it doesn't interfere with the grabbing of the object.

This is the latest branch to test:

https://github.com/thestonefox/SteamVR_Unity_Toolkit/tree/feat/rigidbody-on-grab-when-no-touch

**Comment by jakk2809** [comment]
Works very well! It does feel a little weird that you have to squeeze something just to push something out of way. Maybe there's some way to have a rigidbody all the time and be able to grab things. It feels more intuitive.

Job Simulator has something like that where you can push things with your hand and grab things. The boundary for grabbing seems a bit bigger than for pushing. There's also a video from GoogleIO that shows something similar, but I can't tell if they're holding down a button to active pushing.

https://youtu.be/lGUmTQgbiAY?t=10m16s

**Comment by thestonefox** [comment]
@jakk2809 I think the way job simulator do it is by having the rigid body on the controller all the time, but only some items are collidable with the rigidbody on the controller, because you can't hit everything with just your hands.

Having the rigidbody turned on all the time would be quite cumbersome as you may swing your controller around and knock a bunch of things flying without meaning to.

It's possible with this to have the grab collider larger than the push collider (because they're 2 separate colliders).

I'm just concerned having it on all the time would cause game mechanic issues. As for the job simulator approach, you'd need to tag items as ones that can collide and ones that can't. I need to play a few more games and see what other's are doing too.

**Comment by jakk2809** [comment]
I'm wondering if layers will make it easier to control collisions globally rather than looking for tags in OnCollisionEnter. I tried using 2 colliders (one on the parent, one on a child) and it was tough to manage with only one script since children colliders will call the parent's Collider/Trigger events.

**Comment by frozenMeatpopsicle** [comment]
Have you seen "Surgeon Simulator VR: Meet the Medic"? It's got this neat feature where when passing your hand through a solid object, it leaves your in-game hand behind, and your controller is now the skeleton of your hand. It's basically a method to prevent you from interacting with stuff outside of bounds. For instance, you wouldn't be able to poke your hand through a wall and cheat teleport.

**Comment by thestonefox** [comment]
@frozenMeatpopsicle Yeah I've played Surgeon Simulator. I'm not a fan of how their hands stop, feels really disjointed, I guess it's a solution to the annoying clipping problem.

I'm thinking of doing two separate solutions to this.

1: is the current one where you activate the rigidbody on pressing the grab button as that has a level of use.

2: a completely new script that you apply to your controller that manages the rigidbody regardless of grabbing. This way you can use the rigidbody stuff without ever needing the grab script. This way would definitely benefit from the surgeon sim hand stopping.

**Comment by thestonefox** [comment]
I'm going to merge in my current solution as it's ok to start with and i'm having too many diverging branches and don't want to get into conflict hell!

**Comment by thestonefox** [comment]
Completed with aa31355238a9fa57de348ba1f62b4ba6dee7bae1

(i'll do more work on this in the future)
