### ISSUE TITLE
Controller doesn't reappear after destroying grabbed gameObject.

### ISSUE THREAD

**Issue by holmesal** [thestonefox/SteamVR_Unity_Toolkit#83]
Hey! Awesome work on this :-D

I'm implementing the "smash a globe into your face to go to that scene" interaction, by surrounding the player's head with a collider and transporting them when the grabbed object enters that collider. I want to instantly destroy the currently-grabbed object, even though the player may still be holding the trigger down.

The issue is that if I immediately destroy the grabbed gameObject, my controller never reappears. It appears that `SteamVR_InteractableObject` thinks that an object is still being held.

Is there any way to manually "ungrab" an object? I see that `ForceUngrab` is protected.

Here's my hacky solution, right now:

* Disable `isTrigger` on the grabbed object's colliders. I *think* this trips the force threshold check, which causes the object to be ungrabbed.
* Make the object invisible.
* After a short delay, destroy the object.

``` csharp
using UnityEngine;
using System.Collections;

public class TransportBall : MonoBehaviour, IGrabbable {
	
	// The transform of the play area
	public Transform playAreaTransform;

	public void onGrab() {
		Debug.Log("TransportBall was grabbed!");
		// set colliders to be triggers
		// this is so we can fully mash the transport ball into our face
		transform.GetComponent<Collider>().isTrigger = true;
	}
	
	public void onRelease() {
		Debug.Log("TransportBall was released!");
		// set colliders to not be triggers
		transform.GetComponent<Collider>().isTrigger = false;
	}
	
	void OnTriggerEnter(Collider other) {
		if (other.tag == "Player") {
			Debug.Log("Collided with player!");
			// Set the player's play area to the level start point
			// TODO - let them ride up in an elevator
			playAreaTransform.localPosition = new Vector3(0,0,0);
			playAreaTransform.localScale = new Vector3(1,1,1);
			
			// Re-enable the collider - this will cause InteractableObject to release the grab (based on force calc, I think)
			transform.GetComponent<Collider>().isTrigger = false;
			
			// This would be awesome, but doesn't exist:
			// gameObject.GetComponent<SteamVR_InteractableObject>().Ungrab();
			
			// Destroy the transport ball (after a waiting bit to allow the collider to cause the object to be ungrabbed)
			// Make it invisible right away
			GetComponent<MeshRenderer>().enabled = false;
			Destroy(gameObject, 0.2f);
		}
	}
}

```

**Comment by thestonefox** [comment]
There is a public ForceRelease method on the controller script `SteamVR_InteractGrab.cs`

You know which controller is grabbing your object because it is passed into the Interactable Object call:
`public virtual void Grabbed(GameObject currentGrabbingObject)`

`currentGrabbingObject` will be the controller doing the grabbing, which gets stored in the variable `grabbingObject`. On your collision, just call the 'ForceRelease()` method on grabbing object and it will release the item. Then you can destroy it accordingly and the controller will be reset.

Hope that helps.

**Comment by holmesal** [comment]
That worked perfectly. Thanks!
