### ISSUE TITLE
Slide Drawers or other objects with limited range

### ISSUE THREAD

**Issue by DrMerlin** [thestonefox/SteamVR_Unity_Toolkit#84]
Enhance the grab feature to allow for clamped range on objects like drawers, levers, doors, etc. that allow the player to grab and slide an object within a defined range.

Incredibly awesome toolset, bytheway.

**Comment by thestonefox** [comment]
Have you checked out the example scene `Assets/Examples/021_Controller_GrabbingObjectsWithJoints` ?

It has a selection of items that have joints such as a box, a door and a drawer.

**Comment by DrMerlin** [comment]
I will check it out- sorry for the noise if this is just my mistake.
