### ISSUE TITLE
Bezier pointers (and teleport) work in editor but not in build.

### ISSUE THREAD

**Issue by x-mugen-x** [thestonefox/SteamVR_Unity_Toolkit#85]
I have tested both my personal project and building the example scenes included in the toolkit. In both cases the bezier pointers either fail to show or occasionally show but teleport does not occur. This is occurring in built projects using Unity 5.4.0b14.

Any help much appreciated,
Thanks.

**Comment by thestonefox** [comment]
Can I just check that you have StreamVR running (prior to opening unity) and that your controllers are turned on and tracking before you run your scene?

Also, do you have the teleport script applied to the CameraRig?

**Comment by thestonefox** [comment]
Nevermind, I just realised your question.

You're talking about when you create a build.

You need to include the custom shader.

watch here:

https://www.youtube.com/watch?v=IsmYoLTmX4c&list=PLRM1b2lKjTbdFJtYv_SNAb3NvYp-Gl7nZ&index=22
