### ISSUE TITLE
Networking breaks Pointers

### ISSUE THREAD

**Issue by mimminito** [thestonefox/SteamVR_Unity_Toolkit#87]
I am doing a networked game and it seems to break the pointers. Both pointers do not teleport you in the direction you are pointing, and the Bezier Pointer faces the wrong direction (up to 90 degrees off) whilst flashing the correct pointer briefly now and then. Its very odd. Any suggestions?

**Comment by thestonefox** [comment]
I've never done any networking in Unity, so not too sure, but I can't see why a Networking component would have anything to do with the pointers.

If you remove your networking element does it still work?

**Comment by mimminito** [comment]
Ive tried many tests and only when its networked does it cause issues. Due to the networking I have to disable scripts and then enable them on the local player only. Now testing this in a local game (no networking) the enabling works fine. So I'm not sure whats going on here, I'm doing more investigation now.

**Comment by mimminito** [comment]
It seems its an issue with the NetworkChildTransform components. Not sure why, but removing these fixes it. Something ill dive into as I go further down the networking route. At least for now I can move around.

**Comment by thestonefox** [comment]
I'll close this for now. If you figure out what the problem was then let me know :)
