### ISSUE TITLE
[Suggestion] Scaling Camera/World Up and Down...

### ISSUE THREAD

**Issue by xEvoGx** [thestonefox/SteamVR_Unity_Toolkit#89]
Hey Stone. I'm not certain if this is even something that necessarily needs any specific code function to work beyond literally just scaling gameObjects...

...but as you may be aware, games like **Out of Ammo** and **Final Approach** have you standing over the gameplay area, staring down at the world as if it were a diorama; let's say you're a giant for the sake of the example. There are mechanics specific to this mode such as setting up your structures or calling in strikes (**Out of Ammo**). If you choose then, you can click on a unit or structure, and zoom down to the ground into _First Person_, allowing you to take over that unit and play in what amounts to a first person shooter for example...

...scaling **[CameraRig]** doesn't appear to do anything, and not being in front of my VR rig as I write this, I can see _Scale_ variable in **Steam VR_Game View** script that's on the **Camera(head)** gameObject. If that doesn't adjust world scale, I can't imagine the only way to do this would be to actually _scale the world_ up or down, as that sounds incongruous and would introduce it's own problems. 

Any ideas on this?

Thanks man!

-Steven

**Comment by thestonefox** [comment]
I'll take a look into it and see what's possible!

**Comment by xEvoGx** [comment]
Yay!

**Comment by thestonefox** [comment]
@xEvoGx you don't get any difference when you scale the CameraRig transform?

I've just changed the camera rig to a scale of 10,10,10 and the world is tiny, but my camera rig is ok.

SteamVR_GameView is the renderer for the game view (if you're not viewing in your headset e.g. the Game tab in Unity), putting a different scale in here just changes the view outside the headset.

Scaling the camera rig worked for me though.

**Comment by xEvoGx** [comment]
Oh hmmm...then lets chalk this one up to me speaking before actually testing it myself!

Sheesh I'm the worst lol.

Okay well if that's all that is needed to work then I think we're good here! I appreciate you humoring me on this haha

Cheers Stone
