### ISSUE TITLE
InteractGrab :78 - GetComponent<RigidBody> with no RigidBody component

### ISSUE THREAD

**Issue by DrMerlin** [thestonefox/SteamVR_Unity_Toolkit#92]
SteamVR_InteractGrab.cs
`    private void Start()`
`    {`
`        //If no attach point has been specified then just use the tip of the controller`
`        if (controllerAttachPoint == null)`
`        {`
78:`            controllerAttachPoint = ``transform.GetChild(0).Find("tip").GetChild(0).GetComponent<Rigidbody>();`
`        }`
....

I often get errors here in my own scenes- not sure why they don't appear in the examples- but it might be due to my instantiating the CameraRig at Scene load, instead of it being apart of the Scene.

Anyways, line 78 makes a call to the rigidbody component attached to the tip/attach gameobject.  In my own scenes, there is no rigidbody component on tip/attach.  Not sure why.  So to work around that I've changed line 78 to be:

`        if (controllerAttachPoint == null)`
`        {`
`              if (transform.GetChild(0).Find("tip").GetChild(0).GetComponent<Rigidbody>() == null)`
`			{`
`				Rigidbody rb = transform.GetChild(0).Find("tip").GetChild(0).gameObject.AddComponent<Rigidbody>();`
`				rb.isKinematic = true;`
`			}`
`			controllerAttachPoint = transform.GetChild(0).Find("tip").GetChild(0).GetComponent<Rigidbody>();`

Is there a better way, or a reason I'm not correctly pulling in the rigidbody?

(Also, I'm having a probably related problem- the model itself isn't loaded for the first couple frames- so Find("tip") is also failing during start.  So I moved this block to an Update method and it works fine for me there.

**Comment by thestonefox** [comment]
@DrMerlin Are you using the [CameraRig] Prefab from the SteamVR_Unity_Toolkit/Prefabs folder or the one from the Valve SteamVR prefabs folder?

The Valve SteamVR prefab is missing these elements until runtime (no idea why). If you look at their TestThrow example scene then they have an object with these elements in (so they basically have 2 different prefabs with no reasoning why!). Basically the prefab I include is the one from the Valve's TestThrow example.

**Comment by DrMerlin** [comment]
Probably.  I will take a look.

Is there a way for me to get simple answers for my dumb questions outside of the issues system?  I think I'm doing this wrong.

**Comment by thestonefox** [comment]
@DrMerlin sure, email me thestonefox at gmail dot com

**Comment by DrMerlin** [comment]
Can do- but I don't want to waste your time if at all possible.  Is there a user group somewhere?  If not, we should set one up.

**Comment by thestonefox** [comment]
@DrMerlin a user group is a good idea. Not sure the best place to start one.. google groups is an option unless someone else has another idea?

**Comment by teatime** [comment]
https://slack.com/ is very popular I'm currently a member of the VRdev
group on there already, loads listed here http://www.slacklist.info/

**Comment by DrMerlin** [comment]
Slack could be cool.  I don't see any sub forums at http://forum.unity3d.com/forums/virtual-reality.80/, which is too bad because that would be perfect.

**Comment by teatime** [comment]
I'm on one for this course: http://learn.vrdev.school/ and seems to work
fine. The free version would be fine for this, even with the 10,000 message
limit (it wipes older messages after this I believe)

**Comment by DrMerlin** [comment]
@teatime Is that site related to the slack channel?  How would one get an invite to the slack channel?  kotefare at gmail dot com, if you need it.

**Comment by teatime** [comment]
the slack channel for the course is by invite only to course members
unfortunately, but someone on there mentioned that they have seen other
channels out there. Apparently there is one called VRdevs which you need to
email Iestyn@lloyddigital Iestyn Lloyd for access. See
http://forum.unity3d.com/attachments/eyeswideopen-resourcemegalist-pdf.181937/
