### ISSUE TITLE
Adding Events for all actions on an Interactable Object

### ISSUE THREAD

**Issue by mimminito** [thestonefox/SteamVR_Unity_Toolkit#93]
I have a couple of suggestions here:

1. Replace current "events" with a UnityEvent instead. This will expose it inside the editor (could use a custom Editor script to hide these as there are a few) and works through scripting as well. Allows for a more generic approach to responding to the events.
2. Add in UnityEvent's for intractable objects. Currently no events are fired on these objects but it would be nice to have something to tell us when they have been grabbed, touched, used, etc.

**Comment by mimminito** [comment]
I have created the following script which you can attach to your interactable objects. This extends the SteamVR_InteractableObject class and exposes 6 events.

`using UnityEngine;
using UnityEngine.Events;
using System;

public class SteamVR_InteractableObjectEvents : SteamVR_InteractableObject
{

    #region Events

    [Serializable]
    public class StartTouchingEvent : UnityEvent<GameObject> { }

    [Serializable]
    public class StopTouchingEvent : UnityEvent<GameObject> { }

    [Serializable]
    public class GrabbedEvent : UnityEvent<GameObject> { }

    [Serializable]
    public class UngrabbedEvent : UnityEvent<GameObject> { }

    [Serializable]
    public class StartUsingEvent : UnityEvent<GameObject> { }

    [Serializable]
    public class StopUsingEvent : UnityEvent<GameObject> { }

    #endregion

    #region Public Variables

    [Header("Events")]
    public StartTouchingEvent OnStartTouching;
    public StopTouchingEvent OnStopTouching;
    public GrabbedEvent OnGrabbed;
    public UngrabbedEvent OnUngrabbed;
    public StartUsingEvent OnStartUsing;
    public StopUsingEvent OnStopUsing;

    #endregion

    #region Public Methods

    public override void StartTouching(GameObject touchingObject)
    {
        base.StartTouching(touchingObject);
        if (OnStartTouching != null)
        {
            OnStartTouching.Invoke(touchingObject);
        }
    }

    public override void StopTouching(GameObject previousTouchingObject)
    {
        base.StopTouching(previousTouchingObject);
        if (OnStopTouching != null)
        {
            OnStopTouching.Invoke(previousTouchingObject);
        }
    }

    public override void Grabbed(GameObject currentGrabbingObject)
    {
        base.Grabbed(currentGrabbingObject);
        if (OnGrabbed != null)
        {
            OnGrabbed.Invoke(currentGrabbingObject);
        }
    }

    public override void Ungrabbed(GameObject previousGrabbingObject)
    {
        base.Ungrabbed(previousGrabbingObject);
        if (OnUngrabbed != null)
        {
            OnUngrabbed.Invoke(previousGrabbingObject);
        }
    }

    public override void StartUsing(GameObject usingObject)
    {
        base.StartUsing(usingObject);
        if (OnStartUsing != null)
        {
            OnStartUsing.Invoke(usingObject);
        }
    }

    public override void StopUsing(GameObject previousUsingObject)
    {
        base.StopUsing(previousUsingObject);
        if (OnStopUsing != null)
        {
            OnStopUsing.Invoke(previousUsingObject);
        }
    }

    #endregion

}`

**Comment by thestonefox** [comment]
I've never used (or know much about) UnityEvents. I'll take a look into it and do a refactor to replace them

**Comment by mimminito** [comment]
As they are exposed in the editor its handy. But adding in events for actions on the interactable objects as well is very beneficial.

**Comment by thestonefox** [comment]
Is there a need for the interactable object to thrown an event?

You already get events thrown in the Interact_Touch/Grab/Use when an object is interacted with, and that object is included in the payload.

Having the event on the object as well, would that just be duplicating these events?

**Comment by mimminito** [comment]
I am using this with UNET right now, and to be able to do networking calls I need to attach a NetworkBehaviour to the interactable object. Now I don't want to mess around with the SteamVR Unity Toolkit and replace everything with NetworkBehaviour's (its not needed).

So instead I have a NetworkBehaviour script which subscribes to the events of the interactable object and processes these as required across the server. Without these events, I cannot sync things happening (such as firing a weapon or starting a particle effect).

I understand that in theory the events will be "duplicated" in some cases, but much like the Archery pull request on here, they have added in an event to know when the object has been grabbed.

If you can think of a better/cleaner way for me to handle this I'm all ears :) I dont mind just keeping this script for my own projects, but I thought it might be a handy addition for people.

**Comment by thestonefox** [comment]
Hmm, right so you need to know what's happened to that object by a third party and instead of listening for the controller events and having like a huge if statement checking for which object is picked up, you want to focus on the event for each object...

An event proxy (or message broker) could work here, where you have a class that's sole purpose is to have all the events register with it, then you register with that.

But I can see having the interactable object throw the events as well wouldn't be the end of the world.

Would be pretty much the same thing, except you include the controller index with the payload so you know what is grabbing it.

**Comment by thestonefox** [comment]
I'm going to add in the additional events. The bow/arrow mechanics require an OnGrab event on the interactable object. So i may as well whack them all in.

**Comment by mimminito** [comment]
Awesome :) Its working well for me so far. Maybe Unity events are not "required", but the exposure in the editor is handy and allows for linking to other components that dont know about your scripts (change some UI, trigger other actions within the scene, etc).

**Comment by thestonefox** [comment]
I've been reading a bit about Unity Events (they're still new to me).

The ability for them to work at design time is good because you can see what is registered to them, excellent for debugging.

However, they seem to be about 40% slower (from some benchmarks I've seen). I'm not sure the performance impact that would have, I need to do some more reading about them :)

**Comment by mimminito** [comment]
Sure. Ive been using them in lots of projects and not noticed any issues with performance, but I suppose if your using LOTS of events then it could become an issue.

**Comment by thestonefox** [comment]
they may be fine, i need to do some actual tests (after the reading). Just have to make sure they don't impact performance, especially in VR games where 90fps is paramount!

**Comment by mimminito** [comment]
Yeah totally understand. Standard events will keep the inspector cleaner as well.

**Comment by thestonefox** [comment]
I do like the neatness of the UnityEvents though, they seem cleaner to write and are actually more versatile.

**Comment by mimminito** [comment]
Definitely. Since they launched the new Unity UI its been so good to be able to use them, and as you say it makes things much more versatile.

But since you mentioned the performance I have noticed that the events are indeed slower (although the 10,000,000 invokes seemed a little overkill). Luckily I am only calling 4 events on the interactable object right now and they are not every frame, so its not an issue for me (yet).

**Comment by teatime** [comment]
I can't find the article at the moment but performance wise it indicated
that this outperformed the inbuilt Unity fire-hose style event handling by
quite a margin: http://wiki.unity3d.com/index.php/Advanced_CSharp_Messenger

**Comment by mimminito** [comment]
Sure, but might as well use C# delegates then. The bonus of UnityEvents is the editor exposure.

**Comment by teatime** [comment]
Very true

**Comment by thestonefox** [comment]
This work has been done and is in the Archery branch (silly that I didn't merge it before, but whatevz)

When that branch is merged this will be complete.

**Comment by mimminito** [comment]
Thanks @thestonefox really appreciate all of your work on this.

**Comment by thestonefox** [comment]
Completed with d86dbf9e8503d7eb1cc3ebdf150364d0bb768bb3
