### ISSUE TITLE
[Feature Request] interacting with picked up objects?

### ISSUE THREAD

**Issue by xx1guardian1xx** [thestonefox/SteamVR_Unity_Toolkit#95]
Would it be possible to have the interactable object script act as a child to the controller? Say I pick up a gun, and I have scripts checking if the gun is a child of the controller for it to work. e.g. if (is child) {Do gun stuff and check for the trigger being down and stuff) 

Is it possible to implement that because unless I'm being blind with the kit atm I can't seem to find any way to actually use the objects I pickup.

EDIT: So I'm re-reading and trying to use the the controlerindex/target, my script is on my object is there anyway to check IF a controller is holding the object and Which controller is holding the object?

EDIT 2: So controller index is actually a variable on a certian controller, I don't know why you need to know what controller your using when your already requesting data from a spefic controller.

The only way I could see to do this is to have a variable that an Object has been Grabbed on the actual objects gameobject rather than the controller? Well atleast that's what I think is needed.

Really stumbled on this, would appricate any explantation!

**Comment by mimminito** [comment]
Do you need to do processing on the gun or on the controller? On the gun, the SteamVR_InteractableObject script exposes IsTouched(), IsGrabbed() and IsUsing() methods to inform you if any of those actions are occuring.

On the controller there are events you can subscribe to which tell you if you are performing actions. These are exposed on the SteamVR_InteractGrab, SteamVR_InteractTouch and SteamVR_InteractUse scripts.

**Comment by thestonefox** [comment]
@xx1guardian1xx  - @mimminito is right, you don't need to do the processing on the controller.

If you look in the Examples/Scripts/Gun.cs file

It extends the Interactable_Object and then overrides the StartUsing Method.

Whenever a controller touches/grabs/uses an interactable object it executes a method (which does very little by default)

But when you override that and do your own stuff, you can get it to do whatever you want within the object.

As a side note though, a parent/child grab type is coming soon (it's part of the bow/arrow mechanics)

**Comment by xx1guardian1xx** [comment]
@thestonefox Well I've done the processing on the controller, mainly due to that I don't like having a wall of text document as I'm using a lot of gameobject compents on my gun, sadly it's a bit more complex than a simple fire and auto reload. 

I've managed to detect to make it so the script knowns if it's being picked up or not and this is done as a child class like gun.cs in the examples, however it's not shown in the examples (That I know of) where I can detect what controller the object is on. I know theres an event for it but I'm not too sure how to interact with that.

What would I need to write in the override to check that?

**Comment by thestonefox** [comment]
There are some new listeners being added to interactable objects (they're not in the master build yet)

But you would be able to use them to listen for when the object is picked up in a script attached to the controller, then do something with the results.
