### ISSUE TITLE
Climbing with controllers.

### ISSUE THREAD

**Issue by x-mugen-x** [thestonefox/SteamVR_Unity_Toolkit#96]
https://m.youtube.com/watch?v=VxINF6UGz9A

Not sure if something like this would be easily achievable by modding the grab script and (?) reversing the joint or parenting.

Just saw it and thought I'd share, sorry not sure how to set as a wishlist item.

Cheers.

**Comment by thestonefox** [comment]
I like that.

Yeah it would be doable using the events within the grab script, but a new script would be needed that sat on the CameraRig and just moved the play area Y position depending on where you grabbed.

I may look at implementing that, just cos it looks fun and is a nice mechanic.

Good find!

**Comment by x-mugen-x** [comment]
That makes sense.

Awesome! Thanks for taking a look.

**Comment by thestonefox** [comment]
Trello Card https://trello.com/c/OFptWSpu
